"""Avocats : trois cabinets complémentaires de Roussel & Associés (entreprises, victimes, pénal)."""

SCALE = '<path d="M16 5v22M9 27h14M6 9h20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/><path class="blade" d="M6 10l-4 8a4 4 0 0 0 8 0zM26 10l-4 8a4 4 0 0 0 8 0z"/>'
PEN = '<path class="blade" d="M22 4l6 6-14 14-8 2 2-8z"/><path d="M5 28h22" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/>'
SHIELD = '<path class="blade" d="M16 3 5 7v8c0 7 4.7 12.4 11 14 6.3-1.6 11-7 11-14V7z"/><path d="M11 16l4 4 7-8" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>'

SECRET = "Vos informations sont couvertes par le secret professionnel dès votre premier contact. Décrivez votre situation en quelques mots seulement."

SITES = [
  {
    "dir": "avocats/02-castel-avocats",
    "seo_h1": "Avocat des entrepreneurs à Lyon : création de société, contrats, recouvrement",
    "founder": ("Me Julie Castel", "avocate au barreau de Lyon, droit des affaires"),
    "photo": ("7876001", "three-business-professionals-discussing-a-contract-7876001", "Karola G"),
    "name": "Castel Avocats", "tagline": "Avocats des entrepreneurs · Lyon",
    "schema": "LegalService",
    "city": "Lyon", "cp": "69006", "street": "25 rue Garibaldi",
    "phone": "04 65 71 58 21", "tel": "+33465715821",
    "hours": "Du lundi au vendredi, 8 h 30 à 19 h", "hours_schema": "Mo-Fr 08:30-19:00",
    "zone_short": "Lyon et visio partout en France",
    "zone": ["Lyon", "Villeurbanne", "Rhône", "Auvergne-Rhône-Alpes", "Consultations en visio partout en France"],
    "zone_label": "Nous accompagnons les entreprises de :",
    "top3": "Forfaits annoncés avant de commencer",
    "form": "rdv",
    "legal": SECRET,
    "title": "Avocat droit des affaires Lyon · Création de société, contrats, impayés | Castel Avocats",
    "desc": "Castel Avocats accompagne les créateurs, TPE et PME à Lyon : création de société, statuts et pacte d'associés, contrats et CGV, bail commercial, recouvrement des impayés. Forfaits annoncés et abonnement juridique.",
    "fonts": ("Plus Jakarta Sans", "Plus+Jakarta+Sans:wght@600;700;800", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F6F7F9", chalk="#E7EAF0", ink="#14213D", muted="#56607A", line="#D6DBE5", accent="#F4B942", deep="#9A6A00"),
    "layout": "overlay",
    "icon": PEN,
    "eyebrow": "Avocats des entrepreneurs · Lyon",
    "h1": ("Un avocat pour votre entreprise,", "au prix annoncé, qui répond en 48 h."),
    "lead": "Créer votre société, rédiger vos contrats, récupérer un impayé, négocier un bail commercial : nous parlons le langage des dirigeants, annonçons nos forfaits avant de commencer et répondons à vos questions sous 48 h ouvrées.",
    "proofs": ["Forfaits annoncés pour les missions courantes", "Réponse à vos questions sous 48 h ouvrées", "Abonnement juridique mensuel pour les TPE et PME"],
    "cta": "Prendre rendez-vous", "note": "Premier rendez-vous de 30 minutes en visio pour cadrer votre besoin.",
    "badge": ("48 h", "pour répondre<br>à vos questions"),
    "alt": "Trois professionnels discutent d'un contrat dans un bureau moderne",
    "sit_title": "Où en est votre entreprise ?",
    "sits": [
      ("Je crée ma société", "Choix de la forme (SAS, SARL…), statuts sur mesure, formalités.", "Création de société"),
      ("J'ai un client qui ne paie pas", "Mise en demeure, injonction de payer, négociation.", "Impayés"),
      ("Je m'associe ou j'accueille un investisseur", "Pacte d'associés, entrée au capital, valorisation.", "Associés et investisseurs"),
      ("Je signe un bail commercial", "Relecture, négociation des clauses, renouvellement.", "Bail commercial"),
      ("Il me faut des CGV ou des contrats solides", "Conditions générales, contrats clients et fournisseurs.", "Contrats et CGV"),
      ("Je veux un avocat au quotidien", "Abonnement mensuel : questions illimitées et documents courants.", "Abonnement juridique"),
    ],
    "serv_eyebrow": "Nos domaines", "serv_h2": "Le droit de votre entreprise, de la création à la croissance.",
    "servs": [
      ("Création de société", "Conseil sur la forme juridique, rédaction des statuts, immatriculation."),
      ("Associés et levée de fonds", "Pacte d'associés, cessions de parts, entrée d'investisseurs."),
      ("Contrats et CGV", "Conditions générales de vente, contrats clients, sous-traitance, partenariats."),
      ("Recouvrement", "Mise en demeure, injonction de payer, procédure au tribunal de commerce."),
      ("Bail commercial", "Négociation, révision du loyer, renouvellement, départ des locaux."),
      ("Abonnement juridique", "Un forfait mensuel pour poser toutes vos questions et faire relire vos documents."),
    ],
    "steps_h2": "Travailler avec nous, concrètement.",
    "steps": [
      ("Rendez-vous de cadrage", "30 minutes en visio pour comprendre votre besoin."),
      ("Proposition chiffrée", "Forfait ou devis écrit, délai de réalisation annoncé."),
      ("Réalisation", "Documents rédigés, expliqués et ajustés avec vous."),
      ("Suivi", "Questions de suivi et mises à jour, à la demande ou par abonnement."),
    ],
    "jobs_eyebrow": "Dossiers récents", "jobs_h2": "Quelques exemples, anonymisés.",
    "job_labels": ("Mission", "Délai"),
    "jobs": [
      ("Start-up de 3 fondateurs", "SAS créée avec pacte d'associés et BSPCE", "Création et pacte", "3 semaines"),
      ("Agence de communication", "12 000 € d'impayés récupérés sans procès", "Recouvrement", "6 semaines"),
      ("Restaurant", "Bail commercial renégocié avant signature", "Bail commercial", "10 jours"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Des prix annoncés.", "Forfait ou devis écrit avant chaque mission, convention d'honoraires signée."),
      ("Des réponses rapides.", "Sous 48 h ouvrées, par écrit ou par téléphone."),
      ("Du concret.", "Des conseils applicables, pas de mémo de trente pages."),
      ("La confidentialité.", "Secret professionnel sur tout ce que vous nous confiez."),
    ],
    "reviews": [
      ("« Statuts, pacte d'associés et formalités réglés en trois semaines, au prix annoncé. Des réponses claires à chaque question. »", "Cofondateur · Start-up lyonnaise · Création de société"),
      ("« L'abonnement nous a changé la vie : on pose nos questions au fil de l'eau au lieu de laisser traîner. »", "Gérante · PME de 15 salariés · Abonnement juridique"),
    ],
    "faq": [
      ("SAS ou SARL : laquelle choisir ?", "La SAS offre plus de souplesse dans l'organisation et l'entrée d'associés, la SARL un cadre plus encadré par la loi. Le bon choix dépend de votre projet, du nombre d'associés et de votre statut social souhaité : nous le voyons ensemble."),
      ("Combien coûte un avocat pour créer une société ?", "Nous proposons un forfait annoncé avant de commencer, qui comprend le conseil, les statuts et les formalités. Il dépend de la complexité (associés, pacte, apports)."),
      ("Comment récupérer une facture impayée ?", "Souvent par une mise en demeure d'avocat, qui suffit dans beaucoup de cas. Sinon, l'injonction de payer permet d'obtenir un titre exécutoire rapidement, sans audience dans la plupart des cas."),
      ("Qu'est-ce qu'un abonnement juridique ?", "Un forfait mensuel qui vous permet de poser vos questions juridiques et de faire relire vos documents courants sans devis à chaque fois."),
      ("Faut-il un avocat pour un bail commercial ?", "Ce n'est pas obligatoire, mais un bail commercial engage souvent sur neuf ans : une relecture avant signature évite des clauses coûteuses sur le loyer, les charges ou les travaux."),
      ("Travaillez-vous en visio ?", "Oui, avec des entreprises partout en France. Les rendez-vous au cabinet restent possibles à Lyon."),
    ],
    "quote_h2": "Parlons de votre entreprise.", "quote_p": "Dites-nous en quelques mots ce dont vous avez besoin. Nous vous rappelons pour fixer un rendez-vous de cadrage.",
    "work_label": "Votre besoin",
    "works": ["Création de société", "Impayés", "Associés et investisseurs", "Bail commercial", "Contrats et CGV", "Abonnement juridique", "Autre"],
    "extra": ("company", "Votre entreprise", "Ex. : SAS de 5 salariés, en création", True),
    "avail": ["Dès que possible", "Cette semaine", "En visio", "Au cabinet"],
    "details_label": "Votre besoin en quelques mots",
    "details_ph": "Ex. : nous créons une SAS à trois associés et voulons un pacte",
    "success": "Merci {first}. Nous vous rappelons {when} pour fixer votre rendez-vous de cadrage.",
    "success_end": "",
    "nav": ["Nos domaines", "Comment ça se passe", "Dossiers", "Questions"],
  },
  {
    "dir": "avocats/03-delmas-victimes",
    "seo_h1": "Avocat des victimes d'accidents à Toulouse : accident de la route, dommage corporel",
    "founder": ("Me Pierre Delmas", "avocat au barreau de Toulouse, réparation du dommage corporel"),
    "photo": ("7876190", "man-sitting-beside-the-woman-crying-7876190", "Karola G"),
    "name": "Delmas Avocats", "tagline": "Défense des victimes · Toulouse",
    "schema": "LegalService",
    "city": "Toulouse", "cp": "31000", "street": "18 allées Jean-Jaurès",
    "phone": "05 36 49 27 63", "tel": "+33536492763",
    "hours": "Du lundi au vendredi, 9 h à 19 h", "hours_schema": "Mo-Fr 09:00-19:00",
    "zone_short": "Toulouse, Occitanie et visio",
    "zone": ["Toulouse", "Haute-Garonne", "Occitanie", "Déplacement à l'hôpital ou à domicile", "Visio partout en France"],
    "zone_label": "Nous défendons les victimes de :",
    "top3": "Premier échange téléphonique gratuit",
    "form": "rdv",
    "legal": SECRET,
    "title": "Avocat victime accident Toulouse · Accident de la route, dommage corporel | Delmas Avocats",
    "desc": "Delmas Avocats défend exclusivement les victimes à Toulouse : accidents de la route, accidents médicaux, agressions, chutes. Contestation des offres d'assurance, assistance à l'expertise médicale, honoraires en partie au résultat.",
    "fonts": ("Source Serif 4", "Source+Serif+4:opsz,wght@8..60,600;8..60,700", "Source Sans 3", "Source+Sans+3:wght@400;500;600"),
    "pal": dict(paper="#FAF7F4", chalk="#F0E9E2", ink="#2B2330", muted="#625A66", line="#E3DAD2", accent="#E3A07D", deep="#9B4A2A"),
    "layout": "split-right",
    "icon": SHIELD,
    "eyebrow": "Défense des victimes · Toulouse",
    "h1": ("Blessé dans un accident ?", "L'assureur a ses avocats. Vous avez droit au vôtre."),
    "lead": "Après un accident, l'assurance fait souvent une première offre bien inférieure à ce que la loi prévoit. Nous défendons uniquement les victimes : nous vous assistons lors de l'expertise médicale, chiffrons tous vos préjudices et négocions, ou plaidons, pour une indemnisation juste.",
    "proofs": ["Nous défendons uniquement les victimes, jamais les assureurs", "Premier échange téléphonique gratuit", "Honoraires en partie liés au résultat obtenu"],
    "cta": "Parler de mon dossier", "note": "Nous pouvons nous déplacer à l'hôpital ou à domicile.",
    "badge": ("100 %", "de nos clients sont<br>des victimes"),
    "alt": "Un avocat écoute une cliente émue dans son bureau",
    "sit_title": "Que vous est-il arrivé ?",
    "sits": [
      ("J'ai été blessé dans un accident de la route", "Piéton, cycliste, passager ou conducteur : la loi protège fortement les victimes.", "Accident de la route"),
      ("L'assurance m'a fait une offre", "Nous vérifions si elle couvre tous vos préjudices avant que vous signiez.", "Offre d'assurance à vérifier"),
      ("J'ai une expertise médicale prévue", "Vous y être assisté change souvent le résultat.", "Expertise médicale"),
      ("J'ai subi une erreur ou un accident médical", "Recours contre l'établissement ou devant les instances d'indemnisation.", "Accident médical"),
      ("J'ai été agressé", "Plainte, constitution de partie civile, indemnisation.", "Agression"),
      ("Un proche est décédé dans un accident", "Indemnisation des proches, accompagnement avec délicatesse.", "Décès d'un proche"),
    ],
    "serv_eyebrow": "Nos domaines", "serv_h2": "Faire reconnaître tous vos préjudices, pas seulement les plus visibles.",
    "servs": [
      ("Accidents de la route", "Indemnisation des piétons, cyclistes, passagers et conducteurs blessés, face aux assureurs."),
      ("Expertise médicale", "Préparation et assistance, avec un médecin-conseil de victimes à vos côtés."),
      ("Chiffrage des préjudices", "Souffrances, perte de revenus, aide humaine, aménagement du logement, préjudice esthétique."),
      ("Accidents médicaux", "Erreurs, infections nosocomiales, aléas thérapeutiques : recours amiables et judiciaires."),
      ("Victimes d'agression", "Plainte, procès pénal, commission d'indemnisation des victimes."),
      ("Proches des victimes", "Préjudice d'affection et économique des proches, en cas de décès ou de handicap."),
    ],
    "steps_h2": "Comment nous défendons votre dossier.",
    "steps": [
      ("Premier échange gratuit", "Au téléphone : vous racontez, nous vous disons si nous pouvons vous aider."),
      ("Constitution du dossier", "Pièces médicales, arrêts de travail, justificatifs, collectés avec vous."),
      ("Expertise médicale", "Préparation, puis assistance avec un médecin-conseil de victimes."),
      ("Négociation ou procès", "Offre contestée, négociée, ou soumise au tribunal si nécessaire."),
    ],
    "jobs_eyebrow": "Dossiers récents", "jobs_h2": "Quelques exemples, anonymisés.",
    "job_labels": ("Dossier", "Issue"),
    "jobs": [
      ("Cycliste de 34 ans", "Fracture du bassin, offre initiale contestée", "Accident de la route", "Offre fortement revalorisée"),
      ("Passagère de 19 ans", "Séquelles au genou, reconversion professionnelle", "Perte de revenus futurs", "Transaction amiable"),
      ("Patient de 58 ans", "Infection contractée après une opération", "Accident médical", "Indemnisation obtenue"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Uniquement les victimes.", "Nous ne défendons jamais d'assureurs : aucun conflit d'intérêts."),
      ("Des honoraires justes.", "Une part fixe raisonnable et un complément lié au résultat, fixés par écrit."),
      ("Du temps pour vous.", "Nous nous déplaçons à l'hôpital ou chez vous si vous ne pouvez pas venir."),
      ("La transparence.", "Vous savez à chaque étape où en est votre dossier."),
    ],
    "reviews": [
      ("« L'assurance me proposait une somme dérisoire. Maître Delmas a tout repris, et l'offre finale n'avait rien à voir. »", "Client · Toulouse · Accident de la route"),
      ("« Il est venu me voir au centre de rééducation. Je me suis sentie écoutée et défendue. »", "Cliente · Haute-Garonne · Dommage corporel"),
    ],
    "faq": [
      ("Faut-il accepter la première offre de l'assurance ?", "Pas sans la faire vérifier. Une fois acceptée, la transaction est en principe définitive. Un avocat de victimes vérifie que tous vos préjudices sont pris en compte et correctement chiffrés."),
      ("Quels droits pour une victime d'accident de la route ?", "La loi du 5 juillet 1985, dite loi Badinter, protège fortement les victimes, en particulier les piétons, cyclistes et passagers, qui sont indemnisés de leurs dommages corporels sauf cas très exceptionnels."),
      ("Pourquoi être assisté lors de l'expertise médicale ?", "Le rapport d'expertise sert de base au calcul de l'indemnisation. Être accompagné d'un avocat et d'un médecin-conseil de victimes permet que toutes vos séquelles soient correctement décrites."),
      ("Combien coûte un avocat de victimes ?", "Nos honoraires comprennent une part fixe et un honoraire complémentaire de résultat, tous deux fixés dans une convention écrite. Votre protection juridique peut aussi prendre en charge une partie des frais."),
      ("Quel est le délai pour agir ?", "Pour un dommage corporel, l'action se prescrit en principe par 10 ans à compter de la consolidation de votre état. Mieux vaut toutefois consulter tôt, avant l'expertise."),
      ("Pouvez-vous vous déplacer ?", "Oui, à l'hôpital, en centre de rééducation ou à domicile si vous ne pouvez pas vous déplacer."),
    ],
    "quote_h2": "Parlez-nous de votre situation.", "quote_p": "Quelques mots suffisent. Nous vous rappelons pour un premier échange gratuit, en toute confidentialité.",
    "work_label": "Votre situation",
    "works": ["Accident de la route", "Offre d'assurance à vérifier", "Expertise médicale", "Accident médical", "Agression", "Décès d'un proche", "Autre"],
    "extra": ("date", "Date de l'accident", "Ex. : mars 2026", True),
    "avail": ["Dès que possible", "Cette semaine", "En visio", "À l'hôpital ou à domicile"],
    "details_label": "Votre situation en quelques mots",
    "details_ph": "Ex. : renversé à vélo en mars, l'assurance vient de me faire une offre",
    "success": "Merci {first}. Nous vous rappelons {when} pour un premier échange gratuit et confidentiel.",
    "success_end": "",
    "nav": ["Nos domaines", "Comment ça se passe", "Dossiers", "Questions"],
  },
  {
    "dir": "avocats/04-leroy-defense",
    "seo_h1": "Avocate pénaliste à Paris, joignable 24 h/24 : garde à vue, comparution immédiate, permis",
    "founder": ("Me Claire Leroy", "avocate pénaliste au barreau de Paris"),
    "photo": ("6077124", "woman-in-black-robe-standing-beside-wooden-table-6077124", "Ekaterina Bolovtsova"),
    "name": "Leroy Défense", "tagline": "Avocate pénaliste · Paris",
    "schema": "LegalService",
    "city": "Paris", "cp": "75004", "street": "6 boulevard du Palais",
    "phone": "06 39 98 71 18", "tel": "+33639987118",
    "hours": "Urgences pénales 24 h/24, 7 j/7", "hours_schema": "Mo-Su 00:00-23:59",
    "zone_short": "Paris et Île-de-France",
    "zone": ["Paris", "Hauts-de-Seine", "Seine-Saint-Denis", "Val-de-Marne", "Tribunaux d'Île-de-France"],
    "zone_label": "J'interviens à",
    "top3": "Garde à vue : joignable jour et nuit",
    "form": "rdv",
    "urgent": True,
    "legal": SECRET,
    "title": "Avocat pénaliste Paris 24h/24 · Garde à vue, comparution immédiate, permis | Leroy Défense",
    "desc": "Me Claire Leroy, avocate pénaliste à Paris, joignable 24 h/24 : garde à vue, comparution immédiate, convocation au tribunal, retrait de permis, défense des victimes. Honoraires annoncés avant d'intervenir.",
    "fonts": ("Bodoni Moda", "Bodoni+Moda:opsz,wght@6..96,600;6..96,700", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F5F5F5", chalk="#E8E8E8", ink="#0D0D0D", muted="#5A5A5A", line="#D9D9D9", accent="#E55B5B", deep="#B02A2A"),
    "layout": "split-left",
    "icon": SCALE,
    "eyebrow": "Avocate pénaliste · Paris",
    "h1": ("Un proche en garde à vue ?", "Appelez maintenant : il a droit à un avocat dès la première heure."),
    "lead": "Garde à vue, comparution immédiate, convocation devant le tribunal, suspension de permis : chaque heure compte. Je suis joignable jour et nuit, je me déplace au commissariat, et j'annonce mes honoraires avant d'intervenir.",
    "proofs": ["Joignable 24 h/24, 7 j/7 pour les urgences", "Déplacement au commissariat ou à la gendarmerie", "Honoraires annoncés avant l'intervention"],
    "cta": "Demande non urgente", "note": "Pour une garde à vue en cours, appelez : c'est le plus rapide.",
    "badge": ("24 h/24", "pour les gardes à vue<br>et les urgences"),
    "alt": "Une avocate en robe noire dans une bibliothèque juridique",
    "sit_title": "Quelle est la situation ?",
    "sits": [
      ("Un proche vient d'être placé en garde à vue", "Désignez-moi auprès des enquêteurs, j'interviens au plus vite.", "Garde à vue"),
      ("Je suis convoqué(e) par la police", "Préparer l'audition avant d'y aller change tout.", "Convocation pour audition"),
      ("Je passe en comparution immédiate", "Préparation du dossier et défense à l'audience.", "Comparution immédiate"),
      ("J'ai reçu une convocation au tribunal", "Analyse du dossier et stratégie de défense.", "Convocation au tribunal"),
      ("On m'a suspendu ou retiré mon permis", "Contestation, défense devant le tribunal de police.", "Permis de conduire"),
      ("Je suis victime et je veux porter plainte", "Plainte, constitution de partie civile, indemnisation.", "Victime"),
    ],
    "serv_eyebrow": "Mes interventions", "serv_h2": "La défense pénale, de la garde à vue au procès.",
    "servs": [
      ("Garde à vue", "Entretien confidentiel avec la personne gardée à vue, assistance lors des auditions."),
      ("Audition libre", "Préparation et présence à vos côtés lors d'une audition sans garde à vue."),
      ("Comparution immédiate", "Préparation en urgence, demande de renvoi si nécessaire, défense à l'audience."),
      ("Procès correctionnel", "Étude du dossier pénal, stratégie, plaidoirie devant le tribunal."),
      ("Droit routier", "Suspension et annulation de permis, alcool ou stupéfiants au volant, excès de vitesse."),
      ("Défense des victimes", "Plainte, constitution de partie civile, demande d'indemnisation."),
    ],
    "steps_h2": "En cas de garde à vue, ce qui se passe.",
    "steps": [
      ("Vous m'appelez", "Donnez-moi le nom de la personne et le lieu de la garde à vue."),
      ("Désignation", "La personne gardée à vue, ou un proche, me désigne auprès des enquêteurs."),
      ("Entretien confidentiel", "Je m'entretiens avec elle et prépare les auditions."),
      ("Assistance et suite", "Présence aux auditions, puis défense si des poursuites suivent."),
    ],
    "jobs_eyebrow": "Dossiers récents", "jobs_h2": "Quelques exemples, anonymisés.",
    "job_labels": ("Procédure", "Issue"),
    "jobs": [
      ("Jeune homme de 22 ans", "Garde à vue de nuit, assistance dès la première audition", "Garde à vue", "Classement sans suite"),
      ("Chef d'entreprise", "Suspension de permis contestée pour vice de procédure", "Droit routier", "Permis restitué"),
      ("Homme de 35 ans", "Comparution immédiate, renvoi obtenu pour préparer la défense", "Comparution immédiate", "Peine aménagée"),
    ],
    "pledges_h2": "Mes engagements.",
    "pledges": [
      ("Être joignable.", "Jour et nuit pour les urgences pénales."),
      ("Des honoraires annoncés.", "Montant indiqué avant l'intervention, convention d'honoraires écrite."),
      ("Le secret absolu.", "Tout ce que vous me dites reste entre nous."),
      ("La franchise.", "Je vous dis ce que risque la personne et ce que je peux obtenir, sans promesse intenable."),
    ],
    "reviews": [
      ("« Mon fils a été placé en garde à vue à 2 h du matin. Maître Leroy a répondu tout de suite et était au commissariat avant sa première audition. »", "Mère d'un client · Paris · Garde à vue"),
      ("« Honoraires annoncés dès le premier appel, et une défense très bien préparée. »", "Client · Hauts-de-Seine · Droit routier"),
    ],
    "faq": [
      ("Quels sont les droits en garde à vue ?", "Toute personne gardée à vue peut être assistée par un avocat dès le début, s'entretenir avec lui de façon confidentielle pendant 30 minutes, faire prévenir un proche, être examinée par un médecin et garder le silence."),
      ("Combien de temps dure une garde à vue ?", "En principe 24 heures, renouvelables une fois pour 24 heures supplémentaires sur décision du procureur. Des durées plus longues existent pour certaines infractions graves."),
      ("Comment désigner un avocat pour un proche en garde à vue ?", "La personne gardée à vue peut demander un avocat nommément. Un proche peut aussi désigner un avocat, la désignation devant ensuite être confirmée par la personne gardée à vue."),
      ("Qu'est-ce qu'une comparution immédiate ?", "Une procédure rapide où la personne est jugée juste après sa garde à vue. Elle peut demander un délai pour préparer sa défense, ce qui est souvent conseillé."),
      ("Combien coûte un avocat pénaliste ?", "Les honoraires dépendent de la procédure (garde à vue, audience, procès). Je les annonce avant d'intervenir et les fixe dans une convention écrite. L'aide juridictionnelle est possible selon vos ressources."),
      ("Faut-il un avocat pour une audition libre ?", "Ce n'est pas obligatoire, mais vous avez le droit d'être assisté. Préparer l'audition avec un avocat évite bien des erreurs."),
    ],
    "quote_h2": "Une demande non urgente ?", "quote_p": "Pour une garde à vue en cours, appelez le 06 39 98 71 18. Pour une convocation ou une question, laissez-moi un message.",
    "work_label": "Situation",
    "works": ["Garde à vue", "Convocation pour audition", "Comparution immédiate", "Convocation au tribunal", "Permis de conduire", "Victime", "Autre"],
    "extra": ("court", "Date d'audience ou de convocation", "Ex. : 12 novembre, tribunal de Paris", True),
    "avail": ["Dès que possible", "Aujourd'hui", "Cette semaine", "En visio"],
    "details_label": "La situation en quelques mots",
    "details_ph": "Ex. : convoqué au commissariat la semaine prochaine pour une audition libre",
    "success": "Merci {first}. Je vous rappelle {when} pour faire le point, en toute confidentialité.",
    "success_end": "",
    "nav": ["Mes interventions", "Garde à vue", "Dossiers", "Questions"],
  },
]
