"""Dentistes : 5 cabinets refaits au format orienté patient (septembre 2026)."""

TOOTH = '<path class="blade" d="M9 5c-3 0-5 2.5-5 6 0 4 2 6 3 10l1.5 6c.4 1.4 2.4 1.4 2.8 0L13 20c.5-1.6 2.5-1.6 3 0l1.7 7c.4 1.4 2.4 1.4 2.8 0L22 21c1-4 3-6 3-10 0-3.5-2-6-5-6-2 0-3 1-4.5 1S11 5 9 5z"/>'

NAV = ["Nos soins", "Votre rendez-vous", "Parcours", "Questions"]
LEGAL = "Vos informations servent uniquement à organiser votre rendez-vous. Ne transmettez pas de données médicales détaillées par ce formulaire."

SITES = [
  {
    "dir": "dentistes/01-eclat-dental",
    "seo_h1": "Dentiste esthétique à Paris 16e : facettes, blanchiment, sourire",
    "founder": ("Dr Claire Aubert", "chirurgien-dentiste, esthétique du sourire"),
    "photo": ("6627575", "a-dentist-holding-a-dental-shade-guide-in-front-of-a-patient-6627575", "Karola G"),
    "name": "Éclat, cabinet dentaire", "tagline": "Esthétique du sourire · Paris 16e",
    "schema": "Dentist",
    "city": "Paris", "cp": "75016", "street": "5 avenue Victor-Hugo",
    "phone": "01 99 00 26 81", "tel": "+33199002681",
    "hours": "Du lundi au vendredi, 9 h à 19 h, samedi matin", "hours_schema": "Mo-Fr 09:00-19:00",
    "zone_short": "Paris 16e, métro Charles-de-Gaulle-Étoile",
    "zone": ["Paris 16e", "Paris 8e", "Paris 17e", "Neuilly-sur-Seine", "Boulogne-Billancourt"],
    "zone_label": "Patients venant de",
    "top3": "Consultation esthétique avec simulation",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Dentiste esthétique Paris 16e · Facettes, blanchiment, couronnes céramique | Éclat",
    "desc": "Éclat, cabinet dentaire esthétique à Paris 16e : facettes en céramique, blanchiment, couronnes, alignement par gouttières. Consultation avec simulation de votre futur sourire et devis détaillé.",
    "fonts": ("Playfair Display", "Playfair+Display:ital,wght@0,600;0,700;1,600", "Lato", "Lato:wght@400;700"),
    "pal": dict(paper="#FBF8F3", chalk="#F2EBE1", ink="#0F3A36", muted="#58706C", line="#E3DACD", accent="#D9A690", deep="#9A5A43"),
    "layout": "split-right",
    "icon": TOOTH,
    "eyebrow": "Esthétique du sourire · Paris 16e",
    "h1": ("Voir votre futur sourire", "avant de décider quoi que ce soit."),
    "lead": "Teinte, forme, alignement : lors de la consultation esthétique, nous simulons le résultat sur une photo de votre visage. Vous repartez avec un plan de traitement et un devis détaillé, sans engagement.",
    "proofs": ["Simulation du résultat dès la consultation", "Devis détaillé et plan de traitement écrits", "Des soins naturels, pas un sourire standard"],
    "cta": "Prendre rendez-vous", "note": "Premier rendez-vous sous deux semaines en moyenne.",
    "badge": ("1 h", "de consultation esthétique<br>avec simulation"),
    "alt": "Une dentiste compare la teinte des dents d'une patiente avec un teintier",
    "sit_title": "Qu'aimeriez-vous changer ?",
    "sits": [
      ("Mes dents sont jaunies ou ternes", "Blanchiment encadré au cabinet ou à domicile, après bilan.", "Blanchiment"),
      ("Une dent est cassée, tachée ou abîmée", "Facette ou couronne en céramique, teinte assortie aux autres dents.", "Facettes ou couronne"),
      ("J'ai des espaces entre les dents", "Composite, facettes ou gouttières selon le cas.", "Espaces entre les dents"),
      ("Mes dents sont légèrement de travers", "Alignement par gouttières transparentes, quasi invisibles.", "Alignement par gouttières"),
      ("Je n'ose plus sourire sur les photos", "Consultation globale avec simulation de votre sourire.", "Bilan esthétique"),
      ("J'ai simplement besoin d'un contrôle", "Contrôle et détartrage, avec la même attention au détail.", "Contrôle et détartrage"),
    ],
    "serv_eyebrow": "Nos soins", "serv_h2": "Un sourire plus beau, qui reste le vôtre.",
    "servs": [
      ("Facettes en céramique", "Fines pellicules collées sur la face visible des dents, pour corriger forme, teinte ou petits défauts."),
      ("Blanchiment", "Au fauteuil ou à domicile avec gouttières sur mesure, après vérification de la santé des dents."),
      ("Couronnes céramique", "Pour une dent très abîmée, une couronne sans métal qui s'accorde aux dents voisines."),
      ("Alignement par gouttières", "Gouttières transparentes pour corriger les petits décalages, à l'âge adulte."),
      ("Collages composites", "Réparation d'une dent ébréchée ou fermeture d'un petit espace en une séance."),
      ("Soins courants", "Contrôle, détartrage, caries : le suivi de base, indispensable à tout le reste."),
    ],
    "steps_h2": "Du premier rendez-vous au résultat.",
    "steps": [
      ("Consultation esthétique", "Examen, photos, écoute de ce que vous souhaitez."),
      ("Simulation", "Votre futur sourire simulé sur votre photo, ajusté avec vous."),
      ("Plan et devis", "Étapes, durée et devis détaillé remis par écrit."),
      ("Traitement", "Séances planifiées, résultat contrôlé ensemble."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Quelques exemples de traitements.",
    "job_labels": ("Traitement", "Durée"),
    "jobs": [
      ("Patiente de 34 ans", "Deux incisives ébréchées et teintées", "Deux facettes céramique", "3 semaines"),
      ("Patient de 52 ans", "Dents jaunies par le café", "Blanchiment à domicile", "2 semaines"),
      ("Patiente de 28 ans", "Légers chevauchements des dents du bas", "Gouttières transparentes", "7 mois"),
    ],
    "pledges_h2": "Notre façon de soigner.",
    "pledges": [
      ("Un résultat naturel.", "On cherche le sourire qui vous va, pas une rangée de dents trop blanches."),
      ("Préserver vos dents.", "La solution la moins invasive est toujours proposée en premier."),
      ("Des devis clairs.", "Chaque acte chiffré, avec ce qui est remboursé et ce qui ne l'est pas."),
      ("Du temps pour vous.", "Des consultations longues, sans vous presser."),
    ],
    "reviews": [
      ("« J'ai vu le résultat avant de commencer. Deux facettes plus tard, personne ne devine qu'elles ne sont pas naturelles. »", "Laure M. · Paris 16e · Facettes"),
      ("« Aucune pression commerciale : on m'a même déconseillé un soin inutile. Rare et précieux. »", "Antoine D. · Neuilly-sur-Seine · Bilan esthétique"),
    ],
    "faq": [
      ("Les facettes abîment-elles les dents ?", "Les facettes modernes demandent une préparation très fine, parfois aucune. Nous privilégions toujours la solution la plus conservatrice et vous l'expliquons avant."),
      ("Le blanchiment est-il remboursé ?", "Non, le blanchiment est un soin esthétique non pris en charge par l'Assurance maladie. Certaines mutuelles participent : le devis vous permet de le vérifier."),
      ("Combien de temps durent des facettes en céramique ?", "Bien entretenues, elles durent de nombreuses années. Un contrôle régulier permet de les surveiller."),
      ("Le blanchiment est-il sans danger ?", "Réalisé par un dentiste après un bilan, avec des produits dosés, il est sûr. Il ne convient pas en cas de caries non soignées ou de gencives fragiles."),
      ("Faites-vous aussi les soins courants ?", "Oui : contrôles, détartrages et caries font partie de notre suivi quotidien."),
      ("Comment prendre rendez-vous ?", "Par téléphone ou via le formulaire. Nous vous rappelons pour proposer un créneau de consultation."),
    ],
    "quote_h2": "Prenez rendez-vous.", "quote_p": "Dites-nous ce qui vous amène. Nous vous rappelons pour vous proposer un créneau de consultation.",
    "work_label": "Motif de consultation",
    "works": ["Bilan esthétique", "Blanchiment", "Facettes ou couronne", "Espaces entre les dents", "Alignement par gouttières", "Contrôle et détartrage", "Autre"],
    "extra": ("patient", "Déjà patient du cabinet ?", "Ex. : non, première visite", True),
    "details_label": "Ce que vous aimeriez",
    "details_ph": "Ex. : j'aimerais des dents plus claires et corriger une incisive ébréchée",
    "success": "Merci {first}. Nous vous rappelons {when} pour vous proposer un créneau de consultation.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "dentistes/02-arcline-dental",
    "seo_h1": "Implants dentaires et dentiste à Lyon 6e",
    "founder": ("Dr Mathieu Perrin", "chirurgien-dentiste, implantologie"),
    "photo": ("7800669", "patient-and-the-dentists-7800669", "Nadezhda Moryak"),
    "name": "Cabinet dentaire Arcline", "tagline": "Implantologie et soins · Lyon 6e",
    "schema": "Dentist",
    "city": "Lyon", "cp": "69006", "street": "72 cours Vitton",
    "phone": "04 65 71 18 57", "tel": "+33465711857",
    "hours": "Du lundi au vendredi, 8 h 30 à 19 h", "hours_schema": "Mo-Fr 08:30-19:00",
    "zone_short": "Lyon 6e, métro Masséna",
    "zone": ["Lyon 6e", "Lyon 3e", "Villeurbanne", "Caluire-et-Cuire", "Lyon 4e"],
    "zone_label": "Patients venant de",
    "top3": "Empreintes numériques, sans pâte",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Implant dentaire à Lyon 6e · Dentiste, prothèses, empreinte numérique | Arcline",
    "desc": "Cabinet dentaire Arcline à Lyon 6e : implants dentaires, couronnes, bridges et soins, avec radio 3D et empreintes numériques. Plan de traitement expliqué sur écran et devis détaillé remis par écrit.",
    "fonts": ("Instrument Sans", "Instrument+Sans:wght@500;600;700", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F6F8FC", chalk="#E7EDF7", ink="#0B1526", muted="#56627A", line="#D5DDEA", accent="#5B8CFF", deep="#1848C8"),
    "layout": "overlay",
    "icon": TOOTH,
    "eyebrow": "Implants et soins · Lyon 6e",
    "h1": ("Remplacer une dent manquante,", "en comprenant chaque étape et chaque euro."),
    "lead": "Radio 3D, empreinte numérique sans pâte, plan de traitement expliqué sur écran : vous savez ce qui va être fait, combien de temps cela prendra et ce que vous rembourseront la Sécurité sociale et votre mutuelle.",
    "proofs": ["Radio 3D et empreintes numériques au cabinet", "Devis détaillé avec la part remboursée", "Offres « 100 % Santé » proposées quand elles existent"],
    "cta": "Prendre rendez-vous", "note": "Première consultation implantaire sous trois semaines.",
    "badge": ("3D", "radio et empreintes<br>numériques au cabinet"),
    "alt": "Deux dentistes expliquent une radio dentaire à un patient sur écran",
    "sit_title": "Quelle est votre situation ?",
    "sits": [
      ("Il me manque une ou plusieurs dents", "Implant, bridge ou prothèse : on compare les solutions ensemble.", "Dent manquante"),
      ("Mon dentier bouge et me gêne", "Stabilisation sur implants pour manger et parler sereinement.", "Prothèse instable"),
      ("On m'a annoncé une dent à arracher", "Extraction et solution de remplacement prévues dès le départ.", "Extraction à prévoir"),
      ("Une couronne s'est décollée ou cassée", "Nouvelle couronne réalisée à partir d'une empreinte numérique.", "Couronne"),
      ("Je veux un deuxième avis sur un devis", "Relecture de votre devis et plan de traitement.", "Deuxième avis"),
      ("J'ai besoin d'un contrôle", "Contrôle, radio si nécessaire, détartrage.", "Contrôle"),
    ],
    "serv_eyebrow": "Nos soins", "serv_h2": "Des traitements précis, expliqués avant d'être faits.",
    "servs": [
      ("Implants dentaires", "Une racine en titane posée dans l'os, surmontée d'une couronne : la solution la plus proche d'une dent naturelle."),
      ("Couronnes et bridges", "Réalisés à partir d'empreintes numériques, avec des options « 100 % Santé » lorsqu'elles existent."),
      ("Prothèses sur implants", "Stabiliser un dentier avec deux à quatre implants pour retrouver confort et assurance."),
      ("Extractions", "Extractions simples et dents de sagesse, avec anticipation du remplacement."),
      ("Radio 3D", "Examen de l'os en trois dimensions pour planifier l'implant au millimètre."),
      ("Soins courants", "Contrôles, détartrages, caries, dévitalisations."),
    ],
    "steps_h2": "Votre parcours implantaire, étape par étape.",
    "steps": [
      ("Consultation et radio 3D", "Examen, radio, discussion de vos attentes."),
      ("Plan expliqué sur écran", "Solutions comparées, durée, devis détaillé avec la part remboursée."),
      ("Pose de l'implant", "Sous anesthésie locale, en une séance le plus souvent."),
      ("Couronne définitive", "Après cicatrisation de quelques mois, pose de la dent finale."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Quelques exemples de traitements.",
    "job_labels": ("Traitement", "Durée totale"),
    "jobs": [
      ("Patient de 48 ans", "Molaire perdue, remplacée par un implant", "Implant et couronne", "4 mois"),
      ("Patiente de 71 ans", "Dentier du bas stabilisé sur deux implants", "Prothèse sur implants", "3 mois"),
      ("Patient de 39 ans", "Couronne cassée refaite sans pâte d'empreinte", "Couronne céramique", "2 semaines"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Tout comprendre avant de signer.", "Plan affiché à l'écran, questions bienvenues, délai de réflexion respecté."),
      ("Des devis lisibles.", "Chaque acte, sa part remboursée par la Sécurité sociale et la mutuelle estimée."),
      ("Toutes les options.", "Implant, bridge ou prothèse : on présente aussi les solutions les moins chères."),
      ("Un suivi dans la durée.", "Contrôle annuel des implants inclus dans votre suivi."),
    ],
    "reviews": [
      ("« Pour la première fois, j'ai compris mon devis. Le docteur a comparé implant et bridge avec moi, sans pousser. »", "Sylvie P. · Lyon 3e · Implant"),
      ("« Mon dentier ne bouge plus. Je remange des pommes, après dix ans. »", "Georges B. · Villeurbanne · Prothèse sur implants"),
    ],
    "faq": [
      ("Combien coûte un implant dentaire ?", "Le prix dépend du nombre d'implants, de l'état de l'os et de la couronne choisie. Vous recevez un devis détaillé après la consultation et la radio 3D."),
      ("Un implant est-il remboursé ?", "La pose de l'implant n'est généralement pas remboursée par l'Assurance maladie, mais la couronne posée dessus l'est en partie. De nombreuses mutuelles participent : le devis vous permet de le vérifier."),
      ("La pose d'un implant fait-elle mal ?", "Elle se fait sous anesthésie locale et n'est pas douloureuse. Les suites sont en général comparables à celles d'une extraction."),
      ("Combien de temps dure un traitement implantaire ?", "Comptez généralement trois à six mois entre la pose et la couronne définitive, le temps que l'os cicatrise autour de l'implant."),
      ("Qu'est-ce que le « 100 % Santé » ?", "Une offre de couronnes, bridges et prothèses sans reste à charge pour les patients ayant une complémentaire santé responsable. Nous vous la proposons quand elle est adaptée."),
      ("Puis-je venir pour un deuxième avis ?", "Oui, apportez votre devis et vos radios : nous vous donnons un avis argumenté."),
    ],
    "quote_h2": "Prenez rendez-vous.", "quote_p": "Dites-nous ce qui vous amène. Nous vous rappelons pour vous proposer un créneau.",
    "work_label": "Motif de consultation",
    "works": ["Dent manquante", "Prothèse instable", "Extraction à prévoir", "Couronne", "Deuxième avis", "Contrôle", "Autre"],
    "extra": ("patient", "Déjà patient du cabinet ?", "Ex. : non, première visite", True),
    "details_label": "Votre situation en quelques mots",
    "details_ph": "Ex. : molaire du bas arrachée il y a un an, je voudrais un implant",
    "success": "Merci {first}. Nous vous rappelons {when} pour vous proposer un créneau de consultation.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "dentistes/03-hollyfield-dental",
    "seo_h1": "Dentiste pour toute la famille à Angers depuis 1961",
    "founder": ("Dr Anne-Laure Chauvin", "chirurgien-dentiste, soins des enfants"),
    "photo": ("6627330", "dentist-holding-a-dental-model-6627330", "Karola G"),
    "name": "Cabinet dentaire du Parc", "tagline": "Dentistes de famille depuis 1961 · Angers",
    "schema": "Dentist",
    "city": "Angers", "cp": "49100", "street": "14 boulevard Foch",
    "phone": "02 61 91 26 38", "tel": "+33261912638",
    "hours": "Du lundi au vendredi, 8 h 30 à 18 h 30, mercredi pour les enfants", "hours_schema": "Mo-Fr 08:30-18:30",
    "zone_short": "Angers centre, jardin du Mail",
    "zone": ["Angers", "Avrillé", "Trélazé", "Les Ponts-de-Cé", "Saint-Barthélemy-d'Anjou", "Beaucouzé"],
    "zone_label": "Patients venant de",
    "top3": "Nouveaux patients acceptés",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Dentiste à Angers pour enfants et adultes · Nouveaux patients acceptés | Cabinet dentaire du Parc",
    "desc": "Cabinet dentaire du Parc à Angers, depuis 1961 : soins pour toute la famille, dentisterie pédiatrique le mercredi, contrôles, prothèses 100 % Santé. Nouveaux patients acceptés, tiers payant.",
    "fonts": ("Libre Baskerville", "Libre+Baskerville:wght@700", "Source Sans 3", "Source+Sans+3:wght@400;500;600"),
    "pal": dict(paper="#FAF7EF", chalk="#EEE8D8", ink="#1E3B2C", muted="#5B6B60", line="#E0D8C4", accent="#D1AE5E", deep="#85651C"),
    "layout": "split-left",
    "icon": TOOTH,
    "eyebrow": "Dentistes de famille · Angers",
    "h1": ("Un dentiste qui accepte encore de nouveaux patients,", "et qui soigne les enfants comme les grands-parents."),
    "lead": "Trouver un dentiste à Angers peut prendre des mois. Notre cabinet accueille de nouveaux patients, réserve le mercredi aux enfants et pratique le tiers payant. Trois générations de familles angevines nous font confiance.",
    "proofs": ["Nouveaux patients acceptés", "Mercredi réservé aux enfants", "Tiers payant et offres 100 % Santé"],
    "cta": "Prendre rendez-vous", "note": "Pour une urgence (douleur, dent cassée), appelez le matin : des créneaux sont gardés chaque jour.",
    "badge": ("1961", "trois générations<br>de familles soignées"),
    "alt": "Une dentiste montre le brossage des dents à un adolescent avec un modèle",
    "sit_title": "Pour qui prenez-vous rendez-vous ?",
    "sits": [
      ("Je cherche un dentiste, je viens d'arriver à Angers", "Premier bilan complet et plan de soins si besoin.", "Nouveau patient"),
      ("Pour mon enfant", "Consultation le mercredi, à son rythme, avec explications.", "Enfant"),
      ("J'ai mal aux dents", "Créneaux d'urgence gardés chaque matin.", "Douleur, urgence"),
      ("Pour un contrôle et un détartrage", "Une fois par an, c'est l'essentiel.", "Contrôle et détartrage"),
      ("Pour une couronne ou un appareil", "Solutions 100 % Santé proposées quand elles existent.", "Prothèse"),
      ("Pour mon parent âgé", "Soins adaptés, rendez-vous à l'heure calme.", "Personne âgée"),
    ],
    "serv_eyebrow": "Nos soins", "serv_h2": "Les soins dentaires de toute la famille, au même endroit.",
    "servs": [
      ("Soins des enfants", "Premières visites, prévention des caries, scellement des sillons, examens M'T dents."),
      ("Contrôles et détartrages", "Un bilan annuel pour éviter les soins lourds."),
      ("Caries et dévitalisations", "Soins conservateurs pour garder vos dents le plus longtemps possible."),
      ("Couronnes et prothèses", "Avec des options « 100 % Santé » sans reste à charge quand elles sont adaptées."),
      ("Urgences", "Douleur, dent cassée, abcès : des créneaux gardés chaque matin."),
      ("Seniors", "Adaptation des prothèses, soins des gencives, rendez-vous sans attente."),
    ],
    "steps_h2": "Votre premier rendez-vous.",
    "steps": [
      ("Vous nous contactez", "Téléphone ou formulaire : dites-nous qui vient et pourquoi."),
      ("On vous rappelle", "Créneau proposé, documents à apporter indiqués."),
      ("Premier bilan", "Examen, radio si nécessaire, explications."),
      ("Plan de soins", "Si des soins sont nécessaires, on les planifie avec vous."),
    ],
    "jobs_eyebrow": "Au quotidien", "jobs_h2": "Des patients de tous les âges.",
    "job_labels": ("Soins", "Rendez-vous"),
    "jobs": [
      ("Léa, 6 ans", "Première visite, apprentissage du brossage, dents saines", "Examen M'T dents", "30 min"),
      ("Famille Morin", "Parents et deux enfants suivis le même mercredi", "Contrôles", "1 h"),
      ("Monique, 78 ans", "Prothèse ajustée pour manger sans douleur", "Adaptation de prothèse", "2 séances"),
    ],
    "pledges_h2": "Ce que nous vous promettons.",
    "pledges": [
      ("De la patience avec les enfants.", "On explique, on montre, on ne force jamais."),
      ("Pas d'avance de frais inutile.", "Tiers payant sur la part obligatoire et selon votre mutuelle."),
      ("Des urgences prises.", "Des créneaux gardés chaque matin pour les douleurs."),
      ("Des soins durables.", "Conserver vos dents avant de les remplacer."),
    ],
    "reviews": [
      ("« Enfin un dentiste qui prend de nouveaux patients à Angers. Mes deux enfants adorent le mercredi au cabinet. »", "Émilie R. · Avrillé · Famille"),
      ("« Mal aux dents un lundi, vue le matin même. Explications claires et tarifs annoncés. »", "Hervé C. · Angers · Urgence"),
    ],
    "faq": [
      ("Acceptez-vous de nouveaux patients ?", "Oui, adultes et enfants. Nous vous proposons un premier rendez-vous de bilan."),
      ("À partir de quel âge amener son enfant chez le dentiste ?", "Une première visite est conseillée dès les premières dents, et l'Assurance maladie propose des examens de prévention gratuits aux âges clés (programme M'T dents)."),
      ("Pratiquez-vous le tiers payant ?", "Oui, sur la part de l'Assurance maladie, et sur la part complémentaire avec la plupart des mutuelles."),
      ("Que faire en cas d'urgence dentaire ?", "Appelez le cabinet dès l'ouverture : des créneaux sont gardés chaque matin. Le week-end et les jours fériés, contactez le service de garde dentaire de votre département ou le 15."),
      ("Qu'est-ce que l'offre 100 % Santé ?", "Certaines couronnes, bridges et prothèses sans reste à charge si vous avez une complémentaire santé responsable. Nous vous la proposons quand elle convient."),
      ("Que faut-il apporter au premier rendez-vous ?", "Votre carte Vitale, votre attestation de mutuelle et, si vous en avez, vos anciennes radios."),
    ],
    "quote_h2": "Prenez rendez-vous.", "quote_p": "Indiquez qui vient et pourquoi. Nous vous rappelons pour proposer un créneau.",
    "work_label": "Motif du rendez-vous",
    "works": ["Nouveau patient", "Enfant", "Douleur, urgence", "Contrôle et détartrage", "Prothèse", "Personne âgée", "Autre"],
    "extra": ("who", "Pour qui ?", "Ex. : moi et mes deux enfants", True),
    "details_label": "Précisions",
    "details_ph": "Ex. : premier rendez-vous pour ma fille de 5 ans",
    "success": "Merci {first}. Nous vous rappelons {when} pour vous proposer un créneau.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "dentistes/04-still-point-dental",
    "seo_h1": "Dentiste pour patients anxieux à Bordeaux : soins sans stress",
    "founder": ("Dr Julien Lacoste", "chirurgien-dentiste, formé à la sédation consciente"),
    "photo": ("4971499", "young-woman-sitting-in-dentist-chair-4971499", "Gustavo Fring"),
    "name": "Cabinet dentaire Sérénade", "tagline": "Soins dentaires sans stress · Bordeaux",
    "schema": "Dentist",
    "city": "Bordeaux", "cp": "33000", "street": "40 rue Judaïque",
    "phone": "05 36 49 61 22", "tel": "+33536496122",
    "hours": "Du lundi au vendredi, 9 h à 19 h", "hours_schema": "Mo-Fr 09:00-19:00",
    "zone_short": "Bordeaux centre, tram Gambetta",
    "zone": ["Bordeaux", "Le Bouscat", "Mérignac", "Talence", "Bruges", "Caudéran"],
    "zone_label": "Patients venant de",
    "top3": "Sédation au gaz MEOPA possible",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Dentiste pour patients anxieux à Bordeaux · Soins sans stress, MEOPA | Sérénade",
    "desc": "Cabinet dentaire Sérénade à Bordeaux, pensé pour les patients qui ont peur du dentiste : premier rendez-vous sans soin, anesthésie douce, sédation au MEOPA, signal pour arrêter à tout moment.",
    "fonts": ("Lora", "Lora:ital,wght@0,600;0,700;1,600", "Karla", "Karla:wght@400;500;600"),
    "pal": dict(paper="#F5F9F8", chalk="#E4EFEE", ink="#1B2E2E", muted="#566866", line="#D2E2E0", accent="#8CC3BE", deep="#3A7C76"),
    "layout": "overlay",
    "icon": TOOTH,
    "eyebrow": "Soins dentaires sans stress · Bordeaux",
    "h1": ("Vous repoussez le dentiste depuis des années ?", "Le premier rendez-vous, c'est juste une conversation."),
    "lead": "Pas de fauteuil qui bascule d'emblée, pas de reproches. On parle de votre peur, de ce qui vous gêne, et rien n'est fait sans votre accord. Anesthésie douce, gaz relaxant (MEOPA) si besoin, et un signal pour tout arrêter à tout moment.",
    "proofs": ["Premier rendez-vous d'échange, sans aucun soin", "Anesthésie douce et gaz relaxant MEOPA si besoin", "Un geste de la main et on arrête, toujours"],
    "cta": "Prendre un premier rendez-vous", "note": "Vous pouvez venir accompagné(e).",
    "badge": ("0 soin", "au premier rendez-vous<br>si vous le souhaitez"),
    "alt": "Une jeune femme détendue et souriante dans un fauteuil dentaire",
    "sit_title": "Vous vous reconnaissez ?",
    "sits": [
      ("Je n'ai pas vu de dentiste depuis des années", "Aucun jugement. On fait le point calmement et on priorise.", "Reprise après plusieurs années"),
      ("J'ai eu une mauvaise expérience", "On en parle d'abord, et on adapte chaque geste.", "Mauvaise expérience passée"),
      ("J'ai peur des piqûres", "Gel anesthésiant avant, anesthésie lente et presque indolore.", "Peur des piqûres"),
      ("J'ai mal mais je repousse", "Soulager la douleur d'abord, en douceur.", "Douleur"),
      ("J'ai honte de l'état de mes dents", "Nous avons tout vu. On vous aide, sans commentaire.", "Honte de mes dents"),
      ("Mon enfant a très peur", "Séances courtes, explications, découverte du cabinet.", "Enfant anxieux"),
    ],
    "serv_eyebrow": "Notre approche", "serv_h2": "Des soins complets, au rythme que vous choisissez.",
    "servs": [
      ("Rendez-vous d'échange", "Premier rendez-vous sans soin : on fait connaissance et on parle de vos craintes."),
      ("Anesthésie douce", "Gel anesthésiant puis injection lente, souvent imperceptible."),
      ("Sédation au MEOPA", "Un gaz relaxant respiré au masque, qui détend sans endormir. Effet dissipé en quelques minutes."),
      ("Séances courtes", "Des soins découpés en rendez-vous plus courts si cela vous rassure."),
      ("Soins complets", "Caries, détartrage, dévitalisation, couronnes : tout est possible, pas à pas."),
      ("Enfants anxieux", "Découverte du cabinet, jeux, explications adaptées à leur âge."),
    ],
    "steps_h2": "Comment se passe votre retour chez le dentiste.",
    "steps": [
      ("Un appel ou un message", "Dites-nous simplement que vous avez peur. On le note."),
      ("Rendez-vous d'échange", "Assis face à face, on parle. Examen seulement si vous êtes d'accord."),
      ("Plan à votre rythme", "Les soins priorisés, avec les options de confort."),
      ("Soins accompagnés", "Signal d'arrêt convenu, pauses quand vous voulez."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Ils ont repris le chemin du dentiste.",
    "job_labels": ("Soins", "Rythme"),
    "jobs": [
      ("Patient de 41 ans", "Douze ans sans dentiste, cinq caries soignées", "Soins sous MEOPA", "6 séances courtes"),
      ("Patiente de 29 ans", "Phobie des piqûres après une mauvaise expérience", "Anesthésie douce", "3 séances"),
      ("Enfant de 7 ans", "Premier soin de carie après deux visites de découverte", "Soin pédiatrique", "3 rendez-vous"),
    ],
    "pledges_h2": "Nos promesses.",
    "pledges": [
      ("Aucun jugement.", "Quel que soit l'état de vos dents, on vous accueille sans commentaire."),
      ("Rien sans votre accord.", "Chaque geste est expliqué avant d'être fait."),
      ("Vous gardez la main.", "Un signal et on s'arrête, à tout moment."),
      ("Des devis clairs.", "Ce qui est remboursé et ce qui ne l'est pas, avant de commencer."),
    ],
    "reviews": [
      ("« Douze ans sans dentiste par peur. Le premier rendez-vous était juste une discussion, et j'ai fini tous mes soins. »", "Nicolas F. · Bordeaux · Reprise des soins"),
      ("« Avec le gaz relaxant, je n'ai plus paniqué une seule fois. L'équipe est d'une douceur incroyable. »", "Pauline G. · Le Bouscat · Soins sous MEOPA"),
    ],
    "faq": [
      ("Qu'est-ce que le MEOPA ?", "Un mélange d'oxygène et de protoxyde d'azote respiré au masque. Il détend et diminue l'anxiété sans endormir. Ses effets disparaissent quelques minutes après l'arrêt."),
      ("Le premier rendez-vous est-il vraiment sans soin ?", "Oui si vous le souhaitez. C'est un temps d'échange et, si vous êtes d'accord, un simple examen."),
      ("Est-ce que ça va faire mal ?", "Nous utilisons un gel anesthésiant avant l'injection, faite lentement. La plupart des patients ne la sentent presque pas."),
      ("J'ai honte de l'état de mes dents, que faire ?", "Venez tel que vous êtes. Nous voyons chaque jour des patients qui reviennent après des années. Notre rôle est de vous aider, pas de juger."),
      ("Les soins sont-ils remboursés ?", "Les soins courants sont pris en charge comme dans tout cabinet conventionné. Certaines options de confort peuvent avoir un coût : il est indiqué avant."),
      ("Puis-je venir accompagné(e) ?", "Oui, une personne de confiance peut vous accompagner en salle de soin."),
    ],
    "quote_h2": "Faisons connaissance.", "quote_p": "Dites-nous simplement ce que vous ressentez. Nous vous rappelons avec douceur pour fixer un premier rendez-vous d'échange.",
    "work_label": "Ce qui vous amène",
    "works": ["Reprise après plusieurs années", "Mauvaise expérience passée", "Peur des piqûres", "Douleur", "Honte de mes dents", "Enfant anxieux", "Autre"],
    "extra": ("comfort", "Ce qui vous rassurerait", "Ex. : venir accompagné, séances courtes", True),
    "details_label": "Ce que vous voulez nous dire",
    "details_ph": "Ex. : je n'ai pas vu de dentiste depuis 10 ans, j'ai très peur de la roulette",
    "success": "Merci {first}. Nous vous rappelons {when}, en douceur, pour fixer un premier rendez-vous d'échange.",
    "success_end": "",
    "nav": ["Notre approche", "Votre rendez-vous", "Parcours", "Questions"],
  },
  {
    "dir": "dentistes/05-nova-smile",
    "seo_h1": "Orthodontie adulte et gouttières transparentes à Nice",
    "founder": ("Dr Sarah Benhamou", "chirurgien-dentiste, orthodontie de l'adulte"),
    "photo": ("6627574", "smiling-woman-in-dentist-chair-looking-in-mirror-6627574", "Karola G"),
    "name": "Nova Sourire", "tagline": "Orthodontie adulte · Nice",
    "schema": "Dentist",
    "city": "Nice", "cp": "06000", "street": "9 avenue Jean-Médecin",
    "phone": "04 65 71 47 83", "tel": "+33465714783",
    "hours": "Du lundi au samedi, 9 h à 19 h", "hours_schema": "Mo-Sa 09:00-19:00",
    "zone_short": "Nice centre, tram Jean-Médecin",
    "zone": ["Nice", "Saint-Laurent-du-Var", "Cagnes-sur-Mer", "Villefranche-sur-Mer", "Cannes", "Antibes"],
    "zone_label": "Patients venant de",
    "top3": "Simulation 3D du résultat offerte",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Gouttières transparentes et orthodontie adulte à Nice · Simulation 3D | Nova Sourire",
    "desc": "Nova Sourire à Nice : orthodontie pour adultes par gouttières transparentes, scan 3D sans pâte et simulation du résultat avant de commencer. Paiement échelonné, suivi rapproché.",
    "fonts": ("Sora", "Sora:wght@600;700;800", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F7F6FC", chalk="#EAE7F7", ink="#0F0C24", muted="#5A5770", line="#DAD6EC", accent="#9B85FF", deep="#5B3FE0"),
    "layout": "split-right",
    "icon": TOOTH,
    "eyebrow": "Orthodontie adulte · Nice",
    "h1": ("Des dents alignées sans bagues visibles,", "et le résultat en 3D avant de commencer."),
    "lead": "Gouttières transparentes, amovibles, quasi invisibles au travail comme en photo. Un scan 3D de vos dents en quelques minutes, sans pâte, et une simulation de votre sourire final avant toute décision.",
    "proofs": ["Scan 3D et simulation offerts", "Gouttières quasi invisibles et amovibles", "Paiement échelonné sur la durée du traitement"],
    "cta": "Réserver mon scan 3D", "note": "Consultation de 45 minutes, résultat simulé le jour même.",
    "badge": ("3D", "votre sourire final<br>simulé avant de décider"),
    "alt": "Une patiente souriante se regarde dans un miroir après un soin dentaire",
    "sit_title": "Qu'est-ce qui vous gêne ?",
    "sits": [
      ("Mes dents se chevauchent", "Alignement progressif par gouttières, souvent en moins d'un an.", "Dents qui se chevauchent"),
      ("J'ai des espaces entre les dents", "Fermeture des espaces, parfois combinée à un composite.", "Espaces entre les dents"),
      ("Mes dents ont bougé après un appareil ado", "Récidive corrigée, puis contention pour que ça tienne.", "Récidive après appareil"),
      ("Je ne veux pas de bagues visibles", "Gouttières transparentes que vous retirez pour manger.", "Gouttières transparentes"),
      ("Je me marie ou j'ai un événement", "Plan de traitement calé sur votre date si c'est possible.", "Événement à venir"),
      ("Je veux juste savoir si c'est possible", "Scan 3D et simulation, sans engagement.", "Simulation 3D"),
    ],
    "serv_eyebrow": "Nos traitements", "serv_h2": "L'orthodontie pensée pour les adultes.",
    "servs": [
      ("Gouttières transparentes", "Une série de gouttières sur mesure qui déplacent les dents par étapes, à porter environ 22 h par jour."),
      ("Scan 3D sans pâte", "Une caméra enregistre vos dents en quelques minutes, sans empreinte désagréable."),
      ("Simulation du résultat", "Votre sourire final et les étapes intermédiaires visualisés avant de commencer."),
      ("Contention", "Fil collé ou gouttière de nuit pour que les dents restent en place."),
      ("Blanchiment de fin de traitement", "En option, pour finir avec un sourire aligné et éclatant."),
      ("Suivi rapproché", "Contrôles réguliers au cabinet, ajustements si besoin."),
    ],
    "steps_h2": "De la simulation au sourire aligné.",
    "steps": [
      ("Consultation et scan 3D", "Examen, radio, scan en quelques minutes."),
      ("Simulation", "Vous voyez le résultat et la durée estimée."),
      ("Devis et paiement échelonné", "Prix total, mensualités, ce que la mutuelle peut rembourser."),
      ("Gouttières et suivi", "Nouvelles gouttières par étapes, contrôles réguliers."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Quelques exemples de traitements.",
    "job_labels": ("Traitement", "Durée"),
    "jobs": [
      ("Patiente de 31 ans", "Incisives du bas qui se chevauchaient", "Gouttières", "8 mois"),
      ("Patient de 44 ans", "Récidive 25 ans après un appareil", "Gouttières et contention", "10 mois"),
      ("Patiente de 27 ans", "Espace entre les incisives avant son mariage", "Gouttières et composite", "5 mois"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Voir avant de payer.", "La simulation 3D est offerte, sans engagement."),
      ("Un prix total.", "Traitement, gouttières, contrôles et contention : un seul prix annoncé."),
      ("Un suivi réel.", "Un orthodontiste vous voit en personne à chaque étape clé."),
      ("L'honnêteté.", "Si les gouttières ne conviennent pas à votre cas, on vous le dit."),
    ],
    "reviews": [
      ("« Personne au bureau ne s'est rendu compte que je portais des gouttières. Huit mois plus tard, mes dents sont droites. »", "Julie A. · Nice · Gouttières"),
      ("« La simulation m'a convaincu. Le résultat final est exactement celui qu'on m'avait montré. »", "Marc-Olivier T. · Cagnes-sur-Mer · Récidive"),
    ],
    "faq": [
      ("L'orthodontie adulte est-elle remboursée ?", "L'Assurance maladie ne rembourse pas l'orthodontie commencée après 16 ans. Beaucoup de mutuelles prévoient un forfait : le devis vous permet de le demander."),
      ("Combien de temps dure un traitement par gouttières ?", "Souvent de six mois à un an et demi selon le déplacement à obtenir. La simulation indique une durée estimée pour votre cas."),
      ("Les gouttières sont-elles vraiment invisibles ?", "Elles sont transparentes et fines : la plupart des gens ne les remarquent pas. Vous les retirez pour manger et vous brosser les dents."),
      ("Combien d'heures par jour faut-il les porter ?", "Environ 22 heures par jour pour que le traitement avance comme prévu."),
      ("Les gouttières conviennent-elles à tous les cas ?", "Non. Certains déplacements complexes demandent un appareil fixe. Nous vous le disons lors de la consultation."),
      ("Que se passe-t-il après le traitement ?", "Une contention (fil collé ou gouttière de nuit) maintient les dents en place durablement."),
    ],
    "quote_h2": "Réservez votre scan 3D.", "quote_p": "Dites-nous ce qui vous gêne. Nous vous rappelons pour fixer la consultation avec simulation.",
    "work_label": "Ce qui vous gêne",
    "works": ["Dents qui se chevauchent", "Espaces entre les dents", "Récidive après appareil", "Gouttières transparentes", "Événement à venir", "Simulation 3D", "Autre"],
    "extra": ("event", "Date à respecter", "Ex. : mariage en juin 2027", True),
    "details_label": "Précisions",
    "details_ph": "Ex. : appareil porté ado, les dents du bas ont bougé depuis",
    "success": "Merci {first}. Nous vous rappelons {when} pour fixer votre consultation avec scan 3D.",
    "success_end": "",
    "nav": ["Nos traitements", "Votre rendez-vous", "Parcours", "Questions"],
  },
]
