"""Paysagiste et cabinet d'avocats : refaits au format orienté client (septembre 2026)."""

LEAF = '<path class="blade" d="M26 5C13 5 6 12 6 21c0 2 .6 3.8 1.6 5.2L5 28.8 6.4 30.2l2.6-2.6C10.4 28.4 12 29 14 29c9 0 14-7 14-20 0-1.5-.7-3-2-4z"/>'
SCALE = '<path d="M16 5v22M9 27h14M6 9h20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/><path class="blade" d="M6 10l-4 8a4 4 0 0 0 8 0zM26 10l-4 8a4 4 0 0 0 8 0z"/>'

SITES = [
  {
    "dir": "paysagistes/01-seve-pierre",
    "seo_h1": "Paysagiste à Saint-Germain-en-Laye : création et entretien de jardins dans les Yvelines",
    "founder": ("Mathilde Sève", "paysagiste conceptrice, fondatrice"),
    "photo": ("24595771", "man-cutting-hedge-with-a-trimmer-in-the-garden-24595771", "Stitch"),
    "name": "Sève & Pierre", "tagline": "Paysagistes depuis 2003 · Yvelines",
    "schema": "HomeAndConstructionBusiness",
    "city": "Saint-Germain-en-Laye", "cp": "78100", "street": "31 rue de Pontoise",
    "phone": "01 99 00 84 36", "tel": "+33199008436",
    "hours": "Du lundi au vendredi, 8 h à 18 h", "hours_schema": "Mo-Fr 08:00-18:00",
    "zone_short": "Yvelines et ouest parisien",
    "zone": ["Saint-Germain-en-Laye", "Le Vésinet", "Chatou", "Croissy-sur-Seine", "Maisons-Laffitte", "Le Pecq", "Versailles", "Marly-le-Roi", "Louveciennes"],
    "top3": "Entretien : 50 % en crédit d'impôt",
    "title": "Paysagiste Saint-Germain-en-Laye · Création, terrasses, entretien de jardin | Sève & Pierre",
    "desc": "Sève & Pierre, paysagistes dans les Yvelines depuis 2003 : conception et création de jardins, terrasses, plantations, arrosage, et entretien régulier ouvrant droit au crédit d'impôt de 50 %.",
    "fonts": ("Fraunces", "Fraunces:opsz,wght@9..144,600;9..144,700", "Karla", "Karla:wght@400;500;600"),
    "pal": dict(paper="#F7F4EC", chalk="#ECE6D8", ink="#1B3A2B", muted="#5B6A5F", line="#DDD5C3", accent="#D08A55", deep="#9A5427"),
    "layout": "overlay",
    "icon": LEAF,
    "eyebrow": "Paysagistes · Yvelines",
    "h1": ("Un jardin dont vous profitez,", "au lieu d'y passer tous vos week-ends."),
    "lead": "Nous dessinons votre jardin, le créons, puis l'entretenons toute l'année si vous le souhaitez. Terrasse, plantations, arrosage automatique, taille : vous gardez le plaisir, on s'occupe du travail. L'entretien ouvre droit à 50 % de crédit d'impôt.",
    "proofs": ["Visite et conseil gratuits dans votre jardin", "Plan et visuels avant les travaux", "Entretien : 50 % de crédit d'impôt"],
    "cta": "Demander une visite", "note": "Visite sous 10 jours. Au printemps, anticipez : le planning se remplit vite.",
    "badge": ("-50 %", "de crédit d'impôt<br>sur l'entretien du jardin"),
    "alt": "Un jardinier taille une haie dans un jardin ensoleillé",
    "sit_title": "Où en est votre jardin ?",
    "sits": [
      ("Je viens d'emménager, tout est à faire", "Conception complète, plan, visuels, puis création.", "Création de jardin"),
      ("Je veux une terrasse pour vivre dehors", "Bois, pierre ou carrelage, avec les plantations autour.", "Terrasse"),
      ("Je n'ai plus le temps d'entretenir", "Contrat d'entretien, passages réguliers, crédit d'impôt.", "Entretien régulier"),
      ("Mes haies et arbres sont trop grands", "Taille, élagage et évacuation des déchets verts.", "Taille et élagage"),
      ("Je veux un arrosage automatique", "Réseau enterré, programmateur, économie d'eau.", "Arrosage automatique"),
      ("Je veux un jardin plus facile à vivre", "Refonte partielle, plantes adaptées, moins d'entretien.", "Rénovation de jardin"),
    ],
    "serv_eyebrow": "Nos prestations", "serv_h2": "De la première esquisse au jardin entretenu.",
    "servs": [
      ("Conception de jardin", "Relevé du terrain, plan, choix des plantes adaptées au sol et à l'exposition, visuels."),
      ("Création et plantations", "Préparation du sol, massifs, haies, arbres, gazon, allées et bordures."),
      ("Terrasses et allées", "Bois, pierre naturelle, dallage ou gravier stabilisé, avec éclairage si souhaité."),
      ("Arrosage automatique", "Goutte-à-goutte et arroseurs enterrés, programmation adaptée aux saisons."),
      ("Entretien régulier", "Tonte, taille, désherbage, ramassage des feuilles : 50 % de crédit d'impôt."),
      ("Taille et élagage", "Haies, arbustes et arbres, avec évacuation des déchets verts."),
    ],
    "steps_h2": "Comment naît votre jardin.",
    "steps": [
      ("Visite du jardin", "On écoute vos envies, on observe le sol, la lumière et les vues."),
      ("Plan et visuels", "Vous voyez le futur jardin, plantes et matériaux inclus."),
      ("Devis détaillé", "Création chiffrée poste par poste, entretien proposé à part."),
      ("Réalisation et suivi", "Chantier propre, plantations garanties, conseils d'arrosage."),
    ],
    "job_labels": ("Travaux", "Durée"),
    "jobs": [
      ("Le Vésinet · Maison de maître", "Jardin de 800 m² entièrement redessiné", "Conception et création", "5 semaines"),
      ("Chatou · Pavillon", "Terrasse en pierre et massifs de vivaces", "Terrasse et plantations", "2 semaines"),
      ("Saint-Germain-en-Laye · Maison", "Entretien toute l'année, deux passages par mois", "Contrat d'entretien", "Toute l'année"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Des plantes qui tiennent.", "Choisies pour votre sol et votre exposition, garanties un an après plantation."),
      ("Un jardin à votre mesure.", "On dessine selon le temps que vous voulez y passer."),
      ("Un chantier propre.", "Accès protégés, déchets évacués, pelouse remise en état."),
      ("Des attestations fiscales.", "Attestation annuelle pour votre crédit d'impôt sur l'entretien."),
    ],
    "reviews": [
      ("« Nous avions un terrain vide. Deux ans plus tard, c'est la pièce de la maison où l'on vit le plus. »", "Hélène et Marc D. · Le Vésinet · Création de jardin"),
      ("« Contrat d'entretien depuis cinq ans, toujours la même équipe, et le crédit d'impôt divise la facture par deux. »", "Bernard P. · Saint-Germain-en-Laye · Entretien"),
    ],
    "faq": [
      ("L'entretien du jardin donne-t-il droit à un crédit d'impôt ?", "Oui, les petits travaux de jardinage chez un particulier (tonte, taille, désherbage) ouvrent droit à un crédit d'impôt de 50 % dans la limite d'un plafond annuel. La création de jardin et les terrasses n'y ouvrent pas droit."),
      ("Combien coûte la création d'un jardin ?", "Le budget dépend de la surface, des matériaux et des plantes. Après la visite, nous vous remettons un plan et un devis détaillé, avec plusieurs options si vous le souhaitez."),
      ("Quelle est la meilleure saison pour planter ?", "L'automne et la fin de l'hiver sont idéaux pour la plupart des arbres et arbustes. Les travaux de terrasse peuvent se faire presque toute l'année."),
      ("Faut-il une autorisation pour une terrasse ?", "Une terrasse de plain-pied n'en demande généralement pas, mais certaines communes et secteurs protégés ont des règles. Nous vérifions avec vous."),
      ("Proposez-vous un entretien ponctuel ?", "Oui, pour une taille de haie, un nettoyage de printemps ou d'automne, en plus des contrats réguliers."),
      ("Pouvez-vous créer un jardin demandant peu d'entretien ?", "Oui : plantes adaptées, paillage, arrosage automatique et gazon réduit permettent un jardin beau avec peu d'effort."),
    ],
    "quote_h2": "Parlez-nous de votre jardin.", "quote_p": "Quelques mots sur votre jardin et vos envies. On vous rappelle pour fixer une visite, gratuite et sans engagement.",
    "work_label": "Votre projet",
    "works": ["Création de jardin", "Terrasse", "Entretien régulier", "Taille et élagage", "Arrosage automatique", "Rénovation de jardin", "Autre"],
    "extra": ("surface", "Surface du jardin", "Ex. : environ 500 m²", True),
    "details_ph": "Ex. : jardin de 500 m² à l'abandon, nous voudrions une terrasse et un coin potager",
    "success_end": "fixer la visite de votre jardin",
    "nav": ["Nos prestations", "Comment ça se passe", "Réalisations", "Questions"],
  },
  {
    "dir": "avocats/01-roussel-associes",
    "seo_h1": "Avocats à Montpellier : famille, travail, immobilier, succession",
    "founder": ("Me Hélène Roussel", "avocate associée, inscrite au barreau de Montpellier"),
    "photo": ("8112166", "lawyer-in-elegant-office-meeting-clients-8112166", "Pavel Danilyuk"),
    "name": "Roussel & Associés", "tagline": "Cabinet d'avocats · Montpellier",
    "schema": "LegalService",
    "city": "Montpellier", "cp": "34000", "street": "4 rue Foch",
    "phone": "04 65 71 72 90", "tel": "+33465717290",
    "hours": "Du lundi au vendredi, 9 h à 19 h", "hours_schema": "Mo-Fr 09:00-19:00",
    "zone_short": "Montpellier et Hérault",
    "zone": ["Montpellier", "Hérault", "Gard", "Consultations en visio partout en France"],
    "zone_label": "Nous recevons à Montpellier et en visio :",
    "top3": "Honoraires annoncés par écrit",
    "form": "rdv",
    "legal": "Vos informations sont couvertes par le secret professionnel dès votre premier contact. Décrivez votre situation en quelques mots seulement.",
    "title": "Avocat à Montpellier · Divorce, licenciement, bail, succession | Roussel & Associés",
    "desc": "Roussel & Associés, avocats à Montpellier : droit de la famille (divorce, garde), droit du travail (licenciement), immobilier (bail, copropriété), successions. Première consultation au tarif annoncé, honoraires par écrit.",
    "fonts": ("Cormorant Garamond", "Cormorant+Garamond:ital,wght@0,600;0,700;1,600", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F8F6F0", chalk="#ECE8DD", ink="#101A2E", muted="#56607A", line="#DEDACF", accent="#C4A15A", deep="#7E6224"),
    "layout": "split-left",
    "icon": SCALE,
    "eyebrow": "Cabinet d'avocats · Montpellier",
    "h1": ("Comprendre vos droits dès le premier rendez-vous,", "et savoir combien cela va coûter."),
    "lead": "Divorce, licenciement, litige avec un propriétaire, succession : nous vous expliquons votre situation en langage clair, les options possibles et leurs chances. Le prix de la première consultation est annoncé, et nos honoraires sont fixés par écrit.",
    "proofs": ["Première consultation au tarif annoncé à l'avance", "Convention d'honoraires écrite et détaillée", "Rendez-vous au cabinet ou en visio sous une semaine"],
    "cta": "Prendre rendez-vous", "note": "Aide juridictionnelle acceptée selon vos ressources.",
    "badge": ("7 jours", "pour un premier<br>rendez-vous en moyenne"),
    "alt": "Une avocate reçoit des clients dans son bureau pour une consultation",
    "sit_title": "De quoi s'agit-il ?",
    "sits": [
      ("Je veux divorcer ou me séparer", "Divorce amiable ou contentieux, garde des enfants, pension.", "Divorce, séparation"),
      ("J'ai été licencié(e) ou on me pousse à partir", "Contestation, rupture conventionnelle, négociation.", "Licenciement, travail"),
      ("J'ai un litige avec mon propriétaire ou locataire", "Loyers impayés, dépôt de garantie, travaux, expulsion.", "Bail, logement"),
      ("Je dois régler une succession", "Partage, conflit entre héritiers, testament.", "Succession"),
      ("J'ai un conflit avec une entreprise ou un artisan", "Mise en demeure, négociation, action en justice.", "Litige, consommation"),
      ("Je suis convoqué(e) par la police ou au tribunal", "Assistance, défense, conseils immédiats.", "Pénal"),
    ],
    "serv_eyebrow": "Nos domaines", "serv_h2": "Six domaines du droit qui touchent la vie de chacun.",
    "servs": [
      ("Droit de la famille", "Divorce, séparation, garde des enfants, pension alimentaire, prestation compensatoire."),
      ("Droit du travail", "Licenciement, rupture conventionnelle, harcèlement, heures supplémentaires, pour les salariés."),
      ("Immobilier", "Baux d'habitation, copropriété, vices cachés, litiges de voisinage."),
      ("Successions", "Règlement et partage, conflits entre héritiers, contestation de testament."),
      ("Litiges et consommation", "Artisans, entreprises, assurances : de la mise en demeure au procès."),
      ("Droit pénal", "Garde à vue, audition, défense devant le tribunal, assistance des victimes."),
    ],
    "steps_h2": "Comment se passe la prise en charge.",
    "steps": [
      ("Premier contact", "Vous décrivez votre situation en quelques lignes. Secret professionnel garanti."),
      ("Première consultation", "Au cabinet ou en visio, au tarif annoncé : analyse et options."),
      ("Convention d'honoraires", "Si vous nous confiez le dossier, les honoraires sont fixés par écrit."),
      ("Suivi du dossier", "Point régulier, réponse à vos messages sous 48 h ouvrées."),
    ],
    "jobs_eyebrow": "Dossiers récents", "jobs_h2": "Quelques exemples, anonymisés.",
    "job_labels": ("Domaine", "Issue"),
    "jobs": [
      ("Salariée, 12 ans d'ancienneté", "Licenciement contesté, indemnités obtenues", "Droit du travail", "Accord transactionnel"),
      ("Couple avec deux enfants", "Divorce par consentement mutuel sans juge", "Droit de la famille", "4 mois"),
      ("Locataire", "Dépôt de garantie retenu abusivement, restitué", "Bail d'habitation", "Mise en demeure"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Parler clairement.", "Pas de jargon : vous comprenez votre dossier et vos chances."),
      ("Des honoraires écrits.", "Forfait ou taux horaire fixé par convention, sans surprise."),
      ("Être joignable.", "Réponse à vos messages sous 48 h ouvrées."),
      ("Vous dire la vérité.", "Si un procès n'en vaut pas la peine, nous vous le disons."),
    ],
    "reviews": [
      ("« Pour la première fois, j'ai compris où j'en étais. Honoraires fixés dès le départ, et respectés. »", "Client · Montpellier · Droit du travail"),
      ("« Divorce géré avec humanité et efficacité. Les enfants ont été au centre de chaque décision. »", "Cliente · Hérault · Droit de la famille"),
    ],
    "faq": [
      ("Combien coûte un avocat ?", "Le prix de la première consultation est annoncé avant le rendez-vous. Si vous nous confiez votre dossier, une convention d'honoraires écrite fixe le forfait ou le taux horaire : c'est obligatoire et vous en gardez un exemplaire."),
      ("Ai-je droit à l'aide juridictionnelle ?", "Selon vos ressources, l'État peut prendre en charge tout ou partie des honoraires. Nous acceptons l'aide juridictionnelle et vous aidons à en faire la demande."),
      ("Mon assurance peut-elle payer l'avocat ?", "Beaucoup de contrats d'assurance habitation, auto ou carte bancaire incluent une protection juridique qui prend en charge une partie des frais. Vérifiez votre contrat ou apportez-le au rendez-vous."),
      ("Peut-on divorcer sans passer devant le juge ?", "Oui, lorsque les deux époux sont d'accord sur tout : le divorce par consentement mutuel se fait par acte d'avocats enregistré chez un notaire. Chaque époux doit avoir son propre avocat."),
      ("Combien de temps pour contester un licenciement ?", "Le délai pour saisir le conseil de prud'hommes est en principe de 12 mois après la notification du licenciement. Consultez rapidement pour ne pas le dépasser."),
      ("Les consultations en visio sont-elles possibles ?", "Oui, partout en France, avec la même confidentialité qu'au cabinet."),
    ],
    "quote_h2": "Prenez rendez-vous.", "quote_p": "Indiquez le domaine et quelques mots sur votre situation. Nous vous rappelons pour fixer une première consultation.",
    "work_label": "Domaine",
    "works": ["Divorce, séparation", "Licenciement, travail", "Bail, logement", "Succession", "Litige, consommation", "Pénal", "Autre"],
    "extra": ("urgency", "Date importante à respecter", "Ex. : audience le 15 novembre", True),
    "avail": ["Dès que possible", "Cette semaine", "En visio", "Au cabinet"],
    "details_label": "Votre situation en quelques mots",
    "details_ph": "Ex. : licenciée après 8 ans, je voudrais savoir si je peux contester",
    "success": "Merci {first}. Nous vous rappelons {when} pour fixer votre première consultation, en toute confidentialité.",
    "success_end": "",
    "nav": ["Nos domaines", "Comment ça se passe", "Dossiers", "Questions"],
  },
]
