"""Ophtalmologie et optique : 5 marques refaites au format orienté patient (septembre 2026)."""

EYE = '<path d="M3 16s5-8 13-8 13 8 13 8-5 8-13 8S3 16 3 16z" fill="none" stroke="currentColor" stroke-width="2.4"/><circle class="blade" cx="16" cy="16" r="4.5"/>'

NAV = ["Nos consultations", "Votre rendez-vous", "Parcours", "Questions"]
LEGAL = "Vos informations servent uniquement à organiser votre rendez-vous. Ne transmettez pas de données médicales détaillées par ce formulaire."

SITES = [
  {
    "dir": "ophtalmologie/01-iris-prive",
    "seo_h1": "Opticien créateur à Paris 6e : lunettes sur mesure et examen de vue",
    "founder": ("Camille Rousseau", "opticienne diplômée, fondatrice"),
    "photo": ("5766154", "young-woman-adjusting-glasses-in-optical-store-5766154", "Ksenia Chernaya"),
    "name": "Iris Privé", "tagline": "Opticien créateur · Paris 6e",
    "schema": "Optician",
    "city": "Paris", "cp": "75006", "street": "27 rue du Cherche-Midi",
    "phone": "01 99 00 63 19", "tel": "+33199006319",
    "hours": "Du mardi au samedi, 10 h à 19 h", "hours_schema": "Tu-Sa 10:00-19:00",
    "zone_short": "Boutique rue du Cherche-Midi",
    "zone": ["Paris 6e", "Paris 7e", "Paris 14e", "Paris 15e", "Saint-Germain-des-Prés"],
    "shop": True,
    "top3": "Essayage privé sur rendez-vous",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Opticien à Paris 6e · Lunettes de créateurs, examen de vue, essayage privé | Iris Privé",
    "desc": "Iris Privé, opticien à Paris 6e : montures de créateurs indépendants, examen de vue en boutique, verres progressifs ajustés, essayage privé sur rendez-vous. Tiers payant avec la plupart des mutuelles.",
    "fonts": ("Cormorant Garamond", "Cormorant+Garamond:ital,wght@0,600;0,700;1,600", "Montserrat", "Montserrat:wght@400;500;600"),
    "pal": dict(paper="#FAF8F3", chalk="#EEE9DE", ink="#1C3F5A", muted="#5A6B78", line="#E0D9CB", accent="#C9A24B", deep="#83641A"),
    "layout": "split-left",
    "icon": EYE,
    "eyebrow": "Opticien créateur · Paris 6e",
    "h1": ("Des lunettes qui vous ressemblent,", "choisies avec vous, pas pour vous."),
    "lead": "Une heure d'essayage privé, des montures de créateurs que l'on ne voit pas partout, un examen de vue en boutique et des verres ajustés à votre façon de lire, de conduire ou de travailler sur écran.",
    "proofs": ["Essayage privé d'une heure sur rendez-vous", "Examen de vue en boutique", "Tiers payant avec la plupart des mutuelles"],
    "cta": "Réserver un essayage", "note": "Sans rendez-vous aussi, selon l'affluence.",
    "badge": ("1 h", "d'essayage privé<br>rien que pour vous"),
    "alt": "Une cliente essaie une paire de lunettes chez l'opticien",
    "sit_title": "Qu'est-ce qui vous amène ?",
    "sits": [
      ("J'ai une ordonnance, je veux de nouvelles lunettes", "Essayage, choix des verres et prise de mesures.", "Nouvelles lunettes"),
      ("Je vois moins bien de près", "Examen de vue, puis verres progressifs ou lunettes de lecture.", "Vision de près"),
      ("Mes progressifs me donnent le tournis", "Nouvelles mesures et verres adaptés à vos usages.", "Verres progressifs"),
      ("Je passe mes journées sur écran", "Verres adaptés au travail sur écran, moins de fatigue.", "Travail sur écran"),
      ("Je veux des solaires à ma vue", "Montures solaires avec verres correcteurs.", "Solaires à la vue"),
      ("Mes lunettes sont cassées ou tordues", "Réparation et ajustage, souvent pendant que vous attendez.", "Réparation"),
    ],
    "serv_eyebrow": "La boutique", "serv_h2": "Une boutique où l'on prend le temps de bien voir.",
    "servs": [
      ("Montures de créateurs", "Maisons indépendantes françaises et européennes, séries limitées, acétate et titane."),
      ("Examen de vue", "Contrôle de votre vue en boutique pour ajuster vos verres, dans le cadre prévu par la réglementation."),
      ("Verres progressifs", "Mesures précises de votre posture et de vos usages pour une adaptation rapide."),
      ("Verres pour écrans", "Verres qui soulagent les yeux lors des longues journées devant l'ordinateur."),
      ("Solaires à la vue", "Toutes nos montures solaires peuvent recevoir votre correction."),
      ("Ajustage et réparation", "Réglage offert à vie sur les lunettes achetées chez nous."),
    ],
    "steps_h2": "Votre rendez-vous chez nous.",
    "steps": [
      ("Vous réservez", "Un créneau d'une heure, rien que pour vous."),
      ("Examen et conseil", "Contrôle de la vue si besoin, échange sur vos usages."),
      ("Essayage", "Montures sélectionnées selon votre visage et votre style."),
      ("Remise des lunettes", "Ajustage final et conseils d'entretien, sous 7 à 10 jours."),
    ],
    "jobs_eyebrow": "Nos clients", "jobs_h2": "Quelques paires récentes.",
    "job_labels": ("Équipement", "Délai"),
    "jobs": [
      ("Architecte, 46 ans", "Premiers progressifs, monture acétate écaille", "Verres progressifs", "8 jours"),
      ("Étudiant, 22 ans", "Verres pour écrans et monture titane légère", "Travail sur écran", "7 jours"),
      ("Retraitée, 70 ans", "Solaires à la vue pour la conduite", "Solaires correcteurs", "10 jours"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Le temps du conseil.", "Un essayage d'une heure, sans pression."),
      ("Des verres adaptés.", "Des mesures précises, et une nouvelle adaptation si vous ne vous y faites pas."),
      ("Des prix clairs.", "Devis détaillé avec ce que prend en charge votre mutuelle."),
      ("Un suivi à vie.", "Ajustage et nettoyage offerts pour vos lunettes Iris Privé."),
    ],
    "reviews": [
      ("« Une heure rien que pour moi, et une monture que je n'avais vue nulle part. On me complimente sans arrêt. »", "Sophie L. · Paris 6e · Nouvelles lunettes"),
      ("« Mes précédents progressifs me donnaient le vertige. Ici, adaptation en deux jours. »", "Jean-Pierre M. · Paris 7e · Verres progressifs"),
    ],
    "faq": [
      ("Faut-il une ordonnance pour acheter des lunettes ?", "Pour être remboursé, oui. Selon votre âge et la date de votre ordonnance, l'opticien peut aussi renouveler vos verres après un examen de vue en boutique."),
      ("Pratiquez-vous le tiers payant ?", "Oui, avec la plupart des mutuelles. Nous vérifions votre prise en charge avant la commande."),
      ("Proposez-vous l'offre « 100 % Santé » ?", "Oui, comme tous les opticiens, nous proposons une sélection de montures et de verres sans reste à charge. Nous vous la présentons à chaque devis."),
      ("Combien de temps pour recevoir mes lunettes ?", "Généralement de 7 à 10 jours, un peu plus pour certains verres très spécifiques."),
      ("Que faire si je ne m'adapte pas à mes progressifs ?", "Revenez nous voir : nous reprenons les mesures et, si nécessaire, faisons refaire les verres."),
      ("Faut-il prendre rendez-vous ?", "C'est conseillé pour l'essayage privé, mais vous pouvez aussi passer sans rendez-vous."),
    ],
    "quote_h2": "Réservez votre essayage.", "quote_p": "Dites-nous ce que vous cherchez. Nous vous rappelons pour fixer un créneau d'une heure.",
    "work_label": "Motif",
    "works": ["Nouvelles lunettes", "Vision de près", "Verres progressifs", "Travail sur écran", "Solaires à la vue", "Réparation", "Autre"],
    "extra": ("prescription", "Avez-vous une ordonnance ?", "Ex. : oui, de moins d'un an", True),
    "details_label": "Ce que vous cherchez",
    "details_ph": "Ex. : première paire de progressifs, j'aime les montures fines et dorées",
    "success": "Merci {first}. Nous vous rappelons {when} pour fixer votre essayage.",
    "success_end": "",
    "nav": ["La boutique", "Votre rendez-vous", "Nos clients", "Questions"],
  },
  {
    "dir": "ophtalmologie/02-meridian-eye",
    "seo_h1": "Chirurgie réfractive et cataracte à Lyon : opération de la myopie",
    "founder": ("Dr Philippe Vernet", "ophtalmologiste, chirurgien réfractif"),
    "photo": ("38167595", "routine-eye-examination-at-optometrist-clinic-38167595", "Fernando Capetillo"),
    "name": "Institut Méridien", "tagline": "Chirurgie de la vue · Lyon",
    "schema": "MedicalClinic",
    "city": "Lyon", "cp": "69002", "street": "15 quai Jules-Courmont",
    "phone": "04 65 71 39 52", "tel": "+33465713952",
    "hours": "Du lundi au vendredi, 8 h à 19 h", "hours_schema": "Mo-Fr 08:00-19:00",
    "zone_short": "Lyon 2e, presqu'île",
    "zone": ["Lyon", "Villeurbanne", "Rhône", "Ain", "Isère", "Saône-et-Loire"],
    "zone_label": "Patients venant de",
    "top3": "Bilan préopératoire complet",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Opération de la myopie à Lyon · LASIK, PKR, SMILE, cataracte | Institut Méridien",
    "desc": "Institut Méridien à Lyon : chirurgie réfractive (LASIK, PKR, SMILE) pour la myopie, l'astigmatisme et la presbytie, chirurgie de la cataracte. Bilan préopératoire complet et devis détaillé.",
    "fonts": ("Space Grotesk", "Space+Grotesk:wght@500;600;700", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F5F8FB", chalk="#E4EDF6", ink="#0B1420", muted="#536172", line="#D3DEEA", accent="#4FA3F0", deep="#0E63C4"),
    "layout": "overlay",
    "icon": EYE,
    "eyebrow": "Chirurgie de la vue · Lyon",
    "h1": ("Vivre sans lunettes ni lentilles ?", "Un bilan complet vous dit d'abord si c'est possible pour vous."),
    "lead": "Myopie, astigmatisme, presbytie, cataracte : avant toute opération, un bilan de 90 minutes mesure vos yeux en détail. Le chirurgien vous explique la technique adaptée, ses résultats attendus et ses limites, puis vous remet un devis.",
    "proofs": ["Bilan préopératoire de 90 minutes", "Technique choisie selon vos yeux, pas selon une offre", "Devis écrit et délai de réflexion respecté"],
    "cta": "Réserver mon bilan", "note": "Pensez à retirer vos lentilles plusieurs jours avant le bilan : nous vous précisons le délai.",
    "badge": ("90 min", "de bilan avant<br>toute décision"),
    "alt": "Une ophtalmologiste examine l'œil d'un patient à la lampe à fente",
    "sit_title": "Quelle est votre situation ?",
    "sits": [
      ("Je suis myope et je ne supporte plus mes lentilles", "Bilan pour savoir si LASIK, PKR ou SMILE vous conviennent.", "Myopie"),
      ("J'ai de l'astigmatisme", "La plupart des astigmatismes se corrigent avec les mêmes techniques.", "Astigmatisme"),
      ("J'ai besoin de lunettes pour lire", "Solutions pour la presbytie, selon votre âge et vos yeux.", "Presbytie"),
      ("On m'a parlé de cataracte", "Consultation et, si besoin, opération en ambulatoire.", "Cataracte"),
      ("On m'a dit que j'étais inopérable ailleurs", "Deuxième avis avec des mesures complètes.", "Deuxième avis"),
      ("Je veux juste savoir si c'est possible", "Le bilan est fait pour ça, sans engagement.", "Bilan préopératoire"),
    ],
    "serv_eyebrow": "Nos consultations", "serv_h2": "La chirurgie de la vue, expliquée avant d'être proposée.",
    "servs": [
      ("LASIK", "Découpe d'un fin volet de cornée puis remodelage au laser. Récupération visuelle rapide."),
      ("PKR", "Laser en surface, sans découpe. Adaptée aux cornées fines, récupération un peu plus longue."),
      ("SMILE", "Extraction d'un fin lenticule par une petite incision. Selon les indications."),
      ("Presbytie", "Selon l'âge et les yeux : laser ou implant, après une discussion approfondie."),
      ("Cataracte", "Remplacement du cristallin opacifié par un implant, en ambulatoire, pris en charge par l'Assurance maladie."),
      ("Bilan préopératoire", "Topographie, épaisseur de cornée, pupille, fond d'œil : tout est mesuré."),
    ],
    "steps_h2": "Votre parcours, de la question à la vue nette.",
    "steps": [
      ("Bilan complet", "Mesures détaillées, 90 minutes."),
      ("Consultation avec le chirurgien", "Technique proposée, résultats attendus, risques expliqués."),
      ("Réflexion et devis", "Devis écrit, délai de réflexion respecté, questions bienvenues."),
      ("Opération et suivi", "Intervention en ambulatoire, contrôles le lendemain, à une semaine et à un mois."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Quelques exemples de parcours.",
    "job_labels": ("Technique", "Reprise"),
    "jobs": [
      ("Patiente de 29 ans", "Myopie avec intolérance aux lentilles", "LASIK", "2 jours"),
      ("Patient de 35 ans", "Myopie et cornée fine", "PKR", "1 semaine"),
      ("Patiente de 68 ans", "Cataracte gênant la conduite de nuit", "Chirurgie de la cataracte", "Quelques jours"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("La vérité sur votre cas.", "Si l'opération n'est pas indiquée, on vous le dit, et pourquoi."),
      ("Aucune pression.", "Délai de réflexion respecté, pas d'offre limitée dans le temps."),
      ("Des prix écrits.", "Devis détaillé, contrôles postopératoires inclus."),
      ("Un suivi par le même chirurgien.", "Celui qui vous opère vous revoit aux contrôles."),
    ],
    "reviews": [
      ("« Le bilan a été très complet et le chirurgien m'a expliqué pourquoi la PKR était plus sûre pour mes yeux. Je vois 10/10. »", "Thomas B. · Lyon · PKR"),
      ("« Personne ne m'a poussé. J'ai réfléchi un mois, et je ne regrette rien. »", "Amélie R. · Villeurbanne · LASIK"),
    ],
    "faq": [
      ("L'opération de la myopie est-elle remboursée ?", "Non, la chirurgie réfractive n'est pas prise en charge par l'Assurance maladie. Certaines mutuelles prévoient un forfait : le devis vous permet de le demander. La chirurgie de la cataracte, elle, est prise en charge."),
      ("Tout le monde peut-il se faire opérer ?", "Non. Il faut une vue stable depuis au moins un an, une cornée suffisamment épaisse et des yeux en bonne santé. C'est ce que vérifie le bilan."),
      ("L'opération fait-elle mal ?", "Elle se fait sous anesthésie par gouttes et dure quelques minutes par œil. Selon la technique, une gêne peut être ressentie les jours suivants."),
      ("Quelle différence entre LASIK et PKR ?", "Le LASIK crée un fin volet de cornée et permet une récupération rapide. La PKR agit en surface, convient aux cornées plus fines, mais la récupération est plus longue."),
      ("À partir de quel âge peut-on se faire opérer ?", "Généralement à partir de 18 ans, quand la vue est stable. Après 45 ans, la presbytie entre aussi en compte."),
      ("Combien de temps avant de reprendre le travail ?", "De un à quelques jours selon la technique et votre métier. Le chirurgien vous le précise lors de la consultation."),
    ],
    "quote_h2": "Réservez votre bilan.", "quote_p": "Dites-nous ce qui vous amène. Nous vous rappelons pour fixer le bilan et vous préciser comment le préparer.",
    "work_label": "Motif",
    "works": ["Myopie", "Astigmatisme", "Presbytie", "Cataracte", "Deuxième avis", "Bilan préopératoire", "Autre"],
    "extra": ("age", "Votre âge", "Ex. : 32 ans", True),
    "details_label": "Précisions",
    "details_ph": "Ex. : myope depuis l'adolescence, je porte des lentilles souples",
    "success": "Merci {first}. Nous vous rappelons {when} pour fixer votre bilan et vous expliquer comment le préparer.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "ophtalmologie/03-hawthorne-eye",
    "seo_h1": "Ophtalmologiste à Rouen : consultations, enfants, glaucome, depuis 1968",
    "founder": ("Dr François Leroux", "ophtalmologiste"),
    "photo": ("6749697", "a-man-having-an-eye-examination-6749697", "Shkraba Anthony"),
    "name": "Cabinet d'ophtalmologie de l'Aubépine", "tagline": "Ophtalmologistes depuis 1968 · Rouen",
    "schema": "Physician",
    "city": "Rouen", "cp": "76000", "street": "22 rue Jeanne-d'Arc",
    "phone": "02 61 91 47 60", "tel": "+33261914760",
    "hours": "Du lundi au vendredi, 8 h 30 à 18 h 30", "hours_schema": "Mo-Fr 08:30-18:30",
    "zone_short": "Rouen centre",
    "zone": ["Rouen", "Mont-Saint-Aignan", "Bois-Guillaume", "Sotteville-lès-Rouen", "Le Grand-Quevilly", "Bihorel", "Darnétal"],
    "zone_label": "Patients venant de",
    "top3": "Rendez-vous sous 4 semaines",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Ophtalmologiste à Rouen · Rendez-vous rapide, enfants, glaucome, lunettes | Cabinet de l'Aubépine",
    "desc": "Cabinet d'ophtalmologie de l'Aubépine à Rouen, depuis 1968 : consultations adultes et enfants, renouvellement de lunettes avec orthoptiste, suivi du glaucome et du diabète. Rendez-vous sous 4 semaines.",
    "fonts": ("Libre Caslon Text", "Libre+Caslon+Text:wght@400;700", "Work Sans", "Work+Sans:wght@400;500;600"),
    "pal": dict(paper="#F9F7F1", chalk="#EDE8DC", ink="#2E4A3A", muted="#5E6B62", line="#DFD8C8", accent="#C9A96A", deep="#7D6021"),
    "layout": "split-right",
    "icon": EYE,
    "eyebrow": "Ophtalmologistes · Rouen",
    "h1": ("Un rendez-vous chez l'ophtalmo en quelques semaines,", "pas en six mois."),
    "lead": "Grâce au travail en équipe avec nos orthoptistes, nous proposons un rendez-vous sous quatre semaines pour la plupart des motifs. Consultations adultes et enfants, renouvellement de lunettes, suivi du glaucome et du diabète.",
    "proofs": ["Rendez-vous sous 4 semaines en moyenne", "Orthoptistes et ophtalmologistes au même endroit", "Créneaux réservés aux enfants et aux urgences"],
    "cta": "Demander un rendez-vous", "note": "Œil rouge et douloureux, baisse de vue brutale : appelez directement.",
    "badge": ("4 sem.", "de délai moyen pour<br>un premier rendez-vous"),
    "alt": "Un patient passe un examen de la vue chez l'ophtalmologiste",
    "sit_title": "Pourquoi consultez-vous ?",
    "sits": [
      ("Je dois renouveler mes lunettes", "Bilan par l'orthoptiste puis consultation, dans la même visite.", "Renouvellement de lunettes"),
      ("Pour mon enfant", "Dépistage, strabisme, première paire : créneaux dédiés.", "Enfant"),
      ("J'ai un glaucome ou on me le suspecte", "Champ visuel, OCT et suivi régulier.", "Glaucome"),
      ("Je suis diabétique", "Fond d'œil annuel recommandé, rendez-vous planifié.", "Diabète"),
      ("J'ai l'œil rouge ou une baisse de vue", "Créneaux d'urgence chaque jour : appelez.", "Urgence"),
      ("Je vois flou ou trouble de loin la nuit", "Recherche d'une cataracte ou d'un autre trouble.", "Vision trouble"),
    ],
    "serv_eyebrow": "Nos consultations", "serv_h2": "Toute l'ophtalmologie de famille, sans attendre des mois.",
    "servs": [
      ("Consultation générale", "Mesure de la vue, examen de l'œil, ordonnance de lunettes ou de lentilles."),
      ("Ophtalmologie pédiatrique", "Dépistage des troubles visuels, strabisme, rééducation orthoptique."),
      ("Glaucome", "Mesure de la pression de l'œil, champ visuel, OCT, suivi au long cours."),
      ("Diabète et rétine", "Fond d'œil de dépistage, suivi de la rétinopathie diabétique."),
      ("Cataracte", "Diagnostic et orientation vers la chirurgie quand elle devient utile."),
      ("Urgences", "Œil rouge, douleur, corps étranger, baisse de vue soudaine : créneaux quotidiens."),
    ],
    "steps_h2": "Comment se passe votre visite.",
    "steps": [
      ("Vous demandez un rendez-vous", "Téléphone ou formulaire, avec le motif."),
      ("Bilan orthoptique", "Mesures de la vue et examens préparatoires par l'orthoptiste."),
      ("Consultation", "L'ophtalmologiste examine vos yeux et vous explique."),
      ("Ordonnance et suivi", "Lunettes, traitement, et prochain rendez-vous si besoin."),
    ],
    "jobs_eyebrow": "Au quotidien", "jobs_h2": "Des patients de 6 mois à 100 ans.",
    "job_labels": ("Consultation", "Durée"),
    "jobs": [
      ("Enfant de 4 ans", "Strabisme dépisté à l'école, rééducation engagée", "Pédiatrie", "45 min"),
      ("Patient de 58 ans", "Glaucome suivi tous les six mois", "Suivi glaucome", "40 min"),
      ("Patiente de 45 ans", "Premières lunettes pour lire", "Renouvellement", "30 min"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Des délais raisonnables.", "Un premier rendez-vous sous quatre semaines pour la plupart des motifs."),
      ("Des urgences prises.", "Des créneaux gardés chaque jour pour les vrais problèmes."),
      ("Des explications claires.", "Vous repartez en sachant ce que vous avez et ce qu'il faut faire."),
      ("Conventionné secteur 1.", "Tarifs de l'Assurance maladie, sans dépassement d'honoraires."),
    ],
    "reviews": [
      ("« Rendez-vous obtenu en trois semaines alors qu'on m'annonçait six mois ailleurs. Consultation sérieuse et bien expliquée. »", "Claire D. · Mont-Saint-Aignan · Renouvellement"),
      ("« Mon fils avait un strabisme. Prise en charge rapide et très douce avec les enfants. »", "Aurélien P. · Rouen · Pédiatrie"),
    ],
    "faq": [
      ("Combien de temps pour avoir un rendez-vous ?", "En moyenne moins de quatre semaines pour un premier rendez-vous, et des créneaux chaque jour pour les urgences."),
      ("Pourquoi voir d'abord l'orthoptiste ?", "L'orthoptiste réalise les mesures et examens préparatoires. L'ophtalmologiste peut ainsi se concentrer sur le diagnostic, ce qui permet de recevoir plus de patients."),
      ("Quand consulter en urgence ?", "Œil rouge et douloureux, baisse brutale de la vue, éclairs lumineux ou voile devant l'œil, choc ou produit dans l'œil : appelez immédiatement, ou le 15 en dehors de nos horaires."),
      ("À quel âge faire examiner les yeux d'un enfant ?", "Des examens sont recommandés dans la petite enfance et avant l'entrée à l'école, et à tout âge si l'enfant plisse les yeux, louche ou se plaint de maux de tête."),
      ("Un diabétique doit-il voir un ophtalmologiste chaque année ?", "Un dépistage régulier de la rétinopathie diabétique est recommandé, en général tous les ans ou tous les deux ans selon votre situation. Nous planifions ce suivi."),
      ("Y a-t-il des dépassements d'honoraires ?", "Non, nos ophtalmologistes sont conventionnés en secteur 1 et appliquent les tarifs de l'Assurance maladie."),
    ],
    "quote_h2": "Demandez un rendez-vous.", "quote_p": "Indiquez le motif. Nous vous rappelons pour vous proposer un créneau.",
    "work_label": "Motif",
    "works": ["Renouvellement de lunettes", "Enfant", "Glaucome", "Diabète", "Urgence", "Vision trouble", "Autre"],
    "extra": ("who", "Pour qui ?", "Ex. : moi, mon fils de 6 ans", True),
    "details_label": "Précisions",
    "details_ph": "Ex. : dernière consultation il y a 3 ans, je vois moins bien de près",
    "success": "Merci {first}. Nous vous rappelons {when} pour vous proposer un créneau.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "ophtalmologie/04-serene-vision",
    "seo_h1": "Sécheresse oculaire et ophtalmologie de l'enfant à Nantes",
    "founder": ("Dr Émilie Garreau", "ophtalmologiste, surface oculaire et pédiatrie"),
    "photo": ("5996649", "an-ophthalmologist-with-a-patient-5996649", "Pavel Danilyuk"),
    "name": "Vision Douce", "tagline": "Yeux secs et enfants · Nantes",
    "schema": "Physician",
    "city": "Nantes", "cp": "44000", "street": "6 quai de la Fosse",
    "phone": "02 61 91 92 05", "tel": "+33261919205",
    "hours": "Du lundi au vendredi, 9 h à 18 h, mercredi pour les enfants", "hours_schema": "Mo-Fr 09:00-18:00",
    "zone_short": "Nantes centre",
    "zone": ["Nantes", "Rezé", "Saint-Herblain", "Orvault", "Saint-Sébastien-sur-Loire", "Vertou", "Loire-Atlantique"],
    "zone_label": "Patients venant de",
    "top3": "Consultations longues, sans hâte",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Sécheresse oculaire et ophtalmologue pour enfants à Nantes | Vision Douce",
    "desc": "Vision Douce à Nantes : consultation spécialisée sécheresse oculaire (yeux secs, brûlures, lumière pulsée) et ophtalmologie de l'enfant (dépistage, strabisme, première paire). Consultations longues.",
    "fonts": ("Gilda Display", "Gilda+Display", "Nunito Sans", "Nunito+Sans:wght@400;600;700"),
    "pal": dict(paper="#F5FAFB", chalk="#E3F0F3", ink="#183642", muted="#56707A", line="#D0E2E7", accent="#8FC6D8", deep="#2C7A92"),
    "layout": "overlay",
    "icon": EYE,
    "eyebrow": "Yeux secs et enfants · Nantes",
    "h1": ("Des yeux qui brûlent, qui piquent, qui pleurent ?", "On cherche enfin la cause, sans vous presser."),
    "lead": "La sécheresse oculaire gâche le quotidien de beaucoup d'adultes, et les enfants ont besoin qu'on prenne le temps. Nos consultations sont longues, les examens expliqués, et les traitements adaptés à chacun.",
    "proofs": ["Consultation dédiée aux yeux secs, bilan complet", "Mercredi réservé aux enfants", "Temps pris pour expliquer, jamais d'examen à la chaîne"],
    "cta": "Prendre rendez-vous", "note": "Délai moyen de trois semaines.",
    "badge": ("45 min", "de consultation<br>pour les yeux secs"),
    "alt": "Un ophtalmologiste examine les yeux d'une petite fille",
    "sit_title": "Vous vous reconnaissez ?",
    "sits": [
      ("Mes yeux brûlent le soir sur écran", "Bilan de sécheresse oculaire et plan de traitement.", "Yeux secs"),
      ("Les gouttes ne suffisent plus", "Examen des glandes des paupières, traitements au cabinet.", "Sécheresse résistante"),
      ("Je ne supporte plus mes lentilles", "Bilan de la surface de l'œil, adaptation ou alternatives.", "Intolérance aux lentilles"),
      ("Mon enfant plisse les yeux ou louche", "Dépistage et prise en charge du strabisme.", "Enfant : strabisme ou vue"),
      ("L'école a signalé un problème de vue", "Bilan complet, première paire si besoin.", "Enfant : dépistage"),
      ("Mon enfant a mal à la tête en lisant", "Recherche d'un trouble de la vision de près.", "Enfant : maux de tête"),
    ],
    "serv_eyebrow": "Nos consultations", "serv_h2": "Deux spécialités qui demandent du temps.",
    "servs": [
      ("Bilan de sécheresse oculaire", "Qualité des larmes, glandes des paupières, surface de l'œil : un bilan complet pour trouver la cause."),
      ("Traitements au cabinet", "Soins des paupières, lumière pulsée ou autres techniques selon votre cas, après explication."),
      ("Lentilles et yeux sensibles", "Conseils et adaptation quand les lentilles deviennent inconfortables."),
      ("Dépistage chez l'enfant", "Examen adapté à l'âge, même avant qu'il sache lire."),
      ("Strabisme", "Diagnostic, rééducation avec l'orthoptiste, suivi."),
      ("Première paire de lunettes", "Ordonnance, conseils aux parents, suivi de l'adaptation."),
    ],
    "steps_h2": "Comment se passe la consultation.",
    "steps": [
      ("Vous prenez rendez-vous", "Motif précisé pour vous réserver le bon temps."),
      ("On écoute", "Vos symptômes, vos habitudes, vos traitements déjà essayés."),
      ("On examine et on explique", "Chaque examen décrit avant d'être fait."),
      ("Plan de traitement", "Étapes claires et rendez-vous de suivi."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Quelques exemples.",
    "job_labels": ("Prise en charge", "Suivi"),
    "jobs": [
      ("Patiente de 42 ans", "Yeux secs depuis des années, gouttes inefficaces", "Soins des paupières", "3 séances"),
      ("Enfant de 5 ans", "Strabisme repéré par la maîtresse", "Rééducation orthoptique", "6 mois"),
      ("Patient de 30 ans", "Intolérance aux lentilles après le télétravail", "Bilan et adaptation", "2 consultations"),
    ],
    "pledges_h2": "Notre façon de travailler.",
    "pledges": [
      ("Du temps.", "Des consultations longues, parce que ces troubles le demandent."),
      ("De la douceur avec les enfants.", "On explique, on joue, on ne force jamais."),
      ("Des explications.", "Chaque examen et chaque traitement sont expliqués avant."),
      ("Des tarifs annoncés.", "Les actes non remboursés sont indiqués avant d'être proposés."),
    ],
    "reviews": [
      ("« Dix ans de gouttes sans résultat. Pour la première fois, on a cherché la cause. Mes yeux ne brûlent plus le soir. »", "Nathalie B. · Nantes · Yeux secs"),
      ("« Ma fille avait peur. Le docteur a pris le temps de jouer avec elle avant l'examen. Merci. »", "Julien C. · Rezé · Enfant"),
    ],
    "faq": [
      ("Qu'est-ce que la sécheresse oculaire ?", "Un trouble du film de larmes qui protège l'œil. Il provoque brûlures, sensation de sable, rougeurs ou paradoxalement des larmoiements. Les écrans, l'âge et certaines maladies le favorisent."),
      ("Les gouttes suffisent-elles ?", "Pas toujours. Si la cause vient des glandes des paupières, d'autres traitements peuvent être plus efficaces. C'est ce que le bilan permet de savoir."),
      ("La lumière pulsée est-elle remboursée ?", "Non, ces traitements au cabinet ne sont généralement pas pris en charge par l'Assurance maladie. Le tarif vous est indiqué avant."),
      ("À quel âge faire examiner les yeux de son enfant ?", "Des examens sont recommandés dans la petite enfance et avant l'entrée à l'école, et à tout âge s'il louche, plisse les yeux ou se plaint de maux de tête."),
      ("Un strabisme se soigne-t-il ?", "Oui, d'autant mieux qu'il est pris en charge tôt : lunettes, rééducation orthoptique, parfois cache ou chirurgie."),
      ("Comment se passe un examen chez un tout-petit ?", "Avec des tests adaptés à l'âge, sous forme de jeux. Pas besoin qu'il sache lire."),
    ],
    "quote_h2": "Prenez rendez-vous.", "quote_p": "Indiquez le motif pour que nous réservions le bon temps de consultation.",
    "work_label": "Motif",
    "works": ["Yeux secs", "Sécheresse résistante", "Intolérance aux lentilles", "Enfant : strabisme ou vue", "Enfant : dépistage", "Enfant : maux de tête", "Autre"],
    "extra": ("who", "Pour qui ?", "Ex. : ma fille de 5 ans", True),
    "details_label": "Précisions",
    "details_ph": "Ex. : yeux qui brûlent le soir depuis deux ans malgré les gouttes",
    "success": "Merci {first}. Nous vous rappelons {when} pour vous proposer un créneau adapté.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "ophtalmologie/05-vizn-lab",
    "seo_h1": "Dépistage de la rétine à Toulouse : DMLA, glaucome, diabète",
    "founder": ("Dr Karim Haddad", "ophtalmologiste, rétine médicale"),
    "photo": ("39647086", "optometrist-conducting-eye-examination-39647086", "Fernando Capetillo"),
    "name": "VIZN", "tagline": "Centre de dépistage de la rétine · Toulouse",
    "schema": "MedicalClinic",
    "city": "Toulouse", "cp": "31400", "street": "48 avenue de Rangueil",
    "phone": "05 36 49 84 27", "tel": "+33536498427",
    "hours": "Du lundi au samedi, 8 h à 19 h", "hours_schema": "Mo-Sa 08:00-19:00",
    "zone_short": "Toulouse Rangueil",
    "zone": ["Toulouse", "Ramonville-Saint-Agne", "Castanet-Tolosan", "Balma", "Blagnac", "Colomiers", "Haute-Garonne"],
    "zone_label": "Patients venant de",
    "top3": "Résultats expliqués le jour même",
    "form": "rdv",
    "legal": LEGAL,
    "title": "Dépistage DMLA, glaucome et rétinopathie diabétique à Toulouse · OCT | VIZN",
    "desc": "VIZN à Toulouse : dépistage et suivi des maladies de la rétine (DMLA, glaucome, rétinopathie diabétique) par OCT et rétinographie. Examens rapides, résultats expliqués le jour même par un ophtalmologiste.",
    "fonts": ("Chakra Petch", "Chakra+Petch:wght@600;700", "IBM Plex Sans", "IBM+Plex+Sans:wght@400;500;600"),
    "pal": dict(paper="#F4F7FA", chalk="#E2EAF2", ink="#05070D", muted="#4F5968", line="#D0DAE5", accent="#33CFFF", deep="#0079A8"),
    "layout": "split-right",
    "icon": EYE,
    "eyebrow": "Dépistage de la rétine · Toulouse",
    "h1": ("Voir les maladies de l'œil avant qu'elles ne se voient,", "et comprendre vos résultats le jour même."),
    "lead": "DMLA, glaucome, rétinopathie diabétique : ces maladies avancent souvent sans symptôme. Un examen OCT de quelques minutes, sans contact avec l'œil, permet de les détecter tôt. Un ophtalmologiste vous explique les images à la fin du rendez-vous.",
    "proofs": ["Examens sans contact, en quelques minutes", "Résultats expliqués le jour même", "Suivi comparé d'une année sur l'autre"],
    "cta": "Réserver un dépistage", "note": "Si vous êtes diabétique, apportez votre dernier bilan.",
    "badge": ("Jour J", "résultats expliqués<br>avant de repartir"),
    "alt": "Une patiente passe un examen de la rétine sur un appareil d'imagerie",
    "sit_title": "Êtes-vous concerné ?",
    "sits": [
      ("Je suis diabétique", "Dépistage de la rétinopathie diabétique, recommandé régulièrement.", "Diabète"),
      ("J'ai plus de 55 ans", "Dépistage de la DMLA, surtout si un proche en est atteint.", "Dépistage DMLA"),
      ("Il y a du glaucome dans ma famille", "Mesure de la pression, OCT du nerf optique, champ visuel.", "Glaucome familial"),
      ("Les lignes droites me paraissent déformées", "Signe possible de DMLA : consultez vite.", "Vision déformée"),
      ("Mon ophtalmo m'a prescrit un OCT", "Examen réalisé rapidement, résultats transmis.", "OCT prescrit"),
      ("Je suis très myope", "Surveillance de la rétine, plus fragile chez les forts myopes.", "Forte myopie"),
    ],
    "serv_eyebrow": "Nos examens", "serv_h2": "Des examens précis, expliqués en français courant.",
    "servs": [
      ("OCT", "Coupe en haute définition de la rétine et du nerf optique, sans contact, en quelques minutes."),
      ("Rétinographie", "Photographie du fond d'œil, souvent sans dilatation de la pupille."),
      ("Champ visuel", "Mesure de l'étendue de la vision, indispensable au suivi du glaucome."),
      ("Dépistage diabétique", "Recherche des premières lésions de rétinopathie, compte rendu transmis à votre médecin."),
      ("Suivi DMLA", "Contrôles réguliers et orientation rapide vers un traitement si besoin."),
      ("Comparaison dans le temps", "Vos images comparées à celles des années précédentes pour détecter la moindre évolution."),
    ],
    "steps_h2": "Un dépistage en moins d'une heure.",
    "steps": [
      ("Vous réservez", "Motif et antécédents indiqués pour préparer l'examen."),
      ("Examens", "OCT, rétinographie ou champ visuel : sans contact et sans douleur."),
      ("Explication", "L'ophtalmologiste vous montre les images et les commente."),
      ("Compte rendu", "Transmis à vous et à votre médecin, prochain contrôle planifié."),
    ],
    "jobs_eyebrow": "Parcours de soin", "jobs_h2": "Quelques exemples.",
    "job_labels": ("Examen", "Suivi"),
    "jobs": [
      ("Patient diabétique, 61 ans", "Premières lésions détectées, traitement précoce", "Rétinographie et OCT", "Tous les 6 mois"),
      ("Patiente de 67 ans", "Mère atteinte de DMLA, rétine saine à ce jour", "OCT maculaire", "Annuel"),
      ("Patient de 50 ans", "Antécédent familial de glaucome, pression normale", "OCT et champ visuel", "Tous les 2 ans"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Comprendre vos images.", "Pas de compte rendu incompréhensible : on vous explique."),
      ("Un suivi comparatif.", "Vos examens sont conservés pour mesurer toute évolution."),
      ("Un lien avec vos médecins.", "Compte rendu transmis à votre ophtalmologiste et à votre médecin traitant."),
      ("Des tarifs clairs.", "Examens pris en charge selon la nomenclature, dépassements annoncés s'il y en a."),
    ],
    "reviews": [
      ("« Diabétique depuis 15 ans, je n'avais jamais compris mes examens. Là, on m'a montré ma rétine et tout expliqué. »", "Patrick L. · Toulouse · Dépistage diabétique"),
      ("« Examen rapide, sans gouttes, résultats le jour même. Rassurée pour un an. »", "Françoise M. · Balma · Dépistage DMLA"),
    ],
    "faq": [
      ("Qu'est-ce qu'un OCT ?", "Un examen d'imagerie qui réalise des coupes très fines de la rétine et du nerf optique, sans contact avec l'œil. Il dure quelques minutes et n'est pas douloureux."),
      ("Faut-il dilater les pupilles ?", "Pas toujours. Certains examens se font sans dilatation. Si elle est nécessaire, prévoyez de ne pas conduire pendant quelques heures."),
      ("Qui devrait faire un dépistage de la DMLA ?", "Les personnes de plus de 55 ans, surtout en cas d'antécédent familial, de tabagisme ou de vision déformée. Un contrôle régulier est conseillé."),
      ("Pourquoi les diabétiques doivent-ils surveiller leur rétine ?", "Le diabète peut abîmer les petits vaisseaux de la rétine sans symptôme au début. Un dépistage régulier permet de traiter tôt."),
      ("Le glaucome donne-t-il des symptômes ?", "Rarement au début : il réduit la vision périphérique progressivement. D'où l'intérêt du dépistage en cas d'antécédent familial ou après 40 ans."),
      ("Les examens sont-ils remboursés ?", "Les examens prescrits sont pris en charge par l'Assurance maladie selon la nomenclature. Nous vous indiquons le tarif avant."),
    ],
    "quote_h2": "Réservez votre dépistage.", "quote_p": "Indiquez le motif et vos antécédents principaux. Nous vous rappelons pour fixer l'examen.",
    "work_label": "Motif",
    "works": ["Diabète", "Dépistage DMLA", "Glaucome familial", "Vision déformée", "OCT prescrit", "Forte myopie", "Autre"],
    "extra": ("prescription", "Avez-vous une prescription ?", "Ex. : oui, de mon ophtalmologiste", True),
    "details_label": "Précisions",
    "details_ph": "Ex. : diabétique de type 2, dernier fond d'œil il y a deux ans",
    "success": "Merci {first}. Nous vous rappelons {when} pour fixer votre examen.",
    "success_end": "",
    "nav": ["Nos examens", "Votre rendez-vous", "Parcours", "Questions"],
  },
]
