"""Paysagistes : trois marques complémentaires de Sève & Pierre (entretien, élagage, jardin sec)."""

LEAF = '<path class="blade" d="M26 5C13 5 6 12 6 21c0 2 .6 3.8 1.6 5.2L5 28.8 6.4 30.2l2.6-2.6C10.4 28.4 12 29 14 29c9 0 14-7 14-20 0-1.5-.7-3-2-4z"/>'
TREE = '<path class="blade" d="M16 3c-5 0-9 4-9 9 0 1 .2 2 .5 3C5.4 16.3 4 18.4 4 21c0 3.9 3.1 7 7 7h10c3.9 0 7-3.1 7-7 0-2.6-1.4-4.7-3.5-6 .3-1 .5-2 .5-3 0-5-4-9-9-9z"/><path d="M16 14v16" stroke="currentColor" stroke-width="2.6" stroke-linecap="round"/>'
SPRIG = '<path d="M16 29V9" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/><path class="blade" d="M16 9c-3-1-5-3-5-6 3 0 5 2 5 6zm0 0c3-1 5-3 5-6-3 0-5 2-5 6zM16 16c-3-1-6-3-6-6 3 0 6 2 6 6zm0 0c3-1 6-3 6-6-3 0-6 2-6 6zM16 23c-3-1-6-3-6-6 3 0 6 2 6 6zm0 0c3-1 6-3 6-6-3 0-6 2-6 6z"/>'

SITES = [
  {
    "dir": "paysagistes/02-allees-vertes",
    "seo_h1": "Entretien de jardin à Orléans : tonte, taille de haies, 50 % de crédit d'impôt",
    "founder": ("Thibault Lambert", "gérant, jardinier paysagiste"),
    "photo": ("12087398", "a-man-mowing-the-green-lawn-12087398", "Vaan Photos"),
    "name": "Allées Vertes", "tagline": "Entretien de jardins · Orléans",
    "schema": "HomeAndConstructionBusiness",
    "city": "Orléans", "cp": "45000", "street": "19 rue du Faubourg Bannier",
    "phone": "02 61 91 63 72", "tel": "+33261916372",
    "hours": "Du lundi au samedi, 8 h à 18 h", "hours_schema": "Mo-Sa 08:00-18:00",
    "zone_short": "Orléans et 25 km autour",
    "zone": ["Orléans", "Olivet", "Saint-Jean-de-Braye", "Fleury-les-Aubrais", "Saint-Jean-le-Blanc", "Saran", "La Chapelle-Saint-Mesmin", "Chécy", "Saint-Cyr-en-Val"],
    "top3": "Vous ne payez que 50 %, crédit d'impôt avancé",
    "title": "Entretien de jardin à Orléans · Tonte, taille de haies, crédit d'impôt 50 % | Allées Vertes",
    "desc": "Allées Vertes entretient les jardins des particuliers à Orléans et alentour : tonte, taille de haies, désherbage, ramassage des feuilles. Crédit d'impôt de 50 % déduit directement de la facture grâce à l'avance immédiate.",
    "fonts": ("Outfit", "Outfit:wght@600;700;800", "Nunito Sans", "Nunito+Sans:wght@400;600;700"),
    "pal": dict(paper="#F6F9F2", chalk="#E7F0DD", ink="#1F3A1C", muted="#5A6A55", line="#D6E2CA", accent="#9ACD4E", deep="#4A7A1A"),
    "layout": "split-right",
    "icon": LEAF,
    "eyebrow": "Entretien de jardins · Orléans",
    "h1": ("Un jardin impeccable toute l'année,", "pour la moitié du prix grâce au crédit d'impôt."),
    "lead": "Tonte, taille des haies, désherbage, feuilles mortes : le même jardinier passe chez vous aux dates convenues. Avec l'avance immédiate du crédit d'impôt, vous ne réglez que 50 % de la facture, sans attendre votre déclaration.",
    "proofs": ["Vous ne payez que 50 % grâce à l'avance immédiate", "Le même jardinier à chaque passage", "Déchets verts évacués, jardin laissé propre"],
    "cta": "Demander un devis d'entretien", "note": "Devis gratuit après une visite de 20 minutes.",
    "badge": ("-50 %", "déduits directement<br>de chaque facture"),
    "alt": "Un jardinier tond une pelouse verte entourée d'arbres",
    "sit_title": "Qu'est-ce qui vous ressemble ?",
    "sits": [
      ("Je n'ai plus le temps de tondre", "Tonte tous les 15 jours au printemps et en été, espacée ensuite.", "Tonte régulière"),
      ("Mes haies débordent sur la rue", "Taille deux fois par an, déchets évacués.", "Taille de haies"),
      ("Mon parent âgé ne peut plus s'en occuper", "Passages réguliers, factures adressées à qui vous voulez.", "Jardin d'un proche âgé"),
      ("Je pars longtemps ou c'est une maison secondaire", "Entretien pendant votre absence, photos après chaque passage.", "Maison inoccupée"),
      ("Je vends ou je loue ma maison", "Remise en état du jardin avant les visites.", "Remise en état"),
      ("Je veux juste un coup de propre ponctuel", "Nettoyage de printemps ou d'automne en une journée.", "Nettoyage ponctuel"),
    ],
    "serv_eyebrow": "Nos prestations", "serv_h2": "Tout l'entretien courant du jardin, sans que vous ayez à y penser.",
    "servs": [
      ("Tonte et bordures", "Tonte à la bonne hauteur selon la saison, finitions au coupe-bordure, pelouse ramassée ou mulchée."),
      ("Taille de haies et d'arbustes", "Deux tailles par an en général, au bon moment pour chaque espèce."),
      ("Désherbage", "Allées, massifs et terrasses désherbés à la main ou mécaniquement, sans produits chimiques."),
      ("Feuilles et déchets verts", "Ramassage à l'automne et évacuation en déchetterie ou compostage."),
      ("Contrat annuel", "Un calendrier de passages établi avec vous, un prix fixe par passage."),
      ("Petits travaux", "Plantation de quelques arbustes, entretien des massifs, scarification de la pelouse."),
    ],
    "steps_h2": "Un jardin entretenu, sans y passer vos week-ends.",
    "steps": [
      ("Visite de 20 minutes", "On fait le tour du jardin et on note ce que vous attendez."),
      ("Devis et calendrier", "Prix par passage, calendrier de l'année, part payée après crédit d'impôt."),
      ("Passages réguliers", "Le même jardinier aux dates convenues, même en votre absence."),
      ("Facture à 50 %", "L'avance immédiate déduit le crédit d'impôt de chaque facture."),
    ],
    "job_labels": ("Prestation", "Fréquence"),
    "jobs": [
      ("Olivet · Pavillon, 600 m²", "Tonte, haies et feuilles toute l'année", "Contrat annuel", "2 passages par mois"),
      ("Orléans · Maison d'une dame de 84 ans", "Jardin entretenu, factures envoyées à sa fille", "Jardin d'un proche", "1 passage par mois"),
      ("Saint-Jean-de-Braye · Maison en vente", "Jardin remis en état avant les visites", "Remise en état", "1 journée"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Le même jardinier.", "Il connaît votre jardin et vos préférences."),
      ("Des dates tenues.", "En cas de pluie, le passage est reporté et vous êtes prévenu."),
      ("Zéro pesticide.", "Désherbage manuel ou mécanique, respect du jardin et des animaux."),
      ("Des démarches simples.", "Avance immédiate du crédit d'impôt et attestation fiscale annuelle."),
    ],
    "reviews": [
      ("« Ma mère ne pouvait plus s'occuper de son jardin. Le même jardinier passe chaque mois, et je reçois les factures. »", "Sandrine P. · Orléans · Jardin d'un proche"),
      ("« On ne paie que la moitié directement sur la facture. Et le jardin n'a jamais été aussi net. »", "Laurent et Anne G. · Olivet · Contrat annuel"),
    ],
    "faq": [
      ("L'entretien du jardin donne-t-il droit au crédit d'impôt ?", "Oui, les petits travaux de jardinage chez un particulier (tonte, taille, désherbage, ramassage des feuilles) ouvrent droit à un crédit d'impôt de 50 %, dans la limite de 5 000 € de dépenses par an et par foyer."),
      ("Qu'est-ce que l'avance immédiate du crédit d'impôt ?", "Un dispositif qui déduit directement le crédit d'impôt de votre facture : vous ne payez que 50 % au lieu d'attendre le remboursement l'année suivante. Il suffit d'activer le service lors de votre premier règlement."),
      ("Combien de passages par an faut-il prévoir ?", "Pour un jardin classique, environ deux tontes par mois d'avril à octobre, deux tailles de haies et un ramassage de feuilles à l'automne. Le calendrier est adapté à votre jardin."),
      ("L'élagage des grands arbres est-il compris ?", "Non. Les travaux d'élagage en hauteur et d'abattage ne relèvent pas des petits travaux de jardinage et n'ouvrent pas droit au crédit d'impôt. Nous pouvons vous orienter vers un élagueur."),
      ("Faut-il être présent lors des passages ?", "Non, un accès au jardin suffit. Vous recevez un message après chaque passage."),
      ("Que deviennent les déchets verts ?", "Ils sont évacués en déchetterie ou valorisés en compost. Leur évacuation est comprise dans le prix du passage."),
    ],
    "quote_h2": "Parlez-nous de votre jardin.", "quote_p": "Quelques mots sur votre jardin. On vous rappelle pour fixer une visite rapide et vous remettre un devis.",
    "work_label": "Votre besoin",
    "works": ["Tonte régulière", "Taille de haies", "Jardin d'un proche âgé", "Maison inoccupée", "Remise en état", "Nettoyage ponctuel", "Autre"],
    "extra": ("surface", "Surface du jardin", "Ex. : 600 m²", True),
    "details_ph": "Ex. : pelouse de 400 m², 30 mètres de haies de laurier, deux grands arbres",
    "success_end": "fixer la visite de votre jardin",
    "nav": ["Nos prestations", "Comment ça se passe", "Jardins", "Questions"],
  },
  {
    "dir": "paysagistes/03-cime-racine",
    "seo_h1": "Élagage et abattage d'arbres dans le Morbihan : élagueurs grimpeurs à Vannes",
    "founder": ("Gaël Le Floch", "élagueur grimpeur, certificat de spécialisation taille et soins des arbres"),
    "photo": ("2310483", "man-in-blue-shirt-siting-on-tree-branch-wearing-safety-harness-holding-ropes-on-left-hand-and-chainsaw-in-right-hand-2310483", "JimBear"),
    "name": "Cime & Racine", "tagline": "Élagueurs grimpeurs · Vannes",
    "schema": "HomeAndConstructionBusiness",
    "city": "Vannes", "cp": "56000", "street": "12 rue du Commerce",
    "phone": "02 61 91 38 65", "tel": "+33261913865",
    "hours": "Du lundi au samedi, 8 h à 18 h, urgences après tempête", "hours_schema": "Mo-Sa 08:00-18:00",
    "zone_short": "Morbihan",
    "zone": ["Vannes", "Séné", "Arradon", "Saint-Avé", "Theix-Noyalo", "Sarzeau", "Auray", "Plescop", "Golfe du Morbihan"],
    "top3": "Intervention d'urgence après tempête",
    "title": "Élagage et abattage d'arbres à Vannes · Élagueur grimpeur, urgence tempête | Cime & Racine",
    "desc": "Cime & Racine, élagueurs grimpeurs dans le Morbihan : élagage, abattage délicat par démontage, dessouchage, broyage des branches, intervention d'urgence après tempête. Devis gratuit, assurance professionnelle.",
    "fonts": ("Big Shoulders Display", "Big+Shoulders+Display:wght@700;800", "Barlow", "Barlow:wght@400;500;600"),
    "pal": dict(paper="#F5F6F1", chalk="#E6E9DE", ink="#16241C", muted="#56625A", line="#D5DBCC", accent="#E0A43A", deep="#8E5D0C"),
    "layout": "overlay",
    "icon": TREE,
    "eyebrow": "Élagueurs grimpeurs · Morbihan",
    "h1": ("Un arbre trop grand, trop près de la maison ?", "On le taille ou on le démonte, branche par branche, sans rien abîmer."),
    "lead": "Nos élagueurs grimpent dans l'arbre, encordés, et retiennent chaque branche au cordage : même au-dessus d'une toiture ou d'une véranda, rien ne tombe au hasard. Élagage, abattage, dessouchage, et intervention rapide après une tempête.",
    "proofs": ["Élagueurs grimpeurs certifiés, assurés", "Abattage par démontage au-dessus des toits et des clôtures", "Branches broyées ou bois coupé à la longueur de votre choix"],
    "cta": "Demander un devis", "note": "Arbre tombé ou menaçant après une tempête : appelez directement.",
    "badge": ("48 h", "pour sécuriser un arbre<br>dangereux après tempête"),
    "alt": "Un élagueur encordé coupe une branche à la tronçonneuse, assis dans un arbre",
    "sit_title": "Quel est le problème avec votre arbre ?",
    "sits": [
      ("Mon arbre fait trop d'ombre ou touche la maison", "Élagage raisonné qui éclaircit sans mutiler l'arbre.", "Élagage"),
      ("Je dois abattre un arbre près de la maison", "Démontage par tronçons retenus au cordage.", "Abattage par démontage"),
      ("Un arbre est tombé ou penche après la tempête", "Mise en sécurité rapide, puis évacuation.", "Urgence tempête"),
      ("Mon voisin se plaint des branches qui dépassent", "Taille en limite de propriété, dans les règles.", "Branches chez le voisin"),
      ("Il reste une souche au milieu du jardin", "Rognage de souche à la machine, terrain nivelé.", "Dessouchage"),
      ("Je veux savoir si mon arbre est malade ou dangereux", "Diagnostic visuel et conseil avant toute coupe.", "Diagnostic d'arbre"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "Tout le travail en hauteur, fait par des grimpeurs formés.",
    "servs": [
      ("Élagage raisonné", "Taille qui respecte la forme et la santé de l'arbre, sans étêtage brutal."),
      ("Abattage par démontage", "Découpe par tronçons retenus au cordage, pour les arbres proches des bâtiments."),
      ("Abattage direct", "Quand l'espace le permet, abattage dirigé au sol, rapide et sûr."),
      ("Dessouchage", "Rognage de souche à la machine, sciure laissée sur place ou évacuée."),
      ("Urgence tempête", "Mise en sécurité des arbres cassés ou déracinés, dossier photo pour l'assurance."),
      ("Broyage et bois", "Branches broyées en paillage, bois coupé en bûches si vous le souhaitez."),
    ],
    "steps_h2": "Un chantier en hauteur, préparé au sol.",
    "steps": [
      ("Vous nous décrivez l'arbre", "Espèce si vous la connaissez, hauteur, proximité de la maison, photos."),
      ("Visite et diagnostic", "On observe l'arbre, l'accès, les risques, et on vous conseille."),
      ("Devis détaillé", "Technique, évacuation ou non des branches, bois conservé ou pas."),
      ("Intervention", "Périmètre balisé, travail encordé, chantier nettoyé à la fin."),
    ],
    "job_labels": ("Intervention", "Durée"),
    "jobs": [
      ("Arradon · Cèdre de 22 m", "Démonté au-dessus d'une véranda, sans une tuile cassée", "Abattage par démontage", "1 jour"),
      ("Séné · Après la tempête", "Pin tombé sur une clôture, mis en sécurité en 24 h", "Urgence tempête", "4 h"),
      ("Vannes · Chêne centenaire", "Élagage raisonné pour dégager la toiture", "Élagage", "1 jour"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Respecter l'arbre.", "On ne coupe que ce qui doit l'être. Si un arbre sain peut rester, on vous le dit."),
      ("La sécurité d'abord.", "Grimpeurs formés, périmètre balisé, matériel contrôlé."),
      ("Des garanties.", "Assurance responsabilité civile professionnelle, attestation fournie."),
      ("Un jardin rendu propre.", "Branches, sciure et feuilles évacuées ou valorisées selon votre choix."),
    ],
    "reviews": [
      ("« Un cèdre énorme au-dessus de la véranda. Ils l'ont démonté morceau par morceau, rien n'a été touché. Impressionnant. »", "Yves et Martine L. · Arradon · Abattage"),
      ("« Arbre tombé sur la clôture un dimanche de tempête. Mise en sécurité le lundi matin et dossier pour l'assurance. »", "Nolwenn K. · Séné · Urgence"),
    ],
    "faq": [
      ("Faut-il une autorisation pour abattre un arbre ?", "Souvent non dans un jardin privé, mais une déclaration ou une autorisation peut être exigée si l'arbre est protégé par le plan local d'urbanisme, situé dans un espace boisé classé ou en secteur protégé. Nous vérifions avec vous auprès de la mairie."),
      ("Mon voisin peut-il m'obliger à couper mes branches ?", "Oui, le Code civil permet à un voisin d'exiger que les branches qui dépassent sur son terrain soient coupées. Il ne peut pas les couper lui-même sans votre accord. Nous intervenons en limite de propriété dans les règles."),
      ("Combien coûte un élagage ou un abattage ?", "Le prix dépend de la hauteur de l'arbre, de son accessibilité, de la technique (démontage ou abattage direct) et de l'évacuation des branches. Le devis est gratuit après visite."),
      ("Quelle est la meilleure période pour élaguer ?", "En général hors période de montée de sève et hors nidification des oiseaux, souvent en fin d'automne et en hiver. En cas de danger, on intervient toute l'année."),
      ("L'élagage donne-t-il droit au crédit d'impôt ?", "Non. Le crédit d'impôt pour les services à la personne ne concerne que les petits travaux de jardinage, pas l'élagage en hauteur ni l'abattage."),
      ("Que faire après une tempête ?", "Éloignez-vous de l'arbre, ne tentez pas de le couper vous-même, prenez des photos pour l'assurance et appelez-nous. Nous sécurisons d'abord, puis nous évacuons."),
    ],
    "quote_h2": "Parlez-nous de votre arbre.", "quote_p": "Décrivez l'arbre et son emplacement. On vous rappelle pour fixer la visite, gratuite et sans engagement.",
    "work_label": "Type d'intervention",
    "works": ["Élagage", "Abattage par démontage", "Urgence tempête", "Branches chez le voisin", "Dessouchage", "Diagnostic d'arbre", "Autre"],
    "extra": ("tree", "Espèce et hauteur approximative", "Ex. : chêne, environ 15 m", True),
    "details_ph": "Ex. : pin à 3 m de la maison, branches au-dessus du toit",
    "success_end": "fixer la visite de votre arbre",
    "nav": ["Nos interventions", "Comment ça se passe", "Chantiers", "Questions"],
  },
  {
    "dir": "paysagistes/04-jardins-de-garrigue",
    "seo_h1": "Paysagiste à Avignon : jardins méditerranéens économes en eau",
    "founder": ("Lucie Fabre", "paysagiste, spécialiste des jardins secs"),
    "photo": ("8279819", "woman-cutting-flowers-in-garden-8279819", "RDNE"),
    "name": "Jardins de Garrigue", "tagline": "Jardins secs · Avignon et Vaucluse",
    "schema": "HomeAndConstructionBusiness",
    "city": "Avignon", "cp": "84000", "street": "7 rue des Teinturiers",
    "phone": "04 65 71 81 44", "tel": "+33465718144",
    "hours": "Du lundi au vendredi, 8 h à 18 h", "hours_schema": "Mo-Fr 08:00-18:00",
    "zone_short": "Avignon et Vaucluse",
    "zone": ["Avignon", "Le Pontet", "Villeneuve-lès-Avignon", "L'Isle-sur-la-Sorgue", "Cavaillon", "Carpentras", "Gordes", "Saint-Rémy-de-Provence", "Luberon"],
    "top3": "Jusqu'à peu ou pas d'arrosage une fois installé",
    "title": "Paysagiste Avignon · Jardin méditerranéen sans arrosage, jardin sec | Jardins de Garrigue",
    "desc": "Jardins de Garrigue crée des jardins méditerranéens économes en eau à Avignon et dans le Vaucluse : plantes de garrigue, remplacement du gazon, goutte-à-goutte, récupération d'eau de pluie, entretien.",
    "fonts": ("Gloock", "Gloock", "Figtree", "Figtree:wght@400;500;600"),
    "pal": dict(paper="#FBF7EF", chalk="#F1E7D6", ink="#2F3A26", muted="#646A58", line="#E4D9C4", accent="#D9895A", deep="#9A4A1E"),
    "layout": "split-left",
    "icon": SPRIG,
    "eyebrow": "Jardins secs · Vaucluse",
    "h1": ("Un jardin beau en plein mois d'août,", "même quand l'arrosage est interdit."),
    "lead": "Les étés sont plus secs et les restrictions d'eau plus fréquentes. Nous créons des jardins de garrigue qui aiment la chaleur : lavandes, cistes, oliviers, graminées, paillage minéral. Une fois bien installés, ils se contentent de très peu d'eau.",
    "proofs": ["Plantes méditerranéennes adaptées à votre sol", "Gazon remplacé par des couvre-sols qui restent verts", "Goutte-à-goutte et récupération d'eau de pluie"],
    "cta": "Repenser mon jardin", "note": "Visite et conseil gratuits. Meilleure saison pour planter : l'automne.",
    "badge": ("Automne", "la saison idéale<br>pour planter au sec"),
    "alt": "Une jardinière taille des tiges de lavande dans un jardin ensoleillé",
    "sit_title": "Où en est votre jardin ?",
    "sits": [
      ("Ma pelouse grille tous les étés", "Remplacement par des couvre-sols et des graminées qui restent beaux sans eau.", "Remplacer le gazon"),
      ("Je veux un jardin qui supporte les restrictions d'eau", "Jardin sec complet : plantes, paillage, arrosage de démarrage.", "Jardin sec complet"),
      ("Je rêve d'un jardin provençal", "Oliviers, lavandes, cyprès, murets de pierre sèche.", "Jardin provençal"),
      ("Je veux récupérer l'eau de pluie", "Cuves enterrées ou hors sol, reliées à l'arrosage.", "Récupération d'eau de pluie"),
      ("J'ai un mas ou une maison secondaire", "Jardin conçu pour se passer de vous plusieurs semaines.", "Maison secondaire"),
      ("Je veux juste de bons conseils", "Visite-conseil : quoi planter, où, et quand.", "Visite-conseil"),
    ],
    "serv_eyebrow": "Nos prestations", "serv_h2": "Des jardins qui aiment le soleil, et qui demandent peu d'eau.",
    "servs": [
      ("Conception de jardin sec", "Plan de plantation selon votre sol, l'exposition, le mistral et le temps que vous voulez y consacrer."),
      ("Remplacement du gazon", "Couvre-sols, thyms, graminées et prairies sèches à la place d'une pelouse gourmande en eau."),
      ("Plantes de garrigue", "Lavandes, cistes, romarins, sauges, oliviers, choisis en pépinière pour leur robustesse."),
      ("Paillage minéral et végétal", "Gravier, pierre locale ou broyat pour garder l'humidité et limiter les herbes."),
      ("Arrosage économe", "Goutte-à-goutte programmé pour l'installation, puis réduit ou coupé."),
      ("Récupération d'eau de pluie", "Cuves enterrées ou apparentes, raccordées au réseau d'arrosage."),
    ],
    "steps_h2": "De la visite au jardin qui se débrouille seul.",
    "steps": [
      ("Visite du jardin", "Sol, exposition, vent, vos envies et votre temps disponible."),
      ("Plan de plantation", "Liste des plantes, visuels, période idéale de plantation."),
      ("Plantation d'automne", "Préparation du sol, plantation, paillage, arrosage de démarrage."),
      ("Suivi la première année", "Deux visites pour ajuster l'arrosage et remplacer ce qui n'a pas pris."),
    ],
    "job_labels": ("Travaux", "Durée"),
    "jobs": [
      ("Villeneuve-lès-Avignon · Villa", "300 m² de pelouse remplacés par un jardin de graminées et de thyms", "Remplacement du gazon", "1 semaine"),
      ("Gordes · Mas", "Jardin sec autour de la piscine, arrosé seulement la première année", "Jardin sec complet", "3 semaines"),
      ("L'Isle-sur-la-Sorgue · Maison de village", "Cour plantée de lavandes et d'un olivier, cuve de 3 000 litres", "Jardin provençal", "5 jours"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Des plantes qui tiennent.", "Choisies pour votre sol et votre climat, garanties un an après plantation."),
      ("Moins d'eau, vraiment.", "Un jardin conçu pour se passer d'arrosage une fois installé, sauf besoin particulier."),
      ("Des plantes locales.", "Achetées dans des pépinières de la région, adaptées au mistral et au calcaire."),
      ("Un suivi la première année.", "Deux visites comprises pour ajuster et remplacer si besoin."),
    ],
    "reviews": [
      ("« Plus de pelouse jaune en août. Le jardin de graminées est magnifique et on n'arrose presque plus. »", "Frédéric et Anne S. · Villeneuve-lès-Avignon · Remplacement du gazon"),
      ("« Notre mas reste inoccupé des semaines. Le jardin sec autour de la piscine se débrouille très bien sans nous. »", "Famille V. · Gordes · Jardin sec"),
    ],
    "faq": [
      ("Qu'est-ce qu'un jardin sec ?", "Un jardin composé de plantes adaptées à la chaleur et à la sécheresse, comme celles de la garrigue. Une fois bien installées, souvent après un ou deux étés, elles n'ont besoin que de très peu d'arrosage, voire aucun."),
      ("Quand planter un jardin méditerranéen ?", "L'automne est la meilleure saison : les pluies aident les racines à s'installer avant l'été. Le début du printemps est possible, avec un arrosage de démarrage plus suivi."),
      ("Par quoi remplacer une pelouse qui grille ?", "Par des couvre-sols (thyms, achillées, zoysia), des prairies sèches ou des graminées, ou par du paillage minéral avec des massifs. Nous vous conseillons selon l'usage : jeux d'enfants, passage, décor."),
      ("Peut-on arroser pendant les restrictions d'eau ?", "Les règles dépendent de l'arrêté préfectoral en vigueur et du niveau d'alerte. L'arrosage au goutte-à-goutte est parfois autorisé à certaines heures. Un jardin sec limite fortement ce souci."),
      ("Un jardin sec demande-t-il de l'entretien ?", "Moins qu'un jardin classique : une taille légère des lavandes et des cistes après floraison, et un désherbage limité grâce au paillage."),
      ("La récupération d'eau de pluie vaut-elle le coup ?", "Oui, surtout pour arroser les jeunes plantations et le potager. Une cuve se remplit avec les pluies d'automne et de printemps."),
    ],
    "quote_h2": "Parlez-nous de votre jardin.", "quote_p": "Surface, exposition, ce que vous aimeriez. On vous rappelle pour fixer une visite-conseil gratuite.",
    "work_label": "Votre projet",
    "works": ["Remplacer le gazon", "Jardin sec complet", "Jardin provençal", "Récupération d'eau de pluie", "Maison secondaire", "Visite-conseil", "Autre"],
    "extra": ("surface", "Surface du jardin", "Ex. : 800 m²", True),
    "details_ph": "Ex. : pelouse de 300 m² toujours jaune l'été, sol calcaire, plein sud",
    "success_end": "fixer une visite-conseil dans votre jardin",
    "nav": ["Nos prestations", "Comment ça se passe", "Réalisations", "Questions"],
  },
]
