"""Plomberie : 5 marques refaites au format orienté client (septembre 2026)."""

DROP = '<path class="blade" d="M16 4c5 7 8 11 8 15a8 8 0 0 1-16 0c0-4 3-8 8-15z"/>'
WRENCH = '<path d="M21 5a6 6 0 0 0-6 8L6 22l4 4 9-9a6 6 0 0 0 8-6l-4 1-3-3z" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linejoin="round"/><circle class="blade" cx="8" cy="24" r="2"/>'

NAV = ["Nos interventions", "Comment ça se passe", "Chantiers", "Questions"]

SITES = [
  {
    "dir": "plomberie/01-aqua-lumiere",
    "seo_h1": "Rénovation de salles de bains et plombier à Paris 16e",
    "founder": ("Olivier Marchal", "fondateur et chef de chantier"),
    "photo": ("31525748", "luxurious-marble-bathroom-with-modern-fixtures-31525748", "pu-ca-adryan"),
    "name": "Aqua Lumière", "tagline": "Salles de bains et plomberie · Paris Ouest",
    "schema": "Plumber",
    "city": "Paris", "cp": "75016", "street": "21 rue de la Pompe",
    "phone": "01 99 00 41 26", "tel": "+33199004126",
    "hours": "Du lundi au vendredi, 8 h à 19 h", "hours_schema": "Mo-Fr 08:00-19:00",
    "zone_short": "Paris Ouest et Hauts-de-Seine",
    "zone": ["Paris 7e, 8e, 15e, 16e, 17e", "Neuilly-sur-Seine", "Boulogne-Billancourt", "Levallois-Perret", "Saint-Cloud", "Issy-les-Moulineaux", "Rueil-Malmaison"],
    "top3": "Chef de chantier unique",
    "title": "Rénovation de salle de bains et plombier à Paris 16e | Aqua Lumière",
    "desc": "Rénovation de salles de bains haut de gamme et plomberie à Paris Ouest et Neuilly : douches à l'italienne, baignoires, robinetterie de designer, dépannage discret. Visite et devis détaillé gratuits.",
    "fonts": ("Cormorant Garamond", "Cormorant+Garamond:ital,wght@0,600;0,700;1,600", "Jost", "Jost:wght@400;500;600"),
    "pal": dict(paper="#FAF8F4", chalk="#EFEAE0", ink="#0F2A33", muted="#566A70", line="#E0D9CB", accent="#C8A24B", deep="#8A6A1E"),
    "layout": "split-right",
    "icon": DROP,
    "eyebrow": "Salles de bains et plomberie · Paris Ouest",
    "h1": ("Votre nouvelle salle de bains,", "livrée à la date promise, sans que vous ayez à gérer le chantier."),
    "lead": "Douche à l'italienne, baignoire îlot, marbre, robinetterie de designer : nous concevons et réalisons votre salle de bains de A à Z, avec un seul interlocuteur. Et pour une fuite ou un dépannage, un plombier se déplace dans la journée.",
    "proofs": ["Visite et plan 3D offerts", "Un chef de chantier unique, du devis à la réception", "Appartement protégé, parties communes respectées"],
    "cta": "Parler de ma salle de bains", "note": "Rappel sous 24 h. Dépannage dans la journée pour nos clients.",
    "badge": ("3 sem.", "pour une salle de bains<br>complète en moyenne"),
    "alt": "Une salle de bains en marbre avec douche vitrée et robinetterie moderne",
    "sit_title": "Qu'est-ce qui vous amène ?",
    "sits": [
      ("Je veux refaire entièrement ma salle de bains", "Conception, dépose, plomberie, carrelage, finitions : un seul chantier coordonné.", "Rénovation complète de salle de bains"),
      ("Je veux remplacer ma baignoire par une douche", "Douche à l'italienne ou receveur extra-plat, souvent en moins d'une semaine.", "Baignoire remplacée par une douche"),
      ("J'ai une fuite ou un dégât des eaux", "Intervention dans la journée, recherche de la fuite, rapport pour l'assurance.", "Fuite ou dégât des eaux"),
      ("Je veux changer la robinetterie", "Mitigeurs thermostatiques, colonnes de douche, robinetterie de designer.", "Robinetterie"),
      ("Mon chauffe-eau est trop petit", "Remplacement ou ajout de capacité pour la baignoire et plusieurs douches.", "Chauffe-eau"),
      ("J'achète un appartement ancien", "Visite avant achat, état de la plomberie et chiffrage des travaux.", "Diagnostic avant achat"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "La salle de bains dont vous rêvez, réalisée par une seule équipe.",
    "servs": [
      ("Rénovation complète", "Plans, choix des matériaux avec vous, dépose, plomberie, électricité, carrelage et pose des équipements."),
      ("Douches à l'italienne", "Receveur à fleur de sol, étanchéité sous carrelage, paroi sur mesure, évacuation linéaire discrète."),
      ("Robinetterie et équipements", "Pose de marques que vous choisissez, thermostatiques, WC suspendus, meubles vasques, sèche-serviettes."),
      ("Dépannage et fuites", "Fuite, robinet qui goutte, chasse d'eau, canalisation bouchée : intervention dans la journée."),
      ("Chauffe-eau", "Remplacement, dimensionnement selon vos usages, pose de ballons plats pour les petits espaces."),
      ("Copropriété", "Coordination avec le syndic, respect des horaires, protection des parties communes et de l'ascenseur."),
    ],
    "steps_h2": "Un chantier que vous suivez sans avoir à le gérer.",
    "steps": [
      ("Premier échange", "Vous nous décrivez votre projet et vos envies, photos à l'appui si vous le souhaitez."),
      ("Visite et plan 3D", "On mesure, on vérifie les évacuations, on vous montre le rendu avant de commencer."),
      ("Devis détaillé", "Chaque poste chiffré, matériaux compris. Date de début et durée écrites."),
      ("Chantier et réception", "Un chef de chantier unique, un point chaque semaine, réception ensemble."),
    ],
    "job_labels": ("Travaux", "Durée"),
    "jobs": [
      ("Paris 16e · Haussmannien", "Salle de bains en marbre avec baignoire îlot", "Rénovation complète 9 m²", "4 semaines"),
      ("Neuilly-sur-Seine · Appartement", "Baignoire remplacée par une douche à l'italienne", "Douche et robinetterie", "6 jours"),
      ("Paris 17e · Duplex", "Fuite encastrée localisée sans casser le carrelage", "Recherche de fuite", "1 jour"),
    ],
    "pledges_h2": "Ce que nous vous garantissons.",
    "pledges": [
      ("Un seul interlocuteur.", "Votre chef de chantier coordonne tous les corps de métier et répond à vos questions."),
      ("Une date tenue.", "La date de livraison est écrite dans le devis. Si elle bouge, vous le savez avant nous."),
      ("Un appartement respecté.", "Sols protégés, poussière confinée, parties communes nettoyées chaque jour."),
      ("Des garanties.", "Assurance décennale, garantie des équipements, étanchéité contrôlée avant carrelage."),
    ],
    "reviews": [
      ("« Trois semaines, pas un jour de plus. Le rendu est exactement celui du plan 3D, et l'appartement est resté propre. »", "Anne-Sophie D. · Paris 16e · Salle de bains complète"),
      ("« Fuite chez le voisin du dessous un samedi : ils sont venus le jour même et ont tout géré avec le syndic. »", "Henri V. · Neuilly-sur-Seine · Dégât des eaux"),
    ],
    "faq": [
      ("Combien coûte la rénovation d'une salle de bains ?", "Le budget dépend de la surface, des matériaux (carrelage, marbre, pierre) et des équipements choisis. Après la visite, vous recevez un devis détaillé poste par poste, avec plusieurs options si vous le souhaitez."),
      ("Combien de temps durent les travaux ?", "Comptez en général de deux à quatre semaines pour une salle de bains complète, moins d'une semaine pour remplacer une baignoire par une douche. La durée exacte est écrite sur le devis."),
      ("Peut-on installer une douche à l'italienne partout ?", "Presque toujours, mais cela dépend de la pente possible pour l'évacuation. Nous le vérifions lors de la visite et proposons un receveur extra-plat si le sol ne permet pas une douche à fleur de sol."),
      ("Intervenez-vous en urgence ?", "Oui, pour une fuite ou un dégât des eaux, un plombier se déplace dans la journée à Paris Ouest et à Neuilly."),
      ("Faut-il prévenir la copropriété ?", "Pour des travaux touchant les canalisations communes, oui. Nous préparons les informations pour le syndic et respectons le règlement de l'immeuble."),
      ("Puis-je fournir mes propres équipements ?", "Oui. Nous vérifions leur compatibilité avant la commande et les posons comme s'il s'agissait des nôtres."),
    ],
    "quote_h2": "Parlons de votre projet.", "quote_p": "Décrivez-nous votre salle de bains ou votre problème. On vous rappelle pour fixer la visite, gratuite et sans engagement.",
    "work_label": "Votre besoin",
    "works": ["Rénovation complète de salle de bains", "Baignoire remplacée par une douche", "Fuite ou dégât des eaux", "Robinetterie", "Chauffe-eau", "Diagnostic avant achat", "Autre"],
    "extra": ("surface", "Surface de la pièce", "Ex. : 7 m²", True),
    "details_ph": "Ex. : salle de bains de 7 m² avec baignoire, je voudrais une grande douche et une double vasque",
    "success_end": "fixer la visite de votre projet",
    "nav": NAV,
  },
  {
    "dir": "plomberie/02-meridian",
    "seo_h1": "Plombier à Grenoble et dans l'agglomération",
    "founder": ("Thomas Girard", "gérant, plombier chauffagiste"),
    "photo": ("32588548", "plumber-repairing-pipe-with-wrench-indoors-32588548", "Bulat843"),
    "name": "Plomberie Méridien", "tagline": "Plombier chauffagiste · Grenoble",
    "schema": "Plumber",
    "city": "Grenoble", "cp": "38000", "street": "9 rue Ampère",
    "phone": "04 65 71 30 94", "tel": "+33465713094",
    "hours": "Du lundi au samedi, 7 h 30 à 19 h", "hours_schema": "Mo-Sa 07:30-19:00",
    "zone_short": "Grenoble et agglomération",
    "zone": ["Grenoble", "Échirolles", "Saint-Martin-d'Hères", "Meylan", "Seyssinet-Pariset", "Fontaine", "Saint-Égrève", "Eybens", "Sassenage"],
    "top3": "Tarifs affichés avant intervention",
    "title": "Plombier à Grenoble · Dépannage, fuite, chauffe-eau | Plomberie Méridien",
    "desc": "Plombier à Grenoble et dans l'agglomération : dépannage de fuites, débouchage, chauffe-eau, remplacement de canalisations. Prix annoncé avant de commencer, compte rendu photo après chaque intervention.",
    "fonts": ("Space Grotesk", "Space+Grotesk:wght@500;600;700", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F7F8FA", chalk="#EAEEF3", ink="#1A2A3A", muted="#5A6674", line="#D8DEE6", accent="#F2665A", deep="#C22436"),
    "layout": "overlay",
    "icon": WRENCH,
    "eyebrow": "Plombier · Grenoble et agglomération",
    "h1": ("Une fuite, un WC bouché, plus d'eau chaude ?", "Le prix d'abord, la réparation ensuite."),
    "lead": "Un plombier chez vous dans la journée, du lundi au samedi. Avant de toucher à quoi que ce soit, on vous annonce le prix. Après, vous recevez un compte rendu avec photos de ce qui a été fait.",
    "proofs": ["Prix annoncé et accepté avant de commencer", "Intervention le jour même, du lundi au samedi", "Compte rendu photo envoyé après chaque passage"],
    "cta": "Décrire mon problème", "note": "Réponse en moins d'une heure pendant nos horaires d'ouverture.",
    "badge": ("Jour J", "intervention le jour<br>même dans l'agglo"),
    "alt": "Un plombier en tenue de travail resserre un raccord avec une clé",
    "sit_title": "Qu'est-ce qui se passe chez vous ?",
    "sits": [
      ("J'ai une fuite sous l'évier ou au plafond", "On coupe, on localise, on répare. Et on vous dit d'où ça venait.", "Fuite"),
      ("Mon WC ou mon évier est bouché", "Débouchage à la pompe ou au furet, sans produits agressifs.", "Débouchage"),
      ("Je n'ai plus d'eau chaude", "Diagnostic du chauffe-eau, réparation ou remplacement dans la journée si possible.", "Chauffe-eau"),
      ("Mon robinet goutte ou ma chasse coule", "Joint, cartouche, mécanisme : réparé en une seule visite.", "Robinet ou chasse d'eau"),
      ("Mes canalisations sont anciennes", "Remplacement du plomb ou de l'acier par du cuivre ou du multicouche.", "Remplacement de canalisations"),
      ("Ma facture d'eau a explosé", "Recherche de fuite cachée, contrôle du compteur et des installations.", "Recherche de fuite"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "Tous les dépannages du quotidien, et les travaux qui évitent qu'ils reviennent.",
    "servs": [
      ("Réparation de fuites", "Raccords, flexibles, siphons, canalisations encastrées : localisation et réparation propre."),
      ("Débouchage", "WC, évier, douche, colonne : pompe, furet électrique ou hydrocurage selon l'obstruction."),
      ("Chauffe-eau", "Dépannage, détartrage, remplacement par un modèle adapté à votre foyer, électrique ou thermodynamique."),
      ("Robinetterie et sanitaires", "Remplacement de mitigeurs, WC, lavabos, éviers et mécanismes de chasse."),
      ("Canalisations", "Remplacement de tuyauteries anciennes, déplacement d'arrivées d'eau, création de points d'eau."),
      ("Recherche de fuite", "Contrôle méthodique pour trouver une fuite invisible, rapport transmis à votre assurance."),
    ],
    "steps_h2": "Pas de surprise, ni sur le prix, ni sur ce qui a été fait.",
    "steps": [
      ("Vous décrivez le problème", "Par téléphone ou via le formulaire. Une photo nous aide à venir avec la bonne pièce."),
      ("Créneau confirmé", "On vous donne une heure d'arrivée, et le plombier vous prévient 30 minutes avant."),
      ("Prix avant intervention", "Diagnostic sur place, prix annoncé. Vous acceptez, on commence."),
      ("Compte rendu photo", "Avant, après, pièces changées : tout vous est envoyé par e-mail."),
    ],
    "job_labels": ("Intervention", "Durée"),
    "jobs": [
      ("Grenoble · Appartement", "Fuite sous évier réparée et siphon remplacé", "Dépannage", "45 min"),
      ("Meylan · Maison", "Chauffe-eau de 200 litres remplacé le jour de la panne", "Chauffe-eau", "3 h"),
      ("Échirolles · Immeuble", "Colonne d'évacuation débouchée par hydrocurage", "Débouchage", "2 h"),
    ],
    "pledges_h2": "Nos engagements, écrits noir sur blanc.",
    "pledges": [
      ("Le prix avant le travail.", "Aucune intervention ne commence sans que vous ayez accepté le montant."),
      ("Une heure d'arrivée.", "Un créneau précis, et un appel si le plombier a du retard."),
      ("Une preuve du travail fait.", "Compte rendu photo et facture détaillée après chaque passage."),
      ("Des pièces de qualité.", "Marques reconnues, garanties constructeur transmises."),
    ],
    "reviews": [
      ("« Prix annoncé au téléphone, confirmé sur place, identique sur la facture. Et les photos de la réparation dans ma boîte mail le soir même. »", "Julie R. · Grenoble · Fuite"),
      ("« Plus d'eau chaude un lundi matin, nouveau chauffe-eau installé l'après-midi. Rapide et sans baratin. »", "Mathieu B. · Meylan · Chauffe-eau"),
    ],
    "faq": [
      ("Combien coûte un plombier pour une fuite ?", "Le prix dépend de l'endroit de la fuite et des pièces à changer. Nous vous annonçons le montant après diagnostic et avant toute intervention : vous décidez en connaissance de cause."),
      ("Intervenez-vous le jour même ?", "Oui, du lundi au samedi dans Grenoble et l'agglomération, selon les créneaux disponibles. Pour une fuite active, nous priorisons."),
      ("Que faire en attendant le plombier ?", "Coupez l'arrivée d'eau générale (souvent près du compteur), et l'électricité si l'eau s'approche des prises. Épongez et prenez des photos pour votre assurance."),
      ("Faut-il remplacer ou réparer mon chauffe-eau ?", "Au-delà d'une dizaine d'années ou si la cuve fuit, le remplacement est souvent plus sûr. Sinon, un changement de résistance ou de thermostat peut suffire. Nous vous donnons les deux prix."),
      ("Mes tuyaux sont en plomb, est-ce grave ?", "Les canalisations en plomb sont à remplacer, car elles peuvent altérer la qualité de l'eau. Nous chiffrons leur remplacement par du cuivre ou du multicouche."),
      ("Envoyez-vous un rapport pour l'assurance ?", "Oui. Le compte rendu photo et la facture détaillée servent de justificatif auprès de votre assureur."),
    ],
    "quote_h2": "Décrivez-nous le problème.", "quote_p": "Quelques mots suffisent. On vous rappelle dans l'heure avec un créneau et une première estimation.",
    "work_label": "Type de problème",
    "works": ["Fuite", "Débouchage", "Chauffe-eau", "Robinet ou chasse d'eau", "Remplacement de canalisations", "Recherche de fuite", "Autre"],
    "extra": ("building", "Logement", "Ex. : appartement au 3e, maison", True),
    "details_ph": "Ex. : fuite sous l'évier de la cuisine depuis ce matin, l'eau est coupée",
    "success_end": "vous proposer un créneau d'intervention",
    "nav": NAV,
  },
  {
    "dir": "plomberie/03-copperline",
    "seo_h1": "Plombier à Reims depuis 1962",
    "founder": ("Nicolas Lefèvre", "plombier, troisième génération"),
    "photo": ("7220892", "hands-adjusting-pipe-under-kitchen-sink-7220892", "Cottonbro"),
    "name": "Lefèvre & Fils", "tagline": "Plombiers depuis 1962 · Reims",
    "schema": "Plumber",
    "city": "Reims", "cp": "51100", "street": "46 rue de Vesle",
    "phone": "03 53 01 27 48", "tel": "+33353012748",
    "hours": "Du lundi au vendredi, 8 h à 18 h, samedi matin", "hours_schema": "Mo-Fr 08:00-18:00",
    "zone_short": "Reims et 30 km autour",
    "zone": ["Reims", "Tinqueux", "Bétheny", "Cormontreuil", "Saint-Brice-Courcelles", "Bezannes", "Witry-lès-Reims", "Épernay"],
    "top3": "Entreprise familiale depuis 1962",
    "title": "Plombier à Reims depuis 1962 · Dépannage, entretien, sanitaires | Lefèvre & Fils",
    "desc": "Lefèvre & Fils, plombiers à Reims depuis 1962 : dépannage, entretien de chaudière et de chauffe-eau, remplacement de sanitaires, adaptation de salle de bains pour les seniors. Devis gratuit.",
    "fonts": ("Fraunces", "Fraunces:opsz,wght@9..144,600;9..144,700", "Archivo", "Archivo:wght@400;500;600"),
    "pal": dict(paper="#FBF7F1", chalk="#F1E7DA", ink="#2B2118", muted="#6B5D50", line="#E5D8C7", accent="#D08A4E", deep="#95521F"),
    "layout": "split-left",
    "icon": WRENCH,
    "eyebrow": "Plombiers à Reims depuis 1962",
    "h1": ("Le plombier que vos parents appelaient déjà,", "toujours là quand il y a un souci."),
    "lead": "Trois générations de plombiers au service des Rémois. Dépannage, entretien, sanitaires, adaptation de salle de bains : on vient vite, on travaille proprement, et on ne vous vend que ce dont vous avez besoin.",
    "proofs": ["Dépannage sous 24 h, souvent le jour même", "Devis gratuit, prix tenus", "Les mêmes plombiers qui reviennent chez vous"],
    "cta": "Demander un devis", "note": "On vous rappelle dans la demi-journée.",
    "badge": ("1962", "trois générations<br>de plombiers à Reims"),
    "alt": "Un plombier resserre un raccord sous un évier de cuisine",
    "sit_title": "Pourquoi nous appelez-vous ?",
    "sits": [
      ("J'ai une fuite ou un robinet qui coule", "Dépannage sous 24 h, souvent le jour même.", "Dépannage"),
      ("Il faut entretenir ma chaudière", "Entretien annuel obligatoire, attestation remise sur place.", "Entretien de chaudière"),
      ("Ma baignoire est devenue dangereuse", "Douche de plain-pied, barres d'appui, siège : une salle de bains sûre.", "Salle de bains adaptée"),
      ("Mon chauffe-eau est vieux", "Remplacement par un modèle adapté, ancien appareil évacué.", "Chauffe-eau"),
      ("Je veux changer mes WC ou mon lavabo", "WC suspendu, lavabo, meuble vasque, posés en une journée.", "Sanitaires"),
      ("Je gère un logement en location", "Interventions pour propriétaires et agences, factures claires.", "Propriétaire ou agence"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "Tout ce qu'on fait pour vous depuis soixante ans.",
    "servs": [
      ("Dépannage", "Fuites, robinets, chasses d'eau, canalisations bouchées : sous 24 h, souvent le jour même."),
      ("Entretien de chaudière", "Visite annuelle obligatoire pour les chaudières gaz et fioul, attestation remise."),
      ("Salles de bains adaptées", "Remplacement de baignoire par une douche de plain-pied, barres et sièges pour plus de sécurité."),
      ("Chauffe-eau", "Remplacement, détartrage, groupe de sécurité, évacuation de l'ancien appareil."),
      ("Sanitaires", "WC, lavabos, éviers, robinetterie : dépose de l'ancien et pose du neuf."),
      ("Contrats d'entretien", "Pour les particuliers et les propriétaires bailleurs : un passage par an, dépannages prioritaires."),
    ],
    "steps_h2": "Simple, comme on l'a toujours fait.",
    "steps": [
      ("Vous nous appelez", "C'est souvent un Lefèvre qui décroche. Dites-nous ce qui se passe."),
      ("On passe voir", "Rendez-vous pris à l'heure qui vous arrange, sous 24 h en dépannage."),
      ("Devis clair", "Pour tout ce qui dépasse le petit dépannage, un devis écrit et gratuit."),
      ("Travail propre", "On protège, on répare, on nettoie. Et on vous explique ce qu'on a fait."),
    ],
    "job_labels": ("Travaux", "Durée"),
    "jobs": [
      ("Reims · Maison de ville", "Baignoire remplacée par une douche de plain-pied pour une cliente de 82 ans", "Salle de bains adaptée", "4 jours"),
      ("Tinqueux · Pavillon", "Entretien de chaudière gaz et remplacement du groupe de sécurité", "Entretien", "1 h 30"),
      ("Reims · Immeuble en location", "Remplacement de trois chauffe-eau pour une agence", "Chauffe-eau", "1 jour"),
    ],
    "pledges_h2": "Ce qui ne change pas depuis 1962.",
    "pledges": [
      ("On vient quand on le dit.", "Rendez-vous tenus, et un appel si on a du retard."),
      ("On ne vend pas l'inutile.", "Si une réparation suffit, on ne vous fera pas changer l'appareil."),
      ("On laisse propre.", "Protection des sols, nettoyage avant de partir."),
      ("On reste joignable.", "Une entreprise locale, qui répond au téléphone et revient si besoin."),
    ],
    "reviews": [
      ("« Déjà le plombier de mes parents. Toujours aussi sérieux, et le fils a repris la même rigueur. »", "Martine G. · Reims · Dépannage"),
      ("« Ma mère ne pouvait plus enjamber sa baignoire. Douche installée en quatre jours, elle est ravie. »", "Philippe A. · Reims · Salle de bains adaptée"),
    ],
    "faq": [
      ("L'entretien de ma chaudière est-il obligatoire ?", "Oui, l'entretien annuel est obligatoire pour les chaudières gaz, fioul et bois de 4 à 400 kW. Nous vous remettons l'attestation à la fin de la visite."),
      ("Existe-t-il des aides pour adapter une salle de bains ?", "Des aides existent pour les personnes âgées ou en situation de handicap, selon les revenus et le degré d'autonomie. Nous vous orientons vers les bons interlocuteurs et fournissons les devis nécessaires."),
      ("Combien coûte un dépannage ?", "Cela dépend de la panne et des pièces. Nous vous annonçons le prix sur place, avant de commencer."),
      ("Intervenez-vous pour les propriétaires bailleurs ?", "Oui, pour les particuliers comme pour les agences. Nous pouvons prendre rendez-vous directement avec vos locataires."),
      ("Combien de temps pour remplacer une baignoire par une douche ?", "Généralement trois à cinq jours, selon la configuration et le carrelage."),
      ("Travaillez-vous le samedi ?", "Oui, le samedi matin pour les dépannages."),
    ],
    "quote_h2": "Dites-nous ce qu'il vous faut.", "quote_p": "Quelques mots suffisent. On vous rappelle dans la demi-journée pour convenir d'un passage.",
    "work_label": "Votre besoin",
    "works": ["Dépannage", "Entretien de chaudière", "Salle de bains adaptée", "Chauffe-eau", "Sanitaires", "Propriétaire ou agence", "Autre"],
    "extra": ("building", "Logement", "Ex. : maison, appartement", True),
    "details_ph": "Ex. : chauffe-eau de 15 ans qui fait du bruit et chauffe mal",
    "success_end": "convenir d'un passage chez vous",
    "nav": NAV,
  },
  {
    "dir": "plomberie/04-stillwater",
    "seo_h1": "Entretien de chaudière, chauffe-eau et adoucisseur à Annecy",
    "founder": ("Sophie Vuillermoz", "gérante, technicienne chauffage"),
    "photo": ("7859953", "plumber-repairing-power-source-7859953", "Heiko Ruth"),
    "name": "Onde Claire", "tagline": "Entretien plomberie et chauffage · Annecy",
    "schema": "Plumber",
    "city": "Annecy", "cp": "74000", "street": "15 avenue de Genève",
    "phone": "04 65 71 52 36", "tel": "+33465715236",
    "hours": "Du lundi au vendredi, 8 h à 18 h", "hours_schema": "Mo-Fr 08:00-18:00",
    "zone_short": "Annecy et le lac",
    "zone": ["Annecy", "Annecy-le-Vieux", "Seynod", "Cran-Gevrier", "Sévrier", "Talloires", "Veyrier-du-Lac", "Argonay", "Épagny Metz-Tessy"],
    "top3": "Contrats d'entretien sans engagement",
    "title": "Entretien chaudière, chauffe-eau et adoucisseur à Annecy | Onde Claire",
    "desc": "Onde Claire entretient votre installation d'eau et de chauffage à Annecy : chaudière, chauffe-eau, adoucisseur, détartrage. Contrat d'entretien avec dépannage prioritaire, sans engagement.",
    "fonts": ("Marcellus", "Marcellus", "Outfit", "Outfit:wght@400;500;600"),
    "pal": dict(paper="#F6FAFA", chalk="#E6F0F0", ink="#173238", muted="#54686C", line="#D2E1E1", accent="#7CC3C9", deep="#2F7680"),
    "layout": "overlay",
    "icon": DROP,
    "eyebrow": "Entretien eau et chauffage · Annecy",
    "h1": ("Ne plus jamais penser à votre chaudière,", "ni au calcaire, ni aux pannes du dimanche."),
    "lead": "Autour du lac, l'eau est très calcaire et les hivers sont longs. Onde Claire entretient votre chaudière, votre chauffe-eau et votre adoucisseur une fois par an, et passe en priorité si quelque chose lâche.",
    "proofs": ["Une visite par an, planifiée pour vous", "Dépannage prioritaire pour nos abonnés", "Sans engagement, résiliable à tout moment"],
    "cta": "Découvrir le contrat d'entretien", "note": "Vous n'êtes pas abonné ? On intervient aussi à la demande.",
    "badge": ("1 visite", "par an, et on s'occupe<br>du rappel pour vous"),
    "alt": "Un technicien règle une chaudière murale avec un appareil de mesure",
    "sit_title": "Qu'est-ce qui vous ressemble ?",
    "sits": [
      ("Je veux arrêter de penser à l'entretien", "Contrat annuel : on vous rappelle, on passe, on vous remet l'attestation.", "Contrat d'entretien"),
      ("Mon eau laisse des traces blanches partout", "Pose ou entretien d'un adoucisseur adapté à la dureté de votre eau.", "Adoucisseur"),
      ("Ma chaudière n'a pas été révisée cette année", "Entretien obligatoire, réglages et attestation pour votre assurance.", "Entretien de chaudière"),
      ("Mon chauffe-eau chauffe de moins en moins", "Détartrage et contrôle de la résistance et de l'anode.", "Détartrage de chauffe-eau"),
      ("Mes radiateurs chauffent mal en haut", "Purge, équilibrage et désembouage du circuit de chauffage.", "Radiateurs"),
      ("J'ai une résidence secondaire au bord du lac", "Mise en service avant votre arrivée, vidange et mise hors gel au départ.", "Résidence secondaire"),
    ],
    "serv_eyebrow": "Nos services", "serv_h2": "Une installation entretenue, c'est une facture plus légère et moins de pannes.",
    "servs": [
      ("Contrat d'entretien", "Visite annuelle de la chaudière ou de la pompe à chaleur, contrôle du chauffe-eau, dépannage prioritaire."),
      ("Adoucisseurs", "Analyse de la dureté de l'eau, pose, réglage, recharge de sel et désinfection annuelle."),
      ("Chauffe-eau", "Détartrage, remplacement de l'anode et de la résistance, groupe de sécurité."),
      ("Chauffage", "Purge, désembouage, équilibrage des radiateurs, remplacement de robinets thermostatiques."),
      ("Résidences secondaires", "Ouverture et fermeture de saison, mise hors gel, contrôle pendant votre absence."),
      ("Dépannage", "Pour nos abonnés en priorité, et pour tous du lundi au vendredi."),
    ],
    "steps_h2": "Comment fonctionne le contrat.",
    "steps": [
      ("Vous nous contactez", "On note vos équipements : chaudière, chauffe-eau, adoucisseur."),
      ("Première visite", "État des lieux complet et réglages. Vous savez où en est votre installation."),
      ("On vous rappelle chaque année", "Pas de date à retenir : on vous propose le créneau."),
      ("Priorité en cas de panne", "Un abonné qui appelle passe avant les nouvelles demandes."),
    ],
    "job_labels": ("Intervention", "Durée"),
    "jobs": [
      ("Annecy-le-Vieux · Maison", "Adoucisseur posé, fini le calcaire sur la robinetterie", "Adoucisseur", "4 h"),
      ("Sévrier · Chalet", "Ouverture de saison et remise en eau avant les vacances", "Résidence secondaire", "2 h"),
      ("Seynod · Appartement", "Désembouage du circuit, radiateurs à nouveau chauds partout", "Chauffage", "1 jour"),
    ],
    "pledges_h2": "Ce que vous pouvez attendre de nous.",
    "pledges": [
      ("Un prix connu d'avance.", "Le tarif annuel est fixé à la signature, sans supplément caché."),
      ("Aucun engagement.", "Vous arrêtez quand vous voulez, sans frais."),
      ("Des explications.", "Après chaque visite, un compte rendu clair de l'état de votre installation."),
      ("Des techniciens formés.", "Chaudières gaz, fioul, pompes à chaleur et adoucisseurs."),
    ],
    "reviews": [
      ("« Je n'y pense plus : ils m'appellent en septembre, passent, et je reçois l'attestation. Exactement ce que je voulais. »", "Claire M. · Annecy · Contrat d'entretien"),
      ("« Depuis l'adoucisseur, plus de traces sur la paroi de douche et la bouilloire reste propre. »", "Stéphane P. · Annecy-le-Vieux · Adoucisseur"),
    ],
    "faq": [
      ("L'entretien de la chaudière est-il obligatoire ?", "Oui, chaque année pour les chaudières de 4 à 400 kW. L'attestation peut vous être demandée par votre assureur en cas de sinistre."),
      ("Que comprend le contrat d'entretien ?", "La visite annuelle, les réglages, l'attestation, et un dépannage prioritaire. Les pièces éventuelles sont chiffrées à part, avec votre accord."),
      ("Un adoucisseur est-il utile à Annecy ?", "L'eau du bassin annécien est souvent dure. Nous mesurons la dureté chez vous avant de conseiller, ou non, un adoucisseur."),
      ("Puis-je résilier à tout moment ?", "Oui, le contrat est sans engagement de durée."),
      ("Intervenez-vous sans contrat ?", "Oui, à la demande, du lundi au vendredi. Les abonnés restent prioritaires."),
      ("Gérez-vous les résidences secondaires ?", "Oui : mise en service avant votre arrivée, vidange et mise hors gel à votre départ, avec compte rendu."),
    ],
    "quote_h2": "Parlez-nous de votre installation.", "quote_p": "Dites-nous quels équipements vous avez. On vous rappelle avec un tarif d'entretien adapté.",
    "work_label": "Votre besoin",
    "works": ["Contrat d'entretien", "Entretien de chaudière", "Adoucisseur", "Détartrage de chauffe-eau", "Radiateurs", "Résidence secondaire", "Dépannage"],
    "extra": ("equip", "Vos équipements", "Ex. : chaudière gaz, chauffe-eau 200 L", True),
    "details_ph": "Ex. : chaudière gaz de 2015, jamais d'adoucisseur, eau très calcaire",
    "success_end": "vous proposer un tarif d'entretien",
    "nav": ["Nos services", "Comment ça se passe", "Interventions", "Questions"],
  },
  {
    "dir": "plomberie/05-nexa",
    "seo_h1": "Recherche de fuite sans casse et plombier à Montpellier",
    "founder": ("Yanis Roussel", "gérant, technicien détection de fuites"),
    "photo": ("35290675", "focused-technician-working-with-water-pump-35290675", "Bulat843"),
    "name": "NEXA Plomberie", "tagline": "Plomberie et détection de fuites · Montpellier",
    "schema": "Plumber",
    "city": "Montpellier", "cp": "34000", "street": "30 rue du Pont Juvénal",
    "phone": "04 65 71 64 12", "tel": "+33465716412",
    "hours": "Du lundi au vendredi, 8 h à 19 h", "hours_schema": "Mo-Fr 08:00-19:00",
    "zone_short": "Montpellier et Hérault",
    "zone": ["Montpellier", "Castelnau-le-Lez", "Lattes", "Pérols", "Juvignac", "Saint-Jean-de-Védas", "Mauguio", "Grabels", "Palavas-les-Flots"],
    "top3": "Détection sans casse",
    "title": "Recherche de fuite sans casse et plomberie à Montpellier | NEXA Plomberie",
    "desc": "Recherche de fuite non destructive à Montpellier (caméra thermique, gaz traceur, acoustique), coupe-eau connecté, plomberie. Rapport technique pour votre assurance, intervention sous 48 h.",
    "fonts": ("Sora", "Sora:wght@600;700;800", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F5F8FA", chalk="#E6EEF2", ink="#0B1A24", muted="#52616C", line="#D3DDE4", accent="#2FE0BC", deep="#0B8A73"),
    "layout": "split-right",
    "icon": DROP,
    "eyebrow": "Recherche de fuite sans casse · Montpellier",
    "h1": ("Une fuite quelque part, mais impossible de la voir ?", "On la trouve sans casser vos murs."),
    "lead": "Caméra thermique, gaz traceur, écoute acoustique : nous localisons les fuites cachées au centimètre près, puis nous réparons. Vous recevez un rapport technique à transmettre à votre assurance.",
    "proofs": ["Localisation sans démolition", "Rapport technique pour l'assurance", "Coupe-eau connecté pour ne plus jamais être surpris"],
    "cta": "Faire rechercher ma fuite", "note": "Intervention sous 48 h, en urgence si l'eau coule encore.",
    "badge": ("0 casse", "pour localiser la fuite<br>dans la grande majorité des cas"),
    "alt": "Un technicien règle une pompe et une vanne sur une installation d'eau",
    "sit_title": "Quels signes voyez-vous ?",
    "sits": [
      ("Ma facture d'eau a doublé sans raison", "Contrôle du compteur, puis recherche de la fuite sur tout le réseau.", "Surconsommation d'eau"),
      ("Une tache d'humidité s'agrandit au mur", "Caméra thermique et humidimètre pour trouver l'origine exacte.", "Tache d'humidité"),
      ("Mon voisin du dessous a un dégât des eaux", "Localisation, réparation et rapport pour les deux assurances.", "Dégât des eaux"),
      ("Ma piscine perd de l'eau", "Test d'étanchéité du bassin et des canalisations enterrées.", "Fuite de piscine"),
      ("La pression de ma chaudière baisse", "Recherche de fuite sur le circuit de chauffage, souvent sous dalle.", "Fuite de chauffage"),
      ("Je veux être alerté avant les dégâts", "Détecteurs et coupe-eau automatique pilotés depuis votre téléphone.", "Coupe-eau connecté"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "Trouver la fuite, la réparer, et vous éviter la prochaine.",
    "servs": [
      ("Recherche de fuite non destructive", "Caméra thermique, gaz traceur, corrélation acoustique : la méthode adaptée à chaque situation."),
      ("Réparation ciblée", "Une ouverture limitée à l'endroit exact de la fuite, puis réparation et rebouchage."),
      ("Rapport pour l'assurance", "Photos, relevés et localisation : le document que demandent les assureurs et les experts."),
      ("Fuites de piscine", "Test du bassin, des skimmers, des refoulements et des canalisations enterrées."),
      ("Coupe-eau connecté", "Une vanne motorisée coupe l'eau automatiquement en cas de fuite, alerte sur votre téléphone."),
      ("Plomberie générale", "Remplacement de canalisations, robinetterie, chauffe-eau, dépannage."),
    ],
    "steps_h2": "De la fuite suspectée au dossier d'assurance bouclé.",
    "steps": [
      ("Vous décrivez les signes", "Facture, tache, pression qui baisse : chaque indice nous oriente."),
      ("Recherche sur place", "Le technicien choisit la méthode adaptée et localise la fuite."),
      ("Réparation", "Ouverture minimale, réparation, rebouchage. Tout est chiffré avant."),
      ("Rapport envoyé", "Le rapport technique vous parvient sous 48 h pour votre assurance."),
    ],
    "job_labels": ("Méthode", "Durée"),
    "jobs": [
      ("Montpellier · Appartement", "Fuite sous carrelage localisée à 10 cm près", "Gaz traceur", "2 h"),
      ("Lattes · Villa", "Fuite sur canalisation de piscine enterrée", "Test de pression et écoute", "3 h"),
      ("Castelnau-le-Lez · Maison", "Fuite du plancher chauffant trouvée sans casser la dalle", "Caméra thermique", "2 h 30"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Le moins de casse possible.", "On localise d'abord, on n'ouvre qu'à l'endroit exact."),
      ("Un rapport exploitable.", "Rédigé pour être compris par votre assureur et son expert."),
      ("Un prix annoncé.", "Tarif de la recherche fixé avant le déplacement."),
      ("Des données protégées.", "Les alertes de votre coupe-eau connecté restent chez vous, pas revendues."),
    ],
    "reviews": [
      ("« Trois plombiers avant eux voulaient casser la salle de bains. NEXA a trouvé la fuite en deux heures, sans rien démolir. »", "Nadia K. · Montpellier · Fuite sous carrelage"),
      ("« Le rapport a été accepté tel quel par mon assurance. Le coupe-eau connecté m'a déjà évité un deuxième sinistre. »", "Laurent F. · Castelnau-le-Lez · Recherche de fuite"),
    ],
    "faq": [
      ("La recherche de fuite est-elle prise en charge par l'assurance ?", "Souvent oui, lorsqu'elle est liée à un dégât des eaux. Les conditions dépendent de votre contrat : notre rapport vous aide à constituer le dossier."),
      ("Comment trouvez-vous une fuite sans casser ?", "Selon le cas : caméra thermique pour les écarts de température, gaz traceur injecté dans la canalisation, ou écoute acoustique du bruit de la fuite."),
      ("Combien de temps dure une recherche de fuite ?", "En général de une à trois heures. Le rapport vous est envoyé sous 48 h."),
      ("Comment savoir si j'ai une fuite ?", "Fermez tous les robinets et relevez le compteur, puis relevez-le à nouveau une heure plus tard. S'il a tourné, il y a probablement une fuite."),
      ("À quoi sert un coupe-eau connecté ?", "Des capteurs détectent l'eau au sol et une vanne motorisée coupe l'arrivée générale automatiquement, avec une alerte sur votre téléphone."),
      ("Réparez-vous aussi la fuite ?", "Oui, dans la foulée si c'est possible, avec un prix annoncé avant de commencer."),
    ],
    "quote_h2": "Décrivez les signes de fuite.", "quote_p": "Plus vous nous en dites, plus la recherche sera rapide. On vous rappelle avec un créneau et le tarif.",
    "work_label": "Situation",
    "works": ["Surconsommation d'eau", "Tache d'humidité", "Dégât des eaux", "Fuite de piscine", "Fuite de chauffage", "Coupe-eau connecté", "Plomberie générale"],
    "extra": ("building", "Type de logement", "Ex. : maison avec piscine", True),
    "details_ph": "Ex. : facture d'eau passée de 60 à 180 € sur le trimestre, rien de visible",
    "success_end": "planifier la recherche de fuite",
    "nav": NAV,
  },
]
