"""Serrurerie : 5 marques refaites au format orienté client (septembre 2026)."""

KEY = '<circle cx="11" cy="11" r="6" fill="none" stroke="currentColor" stroke-width="2.6"/><path class="blade" d="M15 15l11 11-2.5 2.5-2-2-2 2-2-2 2-2-6.5-6.5z"/>'
LOCK = '<rect class="blade" x="7" y="14" width="18" height="13" rx="2"/><path d="M11 14v-4a5 5 0 0 1 10 0v4" fill="none" stroke="currentColor" stroke-width="2.6"/>'

NAV = ["Nos interventions", "Comment ça se passe", "Interventions", "Questions"]

SITES = [
  {
    "dir": "serrurerie/01-bastion-clef",
    "seo_h1": "Serrurier haute sécurité à Paris : portes blindées et serrures A2P",
    "founder": ("Édouard Vasseur", "fondateur, serrurier"),
    "photo": ("279810", "deadlock-with-key-on-hole-279810", "Pixabay"),
    "name": "Bastion & Clef", "tagline": "Serrurerie haute sécurité · Paris",
    "schema": "Locksmith",
    "city": "Paris", "cp": "75008", "street": "11 rue de Miromesnil",
    "phone": "01 99 00 58 13", "tel": "+33199005813",
    "hours": "Du lundi au samedi, 8 h à 20 h", "hours_schema": "Mo-Sa 08:00-20:00",
    "zone_short": "Paris et Neuilly",
    "zone": ["Paris (tous arrondissements)", "Neuilly-sur-Seine", "Levallois-Perret", "Boulogne-Billancourt", "Saint-Mandé", "Vincennes"],
    "top3": "Serrures certifiées A2P",
    "title": "Porte blindée et serrure haute sécurité à Paris | Bastion & Clef",
    "desc": "Bastion & Clef sécurise les appartements et hôtels particuliers parisiens : portes blindées, serrures certifiées A2P, coffres-forts, cartes de clés protégées. Audit de sécurité gratuit à domicile.",
    "fonts": ("Playfair Display", "Playfair+Display:ital,wght@0,600;0,700;1,600", "Montserrat", "Montserrat:wght@400;500;600"),
    "pal": dict(paper="#F8F6F1", chalk="#ECE7DC", ink="#0E0E10", muted="#5C5A56", line="#DDD7CB", accent="#C9A54B", deep="#86661B"),
    "layout": "overlay",
    "icon": KEY,
    "eyebrow": "Serrurerie haute sécurité · Paris",
    "h1": ("Dormir tranquille, partir en voyage l'esprit libre :", "votre porte ne cédera pas."),
    "lead": "Portes blindées, serrures certifiées A2P, coffres-forts et clés protégées contre la copie. Nous auditons votre logement gratuitement et vous proposons la protection adaptée, posée avec la discrétion qu'exige votre adresse.",
    "proofs": ["Audit de sécurité gratuit à domicile", "Serrures et portes certifiées A2P", "Intervenants salariés, discrets, identifiables"],
    "cta": "Demander un audit de sécurité", "note": "Rendez-vous sous 48 h, à l'heure qui vous convient.",
    "badge": ("A2P", "serrures et blindages<br>certifiés anti-effraction"),
    "alt": "Une serrure de sécurité avec sa clé sur une porte d'entrée",
    "sit_title": "Qu'est-ce qui vous préoccupe ?",
    "sits": [
      ("Ma porte d'entrée me semble fragile", "Blindage de la porte existante ou bloc-porte blindé complet.", "Porte blindée"),
      ("Je viens d'emménager", "Changement de cylindre : les anciens occupants n'auront plus vos clés.", "Changement de serrure"),
      ("J'ai subi une tentative d'effraction", "Mise en sécurité immédiate, puis renforcement durable.", "Après effraction"),
      ("Je veux protéger mes objets de valeur", "Coffre-fort encastré ou scellé, certifié, posé discrètement.", "Coffre-fort"),
      ("Trop de clés circulent (personnel, famille)", "Clés protégées : copie possible uniquement sur présentation de votre carte.", "Clés protégées"),
      ("Je pars longtemps", "Audit avant départ, renforcement des points faibles.", "Audit de sécurité"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "La sécurité de votre logement, pensée comme un tout.",
    "servs": [
      ("Portes blindées", "Blocs-portes certifiés ou blindage de votre porte existante, finitions assorties à votre intérieur."),
      ("Serrures multipoints", "Serrures 3 à 7 points certifiées A2P, adaptées à votre porte et à votre niveau d'exigence."),
      ("Cylindres et clés protégées", "Cylindres haute sécurité et carte de propriété : personne ne copie vos clés sans vous."),
      ("Coffres-forts", "Coffres encastrés, à sceller ou meubles-coffres, choisis selon ce que vous protégez."),
      ("Mise en sécurité après effraction", "Fermeture provisoire le jour même, dossier photo pour l'assurance, remplacement définitif."),
      ("Audit de sécurité", "Portes, fenêtres, accès secondaires : un bilan écrit et des recommandations chiffrées."),
    ],
    "steps_h2": "Une protection sur mesure, sans intervention hâtive.",
    "steps": [
      ("Premier échange", "Vous nous décrivez votre logement et vos inquiétudes, en toute confidentialité."),
      ("Audit à domicile", "Un expert examine vos accès et vous explique les points faibles."),
      ("Proposition écrite", "Solutions et prix détaillés, avec leur niveau de certification."),
      ("Pose soignée", "Intervention à la date choisie, clés et cartes remises en main propre."),
    ],
    "job_labels": ("Intervention", "Durée"),
    "jobs": [
      ("Paris 8e · Appartement", "Porte d'entrée blindée avec serrure 7 points A2P", "Blindage sur porte existante", "1 jour"),
      ("Neuilly-sur-Seine · Hôtel particulier", "Cylindres protégés sur 6 accès, 12 clés sous carte", "Organigramme de clés", "1 jour"),
      ("Paris 16e · Après tentative d'effraction", "Mise en sécurité le jour même, bloc-porte posé en 10 jours", "Après effraction", "2 passages"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Discrétion absolue.", "Aucune information sur votre logement ou vos accès ne sort de notre atelier."),
      ("Du matériel certifié.", "Serrures, cylindres et blocs-portes certifiés A2P, attestations remises."),
      ("Des prix écrits.", "Aucune pose sans devis signé, même après une effraction."),
      ("Des intervenants identifiables.", "Salariés de l'entreprise, carte professionnelle présentée à l'arrivée."),
    ],
    "reviews": [
      ("« Audit très pédagogique, sans aucune pression. La porte blindée est posée, et elle s'accorde parfaitement avec l'entrée. »", "Charles-Henri L. · Paris 8e · Porte blindée"),
      ("« Après une tentative d'effraction, ils ont sécurisé la porte le soir même et tout géré avec l'assurance. »", "Isabelle R. · Paris 16e · Après effraction"),
    ],
    "faq": [
      ("Que signifie la certification A2P ?", "C'est une certification française qui classe la résistance à l'effraction des serrures, cylindres et blocs-portes (1, 2 ou 3 étoiles). Certains assureurs l'exigent pour les logements de valeur."),
      ("Blinder ma porte ou la remplacer ?", "Le blindage renforce votre porte existante et coûte moins cher. Le bloc-porte blindé offre la meilleure résistance. L'audit permet de choisir selon votre porte et vos besoins."),
      ("Qu'est-ce qu'une clé protégée ?", "Une clé dont la copie n'est possible que chez un revendeur agréé, sur présentation de votre carte de propriété. Vous savez toujours combien de clés existent."),
      ("Intervenez-vous en copropriété ?", "Oui. Pour une porte palière visible depuis les parties communes, nous vérifions le règlement et proposons des finitions conformes."),
      ("Combien de temps pour une porte blindée ?", "Un blindage se pose en une journée. Un bloc-porte sur mesure demande environ deux semaines de fabrication, avec une mise en sécurité provisoire si besoin."),
      ("L'audit est-il vraiment gratuit ?", "Oui, sans engagement. Vous repartez avec un bilan de vos points faibles, que vous travailliez avec nous ou non."),
    ],
    "quote_h2": "Parlons de votre sécurité.", "quote_p": "Vos informations restent confidentielles. On vous rappelle pour fixer l'audit, gratuit et sans engagement.",
    "work_label": "Votre besoin",
    "works": ["Porte blindée", "Changement de serrure", "Après effraction", "Coffre-fort", "Clés protégées", "Audit de sécurité", "Autre"],
    "extra": ("building", "Type de logement", "Ex. : appartement 4e étage, maison", True),
    "details_ph": "Ex. : porte d'origine de l'immeuble, une seule serrure, nous partons trois mois cet été",
    "success_end": "fixer votre audit de sécurité",
    "nav": NAV,
  },
  {
    "dir": "serrurerie/02-keystone-lock",
    "seo_h1": "Serrurier à Nantes, 7 jours sur 7, prix affichés",
    "founder": ("Kevin Le Goff", "gérant, serrurier"),
    "photo": ("35287856", "close-up-of-a-locksmith-working-with-tools-35287856", "Saad Bin Hasan"),
    "name": "Serrurerie Clé de Voûte", "tagline": "Serrurier aux prix affichés · Nantes",
    "schema": "Locksmith",
    "city": "Nantes", "cp": "44000", "street": "22 rue de Strasbourg",
    "phone": "02 61 91 73 20", "tel": "+33261917320",
    "hours": "7 j/7, de 7 h à 22 h", "hours_schema": "Mo-Su 07:00-22:00",
    "zone_short": "Nantes Métropole",
    "zone": ["Nantes", "Rezé", "Saint-Herblain", "Orvault", "Saint-Sébastien-sur-Loire", "Vertou", "Carquefou", "Bouguenais", "La Chapelle-sur-Erdre"],
    "top3": "Prix affichés, sans surprise",
    "title": "Serrurier à Nantes · Porte claquée, serrure, prix affichés | Clé de Voûte",
    "desc": "Serrurier à Nantes 7 j/7 : ouverture de porte claquée, changement de serrure, cylindre, porte blindée. Prix affichés avant de se déplacer, devis écrit avant toute intervention.",
    "fonts": ("Archivo", "Archivo:wght@600;700;800", "Karla", "Karla:wght@400;500;600"),
    "pal": dict(paper="#F8F7F4", chalk="#EEEBE4", ink="#121110", muted="#5F5B55", line="#DEDAD2", accent="#F07A2E", deep="#B24E0B"),
    "layout": "split-right",
    "urgent": True,
    "icon": KEY,
    "eyebrow": "Serrurier · Nantes, 7 j/7",
    "h1": ("Porte claquée ou serrure bloquée ?", "Vous connaissez le prix avant qu'on se déplace."),
    "lead": "Les arnaques au dépannage de serrure sont trop fréquentes. Chez nous, les prix des interventions courantes sont affichés ici même, et vous signez un devis avant que l'on touche à votre porte.",
    "proofs": ["Prix annoncé au téléphone, confirmé par écrit", "Ouverture de porte claquée sans casse le plus souvent", "Serrurier sur place en 30 à 45 minutes dans Nantes"],
    "cta": "Voir les prix et demander", "note": "7 j/7 de 7 h à 22 h. Aucun supplément caché le dimanche.",
    "badge": ("30 min", "en moyenne pour arriver<br>dans Nantes intra-muros"),
    "alt": "Un serrurier taille une clé sur une machine",
    "sit_title": "Que vous arrive-t-il ?",
    "sits": [
      ("J'ai claqué ma porte, les clés sont dedans", "Ouverture sans casse dans la majorité des cas, prix fixe annoncé.", "Porte claquée"),
      ("J'ai perdu mes clés", "Ouverture puis changement du cylindre pour votre sécurité.", "Clés perdues"),
      ("Ma clé tourne mal ou s'est cassée dans la serrure", "Extraction, réparation ou remplacement du cylindre.", "Serrure bloquée"),
      ("On m'a volé mes clés avec mon adresse", "Changement de cylindre en urgence, le jour même.", "Clés volées"),
      ("Je veux une serrure plus solide", "Serrure multipoints ou cylindre haute sécurité, posé en 1 h.", "Changement de serrure"),
      ("Je suis propriétaire, mon locataire part", "Changement de cylindre entre deux locations.", "Changement de cylindre"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "Les interventions courantes, et leur prix affiché.",
    "servs": [
      ("Ouverture de porte claquée", "Porte non verrouillée, en journée : prix fixe annoncé au téléphone, confirmé sur place."),
      ("Ouverture de porte verrouillée", "Selon la serrure, avec ou sans remplacement du cylindre. Devis avant intervention."),
      ("Changement de cylindre", "Cylindre standard ou haute sécurité, livré avec ses clés, posé en 30 minutes."),
      ("Serrures multipoints", "Remplacement ou ajout d'une serrure 3 ou 5 points sur votre porte."),
      ("Porte blindée", "Blindage de porte existante ou bloc-porte, sur devis après visite."),
      ("Boîtes aux lettres et portails", "Serrures de boîte aux lettres, de portail, de garage et de cave."),
    ],
    "steps_h2": "Un dépannage honnête, étape par étape.",
    "steps": [
      ("Vous appelez", "On vous pose trois questions et on vous annonce le prix."),
      ("Arrivée confirmée", "Heure d'arrivée donnée, SMS avec le nom du serrurier."),
      ("Devis signé sur place", "Le prix annoncé est écrit. Vous signez, on commence."),
      ("Facture identique", "Le montant de la facture est celui du devis. Point."),
    ],
    "job_labels": ("Intervention", "Durée"),
    "jobs": [
      ("Nantes centre · Appartement", "Porte claquée ouverte sans casse un dimanche soir", "Ouverture", "20 min"),
      ("Rezé · Maison", "Clés volées : cylindre remplacé dans l'heure", "Changement de cylindre", "35 min"),
      ("Saint-Herblain · Location", "Serrure 3 points posée entre deux locataires", "Serrure multipoints", "1 h 15"),
    ],
    "pledges_h2": "Notre charte anti-arnaque.",
    "pledges": [
      ("Le prix avant le déplacement.", "Pour les interventions courantes, vous le connaissez dès l'appel."),
      ("Un devis signé avant d'agir.", "Aucune intervention ne commence sans votre accord écrit."),
      ("Pas de casse inutile.", "On ne perce une serrure que si aucune autre méthode ne fonctionne."),
      ("Un serrurier identifié.", "Nom envoyé par SMS avant son arrivée, carte présentée sur place."),
    ],
    "reviews": [
      ("« Porte claquée à 21 h. Prix annoncé au téléphone, serrurier là en 25 minutes, et la facture était exactement la même. »", "Élodie P. · Nantes · Porte claquée"),
      ("« Après une mauvaise expérience avec un autre dépanneur, enfin quelqu'un de transparent. Je garde le numéro. »", "Bruno L. · Rezé · Changement de cylindre"),
    ],
    "faq": [
      ("Combien coûte l'ouverture d'une porte claquée ?", "Pour une porte simplement claquée (non verrouillée), nous annonçons un prix fixe au téléphone, confirmé sur place avant d'intervenir. Il n'augmente pas le soir ou le dimanche dans nos horaires."),
      ("Faut-il forcément changer la serrure ?", "Non. Une porte claquée s'ouvre le plus souvent sans casse. On ne change le cylindre que si la porte était verrouillée ou si vous avez perdu vos clés."),
      ("Comment éviter les arnaques au serrurier ?", "Exigez un devis écrit avant toute intervention, méfiez-vous des numéros sans adresse et des prix annoncés « à partir de ». Chez nous, le devis est systématique."),
      ("Mon assurance peut-elle rembourser ?", "Certains contrats d'assurance habitation couvrent la perte ou le vol de clés. Gardez la facture détaillée, nous la rédigeons pour cela."),
      ("Intervenez-vous la nuit ?", "Nous intervenons 7 j/7 de 7 h à 22 h. En dehors, nous vous orientons vers une solution d'urgence."),
      ("Quelle serrure choisir pour plus de sécurité ?", "Une serrure multipoints avec un cylindre certifié A2P offre une bonne résistance. On vous conseille selon votre porte."),
    ],
    "quote_h2": "Dites-nous ce qui se passe.", "quote_p": "Pour une urgence, appelez directement. Pour un changement de serrure, décrivez votre porte : on vous rappelle avec le prix.",
    "work_label": "Situation",
    "works": ["Porte claquée", "Clés perdues", "Serrure bloquée", "Clés volées", "Changement de serrure", "Changement de cylindre", "Porte blindée", "Autre"],
    "extra": ("door", "Type de porte", "Ex. : porte d'appartement, 3 points", True),
    "details_ph": "Ex. : clé qui force depuis une semaine, serrure 3 points",
    "success_end": "vous annoncer le prix et un créneau",
    "nav": NAV,
  },
  {
    "dir": "serrurerie/03-ironhaven",
    "seo_h1": "Serrurier et double de clés à Strasbourg depuis 1954",
    "founder": ("Pierre Hardy", "serrurier, troisième génération"),
    "photo": ("35578808", "elderly-locksmith-working-in-key-shop-35578808", "Muhammad Diler"),
    "name": "Serrurerie Hardy", "tagline": "Serrurier et clés depuis 1954 · Strasbourg",
    "schema": "Locksmith",
    "city": "Strasbourg", "cp": "67000", "street": "7 rue des Orfèvres",
    "phone": "03 53 01 45 91", "tel": "+33353014591",
    "hours": "Du mardi au samedi, 9 h à 18 h 30", "hours_schema": "Tu-Sa 09:00-18:30",
    "zone_short": "Boutique au centre de Strasbourg",
    "zone": ["Strasbourg", "Schiltigheim", "Illkirch-Graffenstaden", "Lingolsheim", "Bischheim", "Hoenheim", "Ostwald"],
    "top3": "Double de clé en 5 minutes",
    "title": "Serrurier et double de clés à Strasbourg depuis 1954 | Serrurerie Hardy",
    "desc": "Serrurerie Hardy, au centre de Strasbourg depuis 1954 : doubles de clés, clés de voiture et badges, serrures, boîtes aux lettres, restauration de serrures anciennes. Boutique et interventions à domicile.",
    "fonts": ("Libre Caslon Text", "Libre+Caslon+Text:ital,wght@0,400;0,700;1,400", "Work Sans", "Work+Sans:wght@400;500;600"),
    "pal": dict(paper="#FAF6F0", chalk="#EFE6D8", ink="#1A1512", muted="#685C52", line="#E3D7C6", accent="#D9733F", deep="#A1400F"),
    "layout": "split-left",
    "shop": True,
    "icon": KEY,
    "eyebrow": "Serrurier depuis 1954 · Strasbourg",
    "h1": ("Un double de clé en cinq minutes,", "une serrure réparée plutôt que remplacée."),
    "lead": "Notre boutique rue des Orfèvres reproduit vos clés, badges et télécommandes pendant que vous attendez. Nos serruriers se déplacent pour vos serrures, et restaurent les mécanismes anciens des immeubles strasbourgeois.",
    "proofs": ["Doubles de clés et badges pendant que vous attendez", "Serrures anciennes réparées à l'atelier", "Déplacement à domicile dans l'Eurométropole"],
    "cta": "Nous écrire", "note": "Sans rendez-vous en boutique, du mardi au samedi.",
    "badge": ("1954", "trois générations<br>rue des Orfèvres"),
    "alt": "Un serrurier âgé taille une clé dans sa boutique remplie de clés",
    "sit_title": "Que peut-on faire pour vous ?",
    "sits": [
      ("Il me faut un double de clé", "Clés plates, à pompe, sécurisées : faites pendant que vous attendez.", "Double de clé"),
      ("Je veux copier le badge de mon immeuble", "Badges et télécommandes de portail dupliqués en boutique.", "Badge ou télécommande"),
      ("J'ai perdu ma clé de voiture", "Clés et télécommandes de voiture pour la plupart des modèles.", "Clé de voiture"),
      ("Ma serrure ancienne est grippée", "Démontage, réparation et nettoyage à l'atelier.", "Serrure ancienne"),
      ("Je veux changer ma serrure", "Conseil en boutique, pose à domicile.", "Changement de serrure"),
      ("Ma boîte aux lettres ne ferme plus", "Serrures de boîtes aux lettres de toutes marques.", "Boîte aux lettres"),
    ],
    "serv_eyebrow": "L'atelier", "serv_h2": "La boutique pour vos clés, les serruriers pour vos portes.",
    "servs": [
      ("Doubles de clés", "Plus de 2 000 modèles de clés en stock : plates, à gorges, à pompe, sécurisées sur carte."),
      ("Badges et télécommandes", "Copie de badges d'immeuble et de télécommandes de portail ou de garage."),
      ("Clés de voiture", "Clés à transpondeur et télécommandes pour la plupart des modèles, programmées sur place."),
      ("Serrures anciennes", "Réparation et restauration des serrures et crémones des immeubles anciens."),
      ("Serrures et cylindres", "Remplacement, mise en place de serrures multipoints, conseil de sécurité."),
      ("Petits dépannages", "Boîtes aux lettres, casiers, meubles, cadenas."),
    ],
    "steps_h2": "Comme au comptoir, depuis soixante-dix ans.",
    "steps": [
      ("Vous passez en boutique", "Avec votre clé, votre badge ou une photo de votre serrure."),
      ("On regarde ensemble", "Conseil, prix et délai annoncés au comptoir."),
      ("Fait sur place ou à l'atelier", "Doubles en cinq minutes, réparations en quelques jours."),
      ("Intervention à domicile", "Pour la pose de serrures, rendez-vous à l'heure qui vous arrange."),
    ],
    "job_labels": ("Travail", "Délai"),
    "jobs": [
      ("Neustadt · Immeuble de 1900", "Serrure à gorges d'origine restaurée à l'atelier", "Restauration", "4 jours"),
      ("Strasbourg · Copropriété", "Quinze badges d'entrée dupliqués pour les résidents", "Badges", "1 h"),
      ("Schiltigheim · Maison", "Serrure 3 points posée sur porte d'entrée", "Pose à domicile", "1 h 30"),
    ],
    "pledges_h2": "Ce que la maison vous garantit.",
    "pledges": [
      ("Des doubles qui fonctionnent.", "Si votre clé ne tourne pas bien, on la reprend gratuitement."),
      ("Réparer d'abord.", "Une serrure ancienne réparable n'est pas remplacée."),
      ("Des prix au comptoir.", "Tous nos tarifs de reproduction sont affichés en boutique."),
      ("Un savoir-faire transmis.", "Trois générations de serruriers formés dans la même boutique."),
    ],
    "reviews": [
      ("« Double de clé fait en cinq minutes, qui fonctionne du premier coup. C'est rare. »", "Lucie W. · Strasbourg · Double de clé"),
      ("« Ils ont sauvé la serrure d'origine de notre porte de 1905 au lieu de la remplacer. Un vrai savoir-faire. »", "Thomas K. · Neustadt · Serrure ancienne"),
    ],
    "faq": [
      ("Combien de temps pour un double de clé ?", "Cinq minutes environ pour une clé courante, pendant que vous attendez. Les clés sécurisées demandent votre carte de propriété et parfois une commande."),
      ("Pouvez-vous copier un badge d'immeuble ?", "Dans la plupart des cas oui, en boutique. Certains badges cryptés ne sont pas copiables : on vous le dit tout de suite."),
      ("Faites-vous les clés de voiture ?", "Oui, pour la plupart des modèles, avec programmation de la puce et de la télécommande."),
      ("Réparez-vous les serrures anciennes ?", "Oui, c'est une spécialité de l'atelier. Démontage, nettoyage, pièces refaites si besoin."),
      ("Faut-il prendre rendez-vous ?", "Non pour la boutique. Pour une intervention à domicile, appelez-nous ou utilisez le formulaire."),
      ("Où se trouve la boutique ?", "7 rue des Orfèvres, au centre de Strasbourg, à deux pas de la cathédrale."),
    ],
    "quote_h2": "Une question, un devis ?", "quote_p": "Pour une pose de serrure ou une réparation, décrivez-nous votre besoin. On vous rappelle avec un prix.",
    "work_label": "Votre besoin",
    "works": ["Double de clé", "Badge ou télécommande", "Clé de voiture", "Serrure ancienne", "Changement de serrure", "Boîte aux lettres", "Autre"],
    "extra": ("item", "Clé ou serrure concernée", "Ex. : clé de voiture, serrure de 1900", True),
    "details_ph": "Ex. : serrure à gorges d'origine qui accroche, porte d'immeuble ancien",
    "success_end": "vous donner un prix et un délai",
    "nav": ["L'atelier", "Comment ça se passe", "Réalisations", "Questions"],
  },
  {
    "dir": "serrurerie/04-haven-hour",
    "seo_h1": "Serrurier d'urgence à Lyon, 24 h/24 et 7 j/7",
    "founder": ("Mehdi Aït-Saïd", "gérant, serrurier"),
    "photo": ("7641991", "keys-inserted-in-the-lock-of-a-door-7641991", "A. Darmel"),
    "name": "Serrurier de Garde", "tagline": "Serrurier 24 h/24 · Lyon",
    "schema": "Locksmith",
    "city": "Lyon", "cp": "69003", "street": "58 cours Lafayette",
    "phone": "04 65 71 90 00", "tel": "+33465719000",
    "hours": "24 h/24, 7 j/7, jours fériés compris", "hours_schema": "Mo-Su 00:00-23:59",
    "zone_short": "Lyon et Villeurbanne",
    "zone": ["Lyon (tous arrondissements)", "Villeurbanne", "Caluire-et-Cuire", "Bron", "Vénissieux", "Oullins", "Tassin-la-Demi-Lune", "Écully", "Saint-Fons"],
    "top3": "Tarif de nuit annoncé au téléphone",
    "title": "Serrurier d'urgence 24h/24 à Lyon · Porte claquée, effraction | Serrurier de Garde",
    "desc": "Serrurier d'urgence à Lyon et Villeurbanne, 24 h/24 et 7 j/7 : porte claquée, clés perdues, mise en sécurité après effraction. Prix annoncé au téléphone, y compris la nuit.",
    "fonts": ("Newsreader", "Newsreader:opsz,wght@6..72,600;6..72,700", "Manrope", "Manrope:wght@400;500;600;700"),
    "pal": dict(paper="#F5F6FA", chalk="#E7EAF2", ink="#1B2A4A", muted="#566079", line="#D6DBE7", accent="#E4B35A", deep="#8F6417"),
    "layout": "overlay",
    "urgent": True,
    "icon": LOCK,
    "eyebrow": "Serrurier d'urgence · Lyon, 24 h/24",
    "h1": ("Bloqué dehors en pleine nuit ?", "Quelqu'un répond, et vous savez déjà combien ça coûte."),
    "lead": "Porte claquée, clés perdues, effraction : un serrurier de garde décroche à toute heure, vous annonce le tarif de nuit au téléphone, et arrive en général en moins de 40 minutes dans Lyon.",
    "proofs": ["Un humain répond 24 h/24, 7 j/7", "Tarif de nuit et de week-end annoncé avant de partir", "Mise en sécurité après effraction, même à 3 h du matin"],
    "cta": "Demande non urgente", "note": "Pour une urgence, appelez : c'est plus rapide que le formulaire.",
    "badge": ("24 h/24", "un serrurier de garde<br>chaque nuit à Lyon"),
    "alt": "Des clés dans la serrure d'une porte d'entrée",
    "sit_title": "Que vous arrive-t-il ?",
    "sits": [
      ("Je suis bloqué dehors, la porte est claquée", "Ouverture sans casse la plupart du temps, prix annoncé au téléphone.", "Porte claquée"),
      ("J'ai perdu mes clés en soirée", "Ouverture et changement du cylindre dans la foulée.", "Clés perdues"),
      ("On a tenté de forcer ma porte", "Mise en sécurité immédiate et dossier photo pour l'assurance.", "Effraction"),
      ("Ma clé est cassée dans la serrure", "Extraction et remise en état, sans forcément tout changer.", "Clé cassée"),
      ("Mon enfant ou un proche âgé est enfermé", "Priorité absolue, départ immédiat.", "Personne enfermée"),
      ("Je veux changer ma serrure (pas urgent)", "Rendez-vous en journée, au tarif normal.", "Changement de serrure"),
    ],
    "serv_eyebrow": "Nos interventions", "serv_h2": "L'urgence, traitée calmement et au bon prix.",
    "servs": [
      ("Ouverture de porte", "Porte claquée ou verrouillée, jour et nuit, avec la méthode la moins destructive."),
      ("Mise en sécurité après effraction", "Réparation provisoire ou définitive, fermeture assurée avant notre départ."),
      ("Changement de cylindre", "Après une perte ou un vol de clés, pour que personne d'autre ne puisse entrer."),
      ("Extraction de clé cassée", "Retrait du morceau coincé, contrôle du cylindre, nouvelle clé si besoin."),
      ("Serrures et portes", "Remplacement de serrures, renforcement de porte, rendez-vous en journée."),
      ("Dossier pour l'assurance", "Photos, constat et facture détaillée pour votre déclaration."),
    ],
    "steps_h2": "Ce qui se passe quand vous appelez.",
    "steps": [
      ("Un humain décroche", "Jour et nuit, quelqu'un vous écoute et pose les bonnes questions."),
      ("Le prix annoncé", "Tarif de l'intervention, y compris la majoration de nuit, avant tout départ."),
      ("Le serrurier arrive", "Vous recevez son nom et son heure d'arrivée par SMS."),
      ("Vous êtes à l'abri", "Porte ouverte ou sécurisée, facture identique au prix annoncé."),
    ],
    "job_labels": ("Intervention", "Arrivée"),
    "jobs": [
      ("Lyon 7e · 2 h du matin", "Porte claquée ouverte sans casse", "Ouverture", "28 min"),
      ("Villeurbanne · Dimanche", "Porte fracturée sécurisée et cylindre remplacé", "Après effraction", "35 min"),
      ("Lyon 3e · Soirée", "Clé cassée extraite, cylindre conservé", "Extraction", "22 min"),
    ],
    "pledges_h2": "Nos promesses, surtout la nuit.",
    "pledges": [
      ("Pas de mauvaise surprise.", "La majoration de nuit est annoncée au téléphone, jamais découverte sur la facture."),
      ("Pas de casse inutile.", "Ouverture fine d'abord, perçage en dernier recours."),
      ("Personne ne reste dehors.", "Si une pièce manque, on sécurise quand même la porte avant de partir."),
      ("Un serrurier identifié.", "Nom et carte professionnelle, entreprise locale avec adresse à Lyon."),
    ],
    "reviews": [
      ("« 3 h du matin, clés oubliées au bureau. Une voix calme au téléphone, le prix tout de suite, et un serrurier en 30 minutes. »", "Camille D. · Lyon 7e · Porte claquée"),
      ("« Après la tentative d'effraction, ils ont réparé la porte en pleine nuit et nous ont laissé tout le dossier pour l'assurance. »", "Rachid M. · Villeurbanne · Effraction"),
    ],
    "faq": [
      ("Combien coûte un serrurier la nuit ?", "Une majoration s'applique la nuit, le dimanche et les jours fériés. Nous l'annonçons au téléphone avant de partir, avec le prix total de l'intervention."),
      ("En combien de temps arrivez-vous ?", "En général en moins de 40 minutes dans Lyon et Villeurbanne, selon l'heure et la circulation. Vous recevez l'heure d'arrivée par SMS."),
      ("Que faire après une effraction ?", "Ne touchez à rien, appelez la police pour le dépôt de plainte, puis un serrurier pour sécuriser. Nous fournissons photos et facture pour votre assurance."),
      ("Faut-il obligatoirement changer la serrure ?", "Non. Une porte claquée s'ouvre souvent sans dommage. En cas de perte ou de vol de clés, changer le cylindre est recommandé."),
      ("Comment reconnaître un serrurier sérieux ?", "Une adresse locale vérifiable, un prix annoncé avant de se déplacer et un devis signé sur place. Méfiez-vous des tarifs « à partir de »."),
      ("Intervenez-vous les jours fériés ?", "Oui, 24 h/24 et 7 j/7, y compris les jours fériés."),
    ],
    "quote_h2": "Une demande non urgente ?", "quote_p": "Pour une urgence, appelez le 04 65 71 90 00. Pour un changement de serrure ou un conseil, laissez-nous un message.",
    "work_label": "Situation",
    "works": ["Porte claquée", "Clés perdues", "Effraction", "Clé cassée", "Personne enfermée", "Changement de serrure", "Autre"],
    "extra": ("door", "Type de porte", "Ex. : porte d'appartement blindée", True),
    "details_ph": "Ex. : serrure qui accroche depuis quelques jours, je voudrais la faire changer",
    "success_end": "vous proposer un rendez-vous",
    "nav": NAV,
  },
  {
    "dir": "serrurerie/05-aperio",
    "seo_h1": "Contrôle d'accès, badges et interphones pour copropriétés en Île-de-France",
    "founder": ("Laura Chen", "directrice technique"),
    "photo": ("9461758", "man-in-black-long-sleeve-shirt-pressing-a-button-on-intercom-9461758", "Mike Jones"),
    "name": "Aperio Accès", "tagline": "Contrôle d'accès et interphonie · Île-de-France",
    "schema": "Locksmith",
    "city": "Paris", "cp": "75012", "street": "88 avenue Daumesnil",
    "phone": "01 99 00 72 64", "tel": "+33199007264",
    "hours": "Du lundi au vendredi, 8 h à 18 h, astreinte 24 h/24", "hours_schema": "Mo-Fr 08:00-18:00",
    "zone_short": "Paris et Île-de-France",
    "zone": ["Paris", "Hauts-de-Seine", "Seine-Saint-Denis", "Val-de-Marne", "Yvelines", "Essonne", "Val-d'Oise"],
    "top3": "Astreinte 24 h/24 pour nos contrats",
    "title": "Contrôle d'accès, badges et interphones pour copropriétés | Aperio Accès",
    "desc": "Aperio Accès équipe copropriétés et entreprises en Île-de-France : interphones et visiophones, badges Vigik, contrôle d'accès, serrures électroniques. Audit gratuit, maintenance et astreinte 24 h/24.",
    "fonts": ("Chakra Petch", "Chakra+Petch:wght@600;700", "Manrope", "Manrope:wght@400;500;600;700"),
    "pal": dict(paper="#F5F7FB", chalk="#E6ECF6", ink="#0A0E14", muted="#515B68", line="#D4DCE8", accent="#4C93FF", deep="#1557C9"),
    "layout": "split-right",
    "icon": LOCK,
    "eyebrow": "Contrôle d'accès · Copropriétés et entreprises",
    "h1": ("Des accès qui fonctionnent,", "des badges que vous gérez en deux clics."),
    "lead": "Interphone en panne, badges perdus qu'on ne peut pas désactiver, prestataire injoignable ? Nous installons et entretenons l'interphonie et le contrôle d'accès de votre immeuble ou de vos locaux, avec une astreinte 24 h/24.",
    "proofs": ["Audit gratuit de vos accès", "Badges désactivables à distance en cas de perte", "Maintenance et astreinte 24 h/24 sous contrat"],
    "cta": "Demander un audit gratuit", "note": "Réponse sous 24 h ouvrées. Syndics et gestionnaires bienvenus.",
    "badge": ("24 h/24", "astreinte pour les<br>immeubles sous contrat"),
    "alt": "Une personne compose un code sur l'interphone d'un immeuble",
    "sit_title": "Où en êtes-vous ?",
    "sits": [
      ("L'interphone de notre immeuble est en panne", "Dépannage, puis remplacement par un visiophone si nécessaire.", "Interphone en panne"),
      ("On ne sait plus combien de badges circulent", "Inventaire, désactivation des badges perdus, nouveau système gérable en ligne.", "Gestion des badges"),
      ("Le facteur ne peut pas entrer", "Mise en place du Vigik pour La Poste et les services autorisés.", "Accès Vigik"),
      ("Nous voulons un visiophone", "Voir qui sonne et ouvrir depuis son téléphone.", "Visiophone"),
      ("Nos bureaux ont besoin d'accès par badge", "Contrôle d'accès par zones et horaires, historique des passages.", "Contrôle d'accès entreprise"),
      ("Notre prestataire ne répond plus", "Reprise de la maintenance de votre installation existante.", "Reprise de maintenance"),
    ],
    "serv_eyebrow": "Nos solutions", "serv_h2": "Les accès de votre immeuble ou de vos locaux, entretenus et maîtrisés.",
    "servs": [
      ("Interphones et visiophones", "Platines de rue, combinés ou application mobile, adaptés au nombre de logements."),
      ("Badges et Vigik", "Badges résidents, accès Vigik pour La Poste et les services, programmation à distance."),
      ("Contrôle d'accès", "Accès par zones et plages horaires pour bureaux, parkings et locaux techniques."),
      ("Serrures électroniques", "Serrures à badge ou à code pour portes de locaux, sans changer toute la porte."),
      ("Maintenance et astreinte", "Visites préventives et intervention 24 h/24 sous contrat."),
      ("Audit et mise aux normes", "État des lieux de vos accès et plan de remplacement chiffré."),
    ],
    "steps_h2": "Un projet mené sans perturber les résidents.",
    "steps": [
      ("Prise de contact", "Syndic, conseil syndical ou entreprise : vous nous décrivez l'existant."),
      ("Audit sur place", "Relevé des portes, du câblage et des besoins, rapport remis."),
      ("Proposition chiffrée", "Solution, planning et contrat de maintenance, prêts pour l'assemblée générale."),
      ("Installation et formation", "Pose planifiée, badges programmés, gestionnaire formé."),
    ],
    "job_labels": ("Installation", "Durée"),
    "jobs": [
      ("Paris 12e · Copropriété de 40 lots", "Visiophone et badges gérés en ligne", "Remplacement complet", "3 jours"),
      ("Boulogne-Billancourt · Bureaux", "Contrôle d'accès sur 3 étages et parking", "Badges par zones", "5 jours"),
      ("Montreuil · Résidence", "Vigik installé, fin des sonneries pour le courrier", "Accès Vigik", "1 jour"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Des systèmes ouverts.", "Vous n'êtes pas prisonnier d'un prestataire : les accès restent les vôtres."),
      ("Une astreinte réelle.", "Un technicien joignable 24 h/24 pour les installations sous contrat."),
      ("Des données protégées.", "Historiques d'accès conservés selon la réglementation, accès limité au gestionnaire."),
      ("Des devis prêts pour l'AG.", "Documents clairs pour faciliter le vote en assemblée générale."),
    ],
    "reviews": [
      ("« Nous ne savions plus qui avait des badges. Tout est maintenant visible en ligne, et on désactive un badge perdu en deux clics. »", "Conseil syndical · Paris 12e · Copropriété"),
      ("« Installation faite sans bloquer nos équipes, et une vraie astreinte le week-end. »", "Responsable des services généraux · Boulogne-Billancourt"),
    ],
    "faq": [
      ("Qu'est-ce que le Vigik ?", "Un système qui permet à La Poste et à certains services autorisés d'accéder aux parties communes sans donner de code, avec des droits limités dans le temps."),
      ("Peut-on désactiver un badge perdu ?", "Oui, avec nos systèmes gérés en ligne, le gestionnaire désactive un badge en quelques secondes."),
      ("Faut-il un vote en assemblée générale ?", "Pour le remplacement de l'interphonie ou du contrôle d'accès en copropriété, généralement oui. Nous fournissons des documents prêts pour l'AG."),
      ("Reprenez-vous une installation existante ?", "Oui, dans la plupart des cas. L'audit indique ce qui peut être conservé."),
      ("Que comprend l'astreinte ?", "Un technicien joignable 24 h/24 pour les pannes bloquantes des installations sous contrat de maintenance."),
      ("Les résidents peuvent-ils ouvrir depuis leur téléphone ?", "Oui, avec un visiophone connecté, chaque résident peut voir le visiteur et ouvrir depuis une application."),
    ],
    "quote_h2": "Parlez-nous de vos accès.", "quote_p": "Syndic, conseil syndical ou entreprise : décrivez-nous votre immeuble ou vos locaux. On vous rappelle pour fixer l'audit.",
    "work_label": "Votre besoin",
    "works": ["Interphone en panne", "Gestion des badges", "Accès Vigik", "Visiophone", "Contrôle d'accès entreprise", "Reprise de maintenance", "Autre"],
    "extra": ("size", "Nombre de lots ou de salariés", "Ex. : 40 logements", True),
    "details_ph": "Ex. : immeuble de 1975, interphone d'origine, badges distribués sans suivi",
    "success_end": "fixer l'audit de vos accès",
    "nav": ["Nos solutions", "Comment ça se passe", "Réalisations", "Questions"],
  },
]
