"""Taxis et chauffeurs : 5 marques refaites au format orienté client (septembre 2026)."""

CAR = '<path class="blade" d="M5 20l2.5-6.5C8 12 9.2 11 10.8 11h10.4c1.6 0 2.8 1 3.3 2.5L27 20z"/><path d="M4 20h24v4H4z" fill="none" stroke="currentColor" stroke-width="2.2"/><circle cx="10" cy="24.5" r="2.2" fill="currentColor"/><circle cx="22" cy="24.5" r="2.2" fill="currentColor"/>'
SIGN = '<rect class="blade" x="11" y="4" width="10" height="5" rx="1"/><path d="M5 22l2.5-7C8 13.5 9.2 12.5 10.8 12.5h10.4c1.6 0 2.8 1 3.3 2.5L27 22v4H5z" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linejoin="round"/>'

NAV = ["Nos trajets", "Comment ça se passe", "Trajets", "Questions"]

SITES = [
  {
    "dir": "taxis/01-onyx-chauffeur",
    "seo_h1": "Chauffeur privé VTC à Paris : aéroports, affaires, soirées",
    "founder": ("Alexandre Nguyen", "fondateur, chauffeur depuis 2012"),
    "photo": ("36377051", "professional-chauffeur-standing-beside-luxury-suv-36377051", "Charlotte Black Car Service"),
    "name": "Onyx Chauffeurs", "tagline": "Chauffeur privé · Paris",
    "schema": "TaxiService",
    "city": "Paris", "cp": "75008", "street": "34 avenue George V",
    "phone": "06 39 98 12 40", "tel": "+33639981240",
    "hours": "Sur réservation, 24 h/24", "hours_schema": "Mo-Su 00:00-23:59",
    "zone_short": "Paris, aéroports et gares",
    "zone": ["Paris", "Aéroport Paris-Charles de Gaulle", "Aéroport Paris-Orly", "Aéroport de Beauvais", "La Défense", "Versailles", "Disneyland Paris"],
    "top3": "Prix fixe confirmé à la réservation",
    "form": "taxi",
    "title": "Chauffeur privé VTC à Paris · Aéroports, affaires, événements | Onyx Chauffeurs",
    "desc": "Onyx Chauffeurs, chauffeurs privés à Paris : transferts vers Roissy-CDG et Orly, mises à disposition pour rendez-vous d'affaires et soirées. Berlines et vans noirs, prix fixe confirmé à la réservation.",
    "fonts": ("Marcellus", "Marcellus", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F6F5F2", chalk="#EAE8E3", ink="#0A0A0A", muted="#5A5854", line="#DAD7D0", accent="#C9A24B", deep="#856515"),
    "layout": "expand",
    "icon": CAR,
    "eyebrow": "Chauffeur privé · Paris",
    "h1": ("Votre chauffeur vous attend à l'arrivée,", "votre nom sur la tablette, sans compteur qui tourne."),
    "lead": "Transferts aéroport, rendez-vous d'affaires, soirées : un chauffeur en costume, une berline ou un van noir, et un prix fixe confirmé dès la réservation. Suivi de votre vol inclus, attente offerte en cas de retard.",
    "proofs": ["Prix fixe confirmé par écrit à la réservation", "Suivi de vol : le chauffeur s'adapte à votre retard", "Eau, chargeurs et Wi-Fi à bord"],
    "cta": "Réserver un chauffeur", "note": "Confirmation par SMS et e-mail en moins de 15 minutes.",
    "badge": ("60 min", "d'attente offerte<br>à l'arrivée de votre vol"),
    "alt": "Un chauffeur en costume attend à côté d'un SUV noir",
    "sit_title": "Où allez-vous ?",
    "sits": [
      ("J'arrive à Roissy ou à Orly", "Accueil en zone d'arrivée avec pancarte, bagages pris en charge.", "Transfert aéroport"),
      ("J'ai un train à prendre", "Prise en charge à l'heure, dépose au plus près du quai.", "Transfert gare"),
      ("J'enchaîne plusieurs rendez-vous", "Mise à disposition à l'heure, le chauffeur vous attend entre chaque arrêt.", "Mise à disposition"),
      ("J'organise un événement", "Plusieurs véhicules coordonnés pour vos invités.", "Événement"),
      ("Je reçois des clients étrangers", "Chauffeurs anglophones, accueil personnalisé.", "Accueil de clients"),
      ("Je vais à Versailles ou en Normandie", "Trajets longue distance avec arrêts à la demande.", "Longue distance"),
    ],
    "serv_eyebrow": "Nos trajets", "serv_h2": "Un chauffeur privé pour chaque déplacement qui compte.",
    "servs": [
      ("Transferts aéroports", "Roissy-CDG, Orly, Beauvais : suivi du vol en temps réel et accueil en zone d'arrivée."),
      ("Transferts gares", "Gare de Lyon, Gare du Nord, Montparnasse : prise en charge ponctuelle, aide aux bagages."),
      ("Mise à disposition", "Un chauffeur et une voiture à l'heure ou à la journée pour vos rendez-vous."),
      ("Événements et mariages", "Plusieurs véhicules coordonnés, chauffeurs en tenue."),
      ("Clientèle d'affaires", "Compte entreprise, facturation mensuelle, chauffeurs anglophones."),
      ("Longues distances", "Châteaux de la Loire, Normandie, Champagne : prix fixe pour le trajet complet."),
    ],
    "steps_h2": "Réserver prend deux minutes. Le reste, on s'en occupe.",
    "steps": [
      ("Vous réservez", "Formulaire, téléphone ou SMS : départ, destination, date et heure."),
      ("Prix confirmé", "Vous recevez le prix fixe et la confirmation en moins de 15 minutes."),
      ("Chauffeur annoncé", "La veille, le nom du chauffeur, le modèle et la plaque du véhicule."),
      ("Vous êtes accueilli", "Pancarte à votre nom, bagages pris en charge, trajet au calme."),
    ],
    "job_labels": ("Trajet", "Véhicule"),
    "jobs": [
      ("Roissy-CDG · Vol retardé de 2 h", "Accueil d'un dirigeant à 23 h, attente sans supplément", "Transfert aéroport", "Berline"),
      ("Paris 8e · Journée de rendez-vous", "Six rendez-vous dans Paris et La Défense", "Mise à disposition 8 h", "Berline"),
      ("Versailles · Mariage", "Trois vans pour les invités entre l'hôtel et le château", "Événement", "3 vans"),
    ],
    "pledges_h2": "Ce que vous pouvez attendre de nous.",
    "pledges": [
      ("Un prix fixe.", "Le prix confirmé à la réservation ne change pas, même dans les bouchons."),
      ("La ponctualité.", "Le chauffeur est sur place 10 minutes avant l'heure prévue."),
      ("La discrétion.", "Vos conversations et vos déplacements restent confidentiels."),
      ("Des chauffeurs professionnels.", "Titulaires de la carte VTC, en costume, véhicules récents."),
    ],
    "reviews": [
      ("« Vol arrivé avec deux heures de retard, le chauffeur était là avec la pancarte, sans le moindre supplément. »", "Caroline B. · Roissy-CDG · Transfert aéroport"),
      ("« Nous l'utilisons pour tous nos clients étrangers. Toujours à l'heure, et des chauffeurs qui parlent anglais. »", "Office manager · Paris 8e · Compte entreprise"),
    ],
    "faq": [
      ("Combien coûte un VTC pour l'aéroport de Roissy ?", "Le prix dépend de l'adresse de départ, de l'heure et du véhicule choisi. Il est fixe et confirmé par écrit à la réservation, sans compteur ni supplément pour les embouteillages."),
      ("Que se passe-t-il si mon vol est en retard ?", "Nous suivons votre vol en temps réel. Le chauffeur adapte son arrivée, et les 60 premières minutes d'attente après l'atterrissage sont offertes."),
      ("Peut-on vous héler dans la rue ?", "Non. Comme tous les VTC, nous travaillons uniquement sur réservation préalable. C'est ce qui nous permet de garantir le prix et le véhicule."),
      ("Quelle différence entre un VTC et un taxi ?", "Le taxi peut être hélé et roule au compteur, avec des forfaits réglementés pour les aéroports parisiens. Le VTC travaille sur réservation avec un prix fixé à l'avance et un service personnalisé."),
      ("Proposez-vous un compte entreprise ?", "Oui, avec facturation mensuelle, suivi des trajets par collaborateur et réservation par e-mail."),
      ("Vos véhicules acceptent-ils les sièges enfant ?", "Oui, sur demande à la réservation, sans supplément."),
    ],
    "quote_h2": "Réservez votre chauffeur.", "quote_p": "Indiquez votre trajet. Vous recevez le prix fixe et la confirmation par SMS en moins de 15 minutes.",
    "work_label": "Type de trajet",
    "works": ["Transfert aéroport", "Transfert gare", "Mise à disposition", "Événement", "Accueil de clients", "Longue distance"],
    "extra": ("flight", "Numéro de vol ou de train", "Ex. : AF1234", True),
    "to_ph": "Ex. : Roissy-CDG terminal 2E",
    "details_label": "Informations utiles",
    "details_ph": "Ex. : 3 valises, un siège enfant, arrêt rapide à l'hôtel",
    "success": "Merci {first}. Votre demande est enregistrée : vous recevez le prix fixe et la confirmation par SMS dans les 15 minutes.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "taxis/02-vector-taxi",
    "seo_h1": "Taxi à Marseille à prix fixe : aéroport, gare Saint-Charles, croisières",
    "founder": ("Sofiane Belkacem", "gérant, chauffeur de taxi"),
    "photo": ("36377043", "professional-chauffeur-loading-luggage-into-sedan-36377043", "Charlotte Black Car Service"),
    "name": "Vecteur Taxi", "tagline": "Taxi à prix fixe · Marseille",
    "schema": "TaxiService",
    "city": "Marseille", "cp": "13002", "street": "12 boulevard des Dames",
    "phone": "06 39 98 27 15", "tel": "+33639982715",
    "hours": "24 h/24, 7 j/7", "hours_schema": "Mo-Su 00:00-23:59",
    "zone_short": "Marseille, aéroport et gares",
    "zone": ["Marseille", "Aéroport Marseille-Provence", "Gare Saint-Charles", "Gare d'Aix-en-Provence TGV", "Terminal croisières", "Aix-en-Provence", "Cassis", "La Ciotat"],
    "top3": "Prix fixe annoncé avant de monter",
    "form": "taxi",
    "title": "Taxi Marseille prix fixe · Aéroport, gare, croisières | Vecteur Taxi",
    "desc": "Vecteur Taxi à Marseille : trajets à prix fixe vers l'aéroport Marseille-Provence, la gare Saint-Charles, Aix TGV et le terminal croisières. Prix annoncé avant le départ, paiement par carte.",
    "fonts": ("Archivo", "Archivo:wght@600;700;800", "Figtree", "Figtree:wght@400;500;600"),
    "pal": dict(paper="#FAF9F4", chalk="#F0EDE0", ink="#101216", muted="#5A5D63", line="#E0DDD0", accent="#E4C04A", deep="#8A6D0A"),
    "layout": "split-right",
    "icon": SIGN,
    "eyebrow": "Taxi à prix fixe · Marseille",
    "h1": ("Aéroport, gare, port :", "le prix est annoncé avant de monter, pas à l'arrivée."),
    "lead": "Réservez votre taxi pour Marignane, Saint-Charles, Aix TGV ou le terminal croisières : vous connaissez le prix fixe à la réservation, bagages compris. Paiement par carte à bord.",
    "proofs": ["Prix fixe annoncé à la réservation", "Bagages et attente courte inclus", "Carte bancaire acceptée dans tous nos taxis"],
    "cta": "Connaître mon prix", "note": "Réponse en moins de 10 minutes, de jour comme de nuit.",
    "badge": ("0 €", "de supplément bagages<br>sur nos trajets à prix fixe"),
    "alt": "Un chauffeur charge des bagages dans le coffre d'une berline",
    "sit_title": "Où devez-vous aller ?",
    "sits": [
      ("Je prends l'avion à Marignane", "Prix fixe depuis votre adresse, chauffeur à l'heure.", "Aéroport Marseille-Provence"),
      ("Mon train part de Saint-Charles", "Dépose au dépose-minute, sans chercher à se garer.", "Gare Saint-Charles"),
      ("Je rejoins Aix TGV", "Trajet à prix fixe, marge prévue pour les bouchons.", "Gare Aix-en-Provence TGV"),
      ("J'embarque pour une croisière", "Prise en charge à l'hôtel ou à la gare, valises comprises.", "Terminal croisières"),
      ("Je vais à Cassis ou à La Ciotat", "Prix annoncé pour le trajet complet.", "Cassis, La Ciotat"),
      ("Il me faut un taxi maintenant", "Appelez-nous : le plus proche arrive.", "Course immédiate"),
    ],
    "serv_eyebrow": "Nos trajets", "serv_h2": "Les trajets les plus demandés, à prix fixe.",
    "servs": [
      ("Aéroport Marseille-Provence", "Depuis Marseille et les communes voisines, dans les deux sens, prix fixe par zone."),
      ("Gares", "Saint-Charles, Aix-en-Provence TGV, Blancarde : ponctualité garantie avant votre train."),
      ("Terminal croisières", "Transferts entre hôtel, gare, aéroport et port, avec les bagages."),
      ("Courses en ville", "Réservation ou course immédiate, au compteur ou prix fixe annoncé."),
      ("Excursions", "Cassis, calanques, Aix, Luberon : prix fixe pour la journée ou le trajet."),
      ("Comptes entreprise", "Facturation mensuelle pour les entreprises et les hôtels."),
    ],
    "steps_h2": "Un taxi réservé en deux minutes, sans calcul à faire.",
    "steps": [
      ("Vous indiquez le trajet", "Départ, destination, date, heure et nombre de passagers."),
      ("Prix fixe annoncé", "Vous recevez le prix par SMS. Vous validez, c'est réservé."),
      ("Le taxi est là", "SMS avec le numéro du taxi 15 minutes avant la prise en charge."),
      ("Vous payez comme vous voulez", "Carte, sans contact ou espèces, facture sur demande."),
    ],
    "job_labels": ("Trajet", "Durée"),
    "jobs": [
      ("Marseille 8e → Aéroport", "Famille de 4 avec valises, départ à 5 h", "Aéroport Marseille-Provence", "35 min"),
      ("Gare Saint-Charles → Terminal croisières", "Couple avec bagages, correspondance serrée", "Croisière", "20 min"),
      ("Aix-en-Provence → Aix TGV", "Cadre en déplacement, reçu envoyé par e-mail", "Gare TGV", "15 min"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Le prix d'abord.", "Annoncé à la réservation, jamais recalculé à l'arrivée."),
      ("La carte bancaire partout.", "Tous nos taxis acceptent la carte et le sans contact."),
      ("La ponctualité.", "SMS 15 minutes avant, chauffeur sur place à l'heure."),
      ("Des taxis officiels.", "Taxis autorisés, chauffeurs titulaires de la carte professionnelle."),
    ],
    "reviews": [
      ("« Prix annoncé par SMS la veille, exactement celui payé le lendemain. Enfin un taxi pour l'aéroport sans mauvaise surprise. »", "Nathalie C. · Marseille 8e · Aéroport"),
      ("« Taxi réservé pour notre croisière, chauffeur ponctuel et adorable avec les enfants. »", "Famille D. · Terminal croisières"),
    ],
    "faq": [
      ("Combien coûte un taxi de Marseille à l'aéroport ?", "Le prix dépend de votre adresse de départ et de l'heure. Nous vous l'annonçons à la réservation et il ne change pas, bagages compris."),
      ("Peut-on payer par carte ?", "Oui, tous nos taxis acceptent la carte bancaire et le sans contact. Une facture peut vous être envoyée par e-mail."),
      ("Faut-il réserver à l'avance ?", "C'est conseillé pour l'aéroport et les gares, surtout tôt le matin. Pour une course immédiate, appelez-nous directement."),
      ("Combien de passagers et de bagages ?", "Jusqu'à 4 passagers en berline et 7 en van. Précisez le nombre de valises à la réservation."),
      ("Que se passe-t-il si mon train a du retard ?", "Donnez-nous le numéro du train : le chauffeur adapte son heure d'arrivée."),
      ("Faites-vous les excursions dans les calanques ?", "Oui, nous déposons et reprenons les visiteurs aux accès des calanques, avec un prix fixe annoncé."),
    ],
    "quote_h2": "Réservez votre taxi.", "quote_p": "Indiquez votre trajet : vous recevez le prix fixe par SMS en moins de 10 minutes.",
    "work_label": "Type de trajet",
    "works": ["Aéroport Marseille-Provence", "Gare Saint-Charles", "Gare Aix-en-Provence TGV", "Terminal croisières", "Cassis, La Ciotat", "Course en ville"],
    "extra": ("luggage", "Nombre de valises", "Ex. : 2 grandes, 1 cabine", True),
    "to_ph": "Ex. : aéroport Marseille-Provence",
    "details_label": "Informations utiles",
    "details_ph": "Ex. : numéro de vol, siège enfant, poussette",
    "success": "Merci {first}. Vous recevez le prix fixe de votre trajet par SMS dans les 10 minutes.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "taxis/03-checker-cab",
    "seo_h1": "Taxi conventionné à Bordeaux depuis 1947 : transport médical et courses",
    "founder": ("Jean-Marc Dubreuil", "gérant, troisième génération"),
    "photo": ("15487495", "back-view-of-a-man-driving-a-car-15487495", "Airamd Photo"),
    "name": "Taxis Damier", "tagline": "Taxi conventionné depuis 1947 · Bordeaux",
    "schema": "TaxiService",
    "city": "Bordeaux", "cp": "33000", "street": "5 cours de la Somme",
    "phone": "05 36 49 33 10", "tel": "+33536493310",
    "hours": "24 h/24, 7 j/7", "hours_schema": "Mo-Su 00:00-23:59",
    "zone_short": "Bordeaux Métropole",
    "zone": ["Bordeaux", "Mérignac", "Pessac", "Talence", "Bègles", "Le Bouscat", "Cenon", "Lormont", "CHU Pellegrin", "Aéroport de Bordeaux-Mérignac"],
    "top3": "Conventionné Assurance maladie",
    "form": "taxi",
    "title": "Taxi conventionné à Bordeaux · Transport médical, hôpitaux, gare | Taxis Damier",
    "desc": "Taxis Damier, taxis bordelais depuis 1947 : transport médical conventionné sans avance de frais, trajets vers le CHU, les cliniques, la gare Saint-Jean et l'aéroport. Réservation 24 h/24.",
    "fonts": ("DM Serif Display", "DM+Serif+Display", "Karla", "Karla:wght@400;500;600;700"),
    "pal": dict(paper="#FBFAF6", chalk="#F1EEE4", ink="#111111", muted="#5C5C5C", line="#E0DDD4", accent="#F2C200", deep="#806400"),
    "layout": "split-left",
    "icon": SIGN,
    "eyebrow": "Taxi conventionné · Bordeaux",
    "h1": ("Vos rendez-vous médicaux,", "sans avancer les frais ni chercher à vous garer."),
    "lead": "Taxis conventionnés par l'Assurance maladie : avec une prescription médicale de transport, vous n'avancez rien dans la plupart des cas. Le même chauffeur pour vos séances régulières, et toutes vos courses à Bordeaux depuis 1947.",
    "proofs": ["Transport médical sans avance de frais le plus souvent", "Le même chauffeur pour vos séances régulières", "Aide à la montée et à la descente du véhicule"],
    "cta": "Réserver un transport", "note": "Pensez à votre prescription de transport et à votre carte Vitale.",
    "badge": ("1947", "trois générations<br>de taxis bordelais"),
    "alt": "Un chauffeur de taxi au volant, en route vers un rendez-vous",
    "sit_title": "Pour quel trajet ?",
    "sits": [
      ("J'ai des séances régulières (dialyse, chimio, radiothérapie)", "Le même chauffeur, aux mêmes horaires, pris en charge par l'Assurance maladie.", "Séances régulières"),
      ("J'ai une consultation à l'hôpital", "Dépose à l'entrée du service, attente ou retour organisé.", "Consultation à l'hôpital"),
      ("Je sors d'une hospitalisation", "Retour à domicile avec aide pour les bagages.", "Sortie d'hospitalisation"),
      ("Je dois prendre un train à Saint-Jean", "Prise en charge à l'heure, aide pour les valises.", "Gare Saint-Jean"),
      ("Je vais à l'aéroport de Mérignac", "Réservation la veille, départ garanti même très tôt.", "Aéroport de Mérignac"),
      ("J'ai une course à faire en ville", "Réservation ou course immédiate.", "Course en ville"),
    ],
    "serv_eyebrow": "Nos trajets", "serv_h2": "Le taxi de confiance des Bordelais, pour les soins comme pour le reste.",
    "servs": [
      ("Transport médical conventionné", "Consultations, examens, hospitalisations : sur prescription, avec tiers payant le plus souvent."),
      ("Séances régulières", "Dialyse, chimiothérapie, radiothérapie, rééducation : un chauffeur attitré, des horaires fixes."),
      ("Entrées et sorties d'hôpital", "CHU Pellegrin, Haut-Lévêque, Saint-André, cliniques : dépose au plus près du service."),
      ("Gares et aéroport", "Saint-Jean et Mérignac, réservation conseillée la veille."),
      ("Courses en ville", "Au compteur, avec paiement par carte à bord."),
      ("Personnes à mobilité réduite", "Aide à la montée, fauteuil pliant transporté, patience garantie."),
    ],
    "steps_h2": "Un transport médical sans paperasse inutile.",
    "steps": [
      ("Vous réservez", "Par téléphone ou formulaire, avec la date et l'adresse du rendez-vous."),
      ("Vous préparez vos papiers", "Prescription médicale de transport, carte Vitale, et justificatif de mutuelle si vous en avez."),
      ("Le chauffeur vient vous chercher", "À l'heure, avec aide pour monter en voiture si besoin."),
      ("Rien à avancer", "Nous nous occupons de la facturation à l'Assurance maladie dans la plupart des cas."),
    ],
    "job_labels": ("Trajet", "Fréquence"),
    "jobs": [
      ("Talence → CHU Pellegrin", "Séances de dialyse, même chauffeur depuis deux ans", "Séances régulières", "3 fois par semaine"),
      ("Bordeaux Caudéran → Clinique", "Sortie d'hospitalisation avec valise et déambulateur", "Retour à domicile", "Ponctuel"),
      ("Le Bouscat → Gare Saint-Jean", "Départ à 6 h pour un TGV, réservé la veille", "Gare", "Ponctuel"),
    ],
    "pledges_h2": "Ce qui fait notre réputation depuis 1947.",
    "pledges": [
      ("La patience.", "On ne vous presse jamais, surtout à la sortie d'un soin."),
      ("La régularité.", "Pour vos séances, le même chauffeur autant que possible."),
      ("La transparence.", "Vous savez ce qui est pris en charge et ce qui reste éventuellement à votre charge."),
      ("La disponibilité.", "Réservation 24 h/24, 7 j/7."),
    ],
    "reviews": [
      ("« Pour mes séances de dialyse, c'est toujours Marc qui vient. Ponctuel, attentionné, et je n'avance jamais rien. »", "Josette L. · Talence · Séances régulières"),
      ("« Taxi réservé à 5 h pour la gare, chauffeur là à 4 h 55. Comme d'habitude avec eux. »", "Pierre-Yves M. · Le Bouscat · Gare Saint-Jean"),
    ],
    "faq": [
      ("Qu'est-ce qu'un taxi conventionné ?", "Un taxi qui a signé une convention avec l'Assurance maladie pour transporter des patients sur prescription médicale. Le transport peut alors être pris en charge, souvent sans avance de frais grâce au tiers payant."),
      ("Quels documents faut-il pour un transport médical ?", "La prescription médicale de transport remplie par votre médecin, votre carte Vitale, et votre attestation de mutuelle ou de prise en charge à 100 % si vous en avez une."),
      ("Le transport médical est-il remboursé à 100 % ?", "Cela dépend de votre situation : affection de longue durée, hospitalisation, accident du travail, etc. Nous vous indiquons avant le trajet ce qui reste éventuellement à votre charge."),
      ("Puis-je avoir le même chauffeur pour mes séances ?", "Oui, nous organisons un chauffeur attitré autant que possible pour les séances régulières."),
      ("Transportez-vous les fauteuils roulants ?", "Nous transportons les fauteuils pliants et aidons à la montée. Pour un transport en fauteuil non pliant, il faut un véhicule adapté que nous pouvons vous indiquer."),
      ("Faites-vous aussi les courses classiques ?", "Oui, en ville, vers la gare et l'aéroport, 24 h/24, avec paiement par carte à bord."),
    ],
    "quote_h2": "Réservez votre transport.", "quote_p": "Indiquez le trajet et l'heure du rendez-vous. On vous rappelle pour confirmer et vérifier la prise en charge.",
    "work_label": "Type de trajet",
    "works": ["Séances régulières", "Consultation à l'hôpital", "Sortie d'hospitalisation", "Gare Saint-Jean", "Aéroport de Mérignac", "Course en ville"],
    "extra": ("prescription", "Prescription de transport", "Ex. : oui, bon de transport", True),
    "to_ph": "Ex. : CHU Pellegrin, service de radiologie",
    "details_label": "Informations utiles",
    "details_ph": "Ex. : j'ai un déambulateur, rendez-vous à 10 h 30, retour à prévoir",
    "success": "Merci {first}. Nous vous rappelons pour confirmer votre transport et vérifier la prise en charge.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "taxis/04-lumen-ride",
    "seo_h1": "Taxi pour seniors et trajets longue distance à Tours",
    "founder": ("Isabelle Moreau", "fondatrice, chauffeuse de taxi"),
    "photo": ("4406040", "a-woman-sitting-inside-a-car-4406040", "Zura Modebadze"),
    "name": "Lumen Trajets", "tagline": "Taxi calme et accompagnement · Tours",
    "schema": "TaxiService",
    "city": "Tours", "cp": "37000", "street": "18 rue Nationale",
    "phone": "02 61 91 84 57", "tel": "+33261918457",
    "hours": "Du lundi au samedi, 6 h à 22 h", "hours_schema": "Mo-Sa 06:00-22:00",
    "zone_short": "Tours et Indre-et-Loire",
    "zone": ["Tours", "Joué-lès-Tours", "Saint-Cyr-sur-Loire", "Saint-Avertin", "Chambray-lès-Tours", "Amboise", "Gare de Saint-Pierre-des-Corps", "Aéroport de Tours"],
    "top3": "Accompagnement porte à porte",
    "form": "taxi",
    "title": "Taxi pour seniors et longue distance à Tours · Accompagnement porte à porte | Lumen Trajets",
    "desc": "Lumen Trajets, taxi à Tours pour les personnes âgées et les trajets qui demandent du calme : accompagnement porte à porte, aide aux bagages, trajets longue distance vers Paris, Nantes et les aéroports.",
    "fonts": ("Quicksand", "Quicksand:wght@600;700", "Karla", "Karla:wght@400;500;600"),
    "pal": dict(paper="#F7F4EF", chalk="#EDE6DB", ink="#243B55", muted="#5B6778", line="#DFD6C8", accent="#E9A857", deep="#9A5F12"),
    "layout": "overlay",
    "icon": CAR,
    "eyebrow": "Taxi calme · Tours",
    "h1": ("Un trajet sans stress pour vos parents,", "et un message pour vous dire qu'ils sont bien arrivés."),
    "lead": "Nous accompagnons les personnes âgées de la porte de chez elles jusqu'à la salle d'attente, à leur rythme. Vous, leurs proches, recevez un SMS à la prise en charge et à l'arrivée. Et pour les longs trajets, la même douceur jusqu'à Paris ou l'aéroport.",
    "proofs": ["Accompagnement de porte à porte, à leur rythme", "SMS aux proches à la prise en charge et à l'arrivée", "Conduite souple, voiture silencieuse"],
    "cta": "Réserver un trajet", "note": "Vous pouvez réserver pour un proche et payer à sa place.",
    "badge": ("2 SMS", "pour les proches : départ<br>et arrivée confirmés"),
    "alt": "Une passagère détendue sur la banquette arrière d'une voiture",
    "sit_title": "Pour qui réservez-vous ?",
    "sits": [
      ("Pour mon père ou ma mère âgé(e)", "Accompagnement porte à porte, SMS aux proches.", "Accompagnement d'un proche"),
      ("Pour un rendez-vous chez le médecin", "Dépose et reprise à l'heure, attente possible.", "Rendez-vous médical"),
      ("Pour aller voir la famille à Paris ou Nantes", "Trajet longue distance à prix fixe, pauses à la demande.", "Longue distance"),
      ("Pour prendre un train à Saint-Pierre-des-Corps", "Aide aux bagages jusqu'au quai.", "Gare"),
      ("Pour une sortie (courses, coiffeur, cimetière)", "Aller, attente et retour, sans se presser.", "Sortie accompagnée"),
      ("Pour une sortie d'hôpital", "Retour au domicile, installation, bagages portés.", "Sortie d'hôpital"),
    ],
    "serv_eyebrow": "Nos trajets", "serv_h2": "Des trajets pensés pour ceux qui n'aiment pas être pressés.",
    "servs": [
      ("Accompagnement porte à porte", "Le chauffeur vient à la porte, aide à descendre l'escalier, accompagne jusqu'à l'accueil."),
      ("Rendez-vous médicaux", "Dépose, attente en salle si souhaité, retour à domicile."),
      ("Longues distances", "Paris, Nantes, Orléans, aéroports parisiens : prix fixe, pauses quand vous le souhaitez."),
      ("Sorties du quotidien", "Courses, coiffeur, visites familiales : aller, attente et retour."),
      ("Réservation par les proches", "Vous réservez et payez pour votre parent, vous recevez les SMS de suivi."),
      ("Abonnements réguliers", "Un créneau fixe chaque semaine avec le même chauffeur."),
    ],
    "steps_h2": "Rassurant pour eux, simple pour vous.",
    "steps": [
      ("Vous réservez", "Pour vous ou pour un proche, par téléphone ou formulaire."),
      ("On confirme les détails", "Étage, ascenseur, aides à la marche : on prévoit tout."),
      ("Le chauffeur accompagne", "De la porte à la destination, sans précipitation."),
      ("Les proches sont prévenus", "Un SMS au départ, un SMS à l'arrivée."),
    ],
    "job_labels": ("Trajet", "Durée"),
    "jobs": [
      ("Tours → Cabinet de cardiologie", "Dame de 89 ans accompagnée jusqu'à la salle d'attente", "Rendez-vous médical", "2 h avec attente"),
      ("Joué-lès-Tours → Paris 15e", "Visite familiale, deux pauses sur l'autoroute", "Longue distance", "3 h"),
      ("Saint-Avertin → Coiffeur et marché", "Sortie hebdomadaire, même chauffeur chaque jeudi", "Abonnement", "Chaque semaine"),
    ],
    "pledges_h2": "Nos promesses.",
    "pledges": [
      ("Prendre le temps.", "Personne n'est jamais pressé de monter ou de descendre."),
      ("Informer les proches.", "Départ et arrivée confirmés par SMS à qui vous voulez."),
      ("Un prix clair.", "Prix annoncé à la réservation, attente comprise quand elle est prévue."),
      ("La même personne.", "Pour les trajets réguliers, le même chauffeur autant que possible."),
    ],
    "reviews": [
      ("« J'habite à Lyon, ma mère à Tours. Je reçois un SMS quand elle part et quand elle arrive. Ça change tout. »", "Véronique T. · Lyon · Accompagnement d'un proche"),
      ("« Trajet jusqu'à Paris avec deux pauses, sans jamais me sentir bousculé. Chauffeur d'une grande gentillesse. »", "Bernard L. · Joué-lès-Tours · Longue distance"),
    ],
    "faq": [
      ("Pouvez-vous accompagner une personne âgée jusqu'à l'intérieur ?", "Oui, c'est notre spécialité : le chauffeur vient à la porte, aide dans l'escalier et accompagne jusqu'à l'accueil ou la salle d'attente."),
      ("Puis-je réserver et payer pour un parent ?", "Oui. Vous réservez, vous payez par carte à distance et vous recevez les SMS de départ et d'arrivée."),
      ("Faites-vous les trajets vers Paris ou les aéroports ?", "Oui, avec un prix fixe annoncé à la réservation et des pauses quand vous le souhaitez."),
      ("Le chauffeur peut-il attendre pendant le rendez-vous ?", "Oui, l'attente peut être prévue et incluse dans le prix annoncé."),
      ("Transportez-vous les déambulateurs et fauteuils pliants ?", "Oui, ils voyagent dans le coffre sans supplément."),
      ("Êtes-vous conventionnés pour le transport médical ?", "Non, nous sommes un taxi classique. Pour un transport sur prescription avec tiers payant, adressez-vous à un taxi conventionné."),
    ],
    "quote_h2": "Réservez un trajet.", "quote_p": "Pour vous ou pour un proche : indiquez le trajet et ce qu'il faut prévoir. On vous rappelle pour confirmer.",
    "work_label": "Type de trajet",
    "works": ["Accompagnement d'un proche", "Rendez-vous médical", "Longue distance", "Gare", "Sortie accompagnée", "Sortie d'hôpital"],
    "extra": ("notify", "Téléphone du proche à prévenir", "Ex. : 06 12 34 56 78", True),
    "to_ph": "Ex. : cabinet médical, 4 rue de Bordeaux",
    "details_label": "À prévoir",
    "details_ph": "Ex. : 3e étage sans ascenseur, déambulateur, rendez-vous à 14 h",
    "success": "Merci {first}. Nous vous rappelons pour confirmer le trajet et les détails de l'accompagnement.",
    "success_end": "",
    "nav": NAV,
  },
  {
    "dir": "taxis/05-pulse-taxi",
    "seo_h1": "Taxi à Lille 24 h/24 : course immédiate et réservation",
    "founder": ("Romain Delattre", "gérant, chauffeur de taxi"),
    "photo": ("4968417", "taxi-cars-parked-on-city-street-in-downtown-4968417", "Tim Durgan"),
    "name": "Pulse Taxi", "tagline": "Taxi 24 h/24 · Lille",
    "schema": "TaxiService",
    "city": "Lille", "cp": "59800", "street": "3 place des Buisses",
    "phone": "06 39 98 55 03", "tel": "+33639985503",
    "hours": "24 h/24, 7 j/7", "hours_schema": "Mo-Su 00:00-23:59",
    "zone_short": "Lille et métropole",
    "zone": ["Lille", "Roubaix", "Tourcoing", "Villeneuve-d'Ascq", "Marcq-en-Barœul", "Lambersart", "Gare Lille-Flandres", "Gare Lille-Europe", "Aéroport de Lille-Lesquin"],
    "top3": "Un taxi en 10 minutes en moyenne",
    "form": "taxi",
    "urgent": True,
    "title": "Taxi Lille 24h/24 · Course immédiate, gares, aéroport | Pulse Taxi",
    "desc": "Pulse Taxi à Lille, 24 h/24 : un taxi en 10 minutes en moyenne dans Lille, courses vers les gares Lille-Flandres et Lille-Europe, l'aéroport de Lesquin et toute la métropole. Paiement par carte.",
    "fonts": ("Space Grotesk", "Space+Grotesk:wght@500;600;700", "Inter", "Inter:wght@400;500;600"),
    "pal": dict(paper="#F4F7F6", chalk="#E3EDEA", ink="#0A0D12", muted="#515A63", line="#D2DDDA", accent="#00D97E", deep="#00804A"),
    "layout": "split-right",
    "icon": SIGN,
    "eyebrow": "Taxi 24 h/24 · Lille",
    "h1": ("Besoin d'un taxi maintenant ?", "Un appel, et une voiture arrive en 10 minutes en moyenne."),
    "lead": "Jour et nuit, un taxi Pulse est toujours en service dans la métropole lilloise. Appelez pour une course immédiate, ou réservez à l'avance pour la gare, l'aéroport ou une sortie. Paiement par carte dans toutes nos voitures.",
    "proofs": ["Course immédiate, 24 h/24", "SMS avec le numéro du taxi et son heure d'arrivée", "Carte bancaire et sans contact dans tous nos taxis"],
    "cta": "Réserver à l'avance", "note": "Pour tout de suite, appelez : c'est le plus rapide.",
    "badge": ("10 min", "d'attente moyenne<br>dans Lille intra-muros"),
    "alt": "Des taxis avec leur lumineux allumé stationnés dans une rue la nuit",
    "sit_title": "Où allez-vous ?",
    "sits": [
      ("Il me faut un taxi tout de suite", "Appelez : le taxi le plus proche part vers vous.", "Course immédiate"),
      ("J'ai un train à Lille-Flandres ou Lille-Europe", "Réservation conseillée aux heures de pointe.", "Gare"),
      ("Je prends l'avion à Lesquin", "Prise en charge à l'heure, même à 4 h du matin.", "Aéroport de Lille-Lesquin"),
      ("Je rentre de soirée", "Un taxi sûr pour rentrer, sans attendre dans le froid.", "Retour de soirée"),
      ("Je vais à Roubaix ou Tourcoing", "Toute la métropole, au compteur ou prix annoncé.", "Métropole"),
      ("Je dois aller à Bruxelles ou Paris", "Longue distance avec prix annoncé.", "Longue distance"),
    ],
    "serv_eyebrow": "Nos trajets", "serv_h2": "Un taxi quand vous en avez besoin, pas quand ça arrange.",
    "servs": [
      ("Course immédiate", "Un taxi en 10 minutes en moyenne dans Lille, 24 h/24 et 7 j/7."),
      ("Gares", "Lille-Flandres et Lille-Europe : réservation conseillée aux heures de pointe."),
      ("Aéroport de Lille-Lesquin", "Départs très matinaux et retours tardifs, suivi du vol."),
      ("Soirées et retours de nuit", "Un trajet sûr jusqu'à votre porte, le chauffeur attend que vous soyez entré."),
      ("Métropole et longue distance", "Roubaix, Tourcoing, Villeneuve-d'Ascq, mais aussi Bruxelles, Paris ou la côte."),
      ("Entreprises", "Bons de transport, facturation mensuelle pour vos collaborateurs et clients."),
    ],
    "steps_h2": "Un taxi, sans application à installer.",
    "steps": [
      ("Vous appelez ou réservez", "Un appel pour tout de suite, le formulaire pour plus tard."),
      ("Taxi assigné", "Le plus proche de vous part immédiatement."),
      ("SMS de suivi", "Numéro du taxi et heure d'arrivée estimée."),
      ("Paiement simple", "Carte, sans contact ou espèces, reçu par e-mail."),
    ],
    "job_labels": ("Trajet", "Attente"),
    "jobs": [
      ("Vieux-Lille → Gare Lille-Europe", "Course immédiate un lundi à 8 h", "Gare", "7 min"),
      ("Wazemmes → Aéroport de Lesquin", "Réservation pour un départ à 4 h 30", "Aéroport", "Réservé"),
      ("Solférino → Lambersart", "Retour de soirée un samedi à 2 h", "Course de nuit", "9 min"),
    ],
    "pledges_h2": "Nos engagements.",
    "pledges": [
      ("Toujours en service.", "Des taxis disponibles 24 h/24, week-ends et jours fériés."),
      ("La carte partout.", "Paiement par carte et sans contact dans toutes nos voitures."),
      ("La sécurité de nuit.", "Le chauffeur attend que vous soyez entré avant de repartir."),
      ("Des taxis officiels.", "Voitures autorisées, compteurs contrôlés, chauffeurs professionnels."),
    ],
    "reviews": [
      ("« Appel à 2 h du matin en sortant du bar, taxi là en 8 minutes, et il a attendu que je sois rentrée. »", "Manon G. · Lille · Retour de soirée"),
      ("« Réservé la veille pour un vol à 6 h, le taxi était devant chez moi à 4 h 25. Parfait. »", "Hugo B. · Wazemmes · Aéroport"),
    ],
    "faq": [
      ("Combien de temps pour avoir un taxi à Lille ?", "En moyenne une dizaine de minutes dans Lille intra-muros, un peu plus en périphérie ou aux heures de pointe. Vous recevez l'heure d'arrivée par SMS."),
      ("Peut-on payer par carte ?", "Oui, tous nos taxis acceptent la carte bancaire et le paiement sans contact."),
      ("Faut-il réserver pour la gare ou l'aéroport ?", "C'est conseillé aux heures de pointe et pour les départs très matinaux. Pour une course immédiate, appelez directement."),
      ("Combien coûte un taxi pour l'aéroport de Lesquin ?", "Le prix dépend de votre adresse de départ et de l'heure (tarif de nuit). Nous vous donnons une estimation à la réservation."),
      ("Allez-vous en Belgique ?", "Oui, Bruxelles, Courtrai ou Tournai, avec un prix annoncé avant le départ."),
      ("Proposez-vous des comptes entreprise ?", "Oui, avec bons de transport et facturation mensuelle."),
    ],
    "quote_h2": "Réservez à l'avance.", "quote_p": "Pour une course immédiate, appelez le 06 39 98 55 03. Pour plus tard, indiquez votre trajet ici.",
    "work_label": "Type de trajet",
    "works": ["Gare", "Aéroport de Lille-Lesquin", "Retour de soirée", "Métropole", "Longue distance", "Autre"],
    "extra": ("flight", "Numéro de vol ou de train", "Ex. : TGV 7012", True),
    "to_ph": "Ex. : gare Lille-Europe",
    "details_label": "Informations utiles",
    "details_ph": "Ex. : 2 valises, siège enfant",
    "success": "Merci {first}. Votre réservation est enregistrée : vous recevez la confirmation et le numéro du taxi par SMS.",
    "success_end": "",
    "nav": NAV,
  },
]
